### ISSUE TITLE
Where is quiet in the python API?

### ISSUE THREAD

**Issue by domoritz** [potassco/clingo#106]
I'm trying to access the `--quiet` flag from the python API but I cannot find it in `prg.configuration`. Is it accessible?

**Comment by rkaminsk** [comment]
This is not possible via the API. Only solving options are supported.

**Comment by domoritz** [comment]
I see. My use case is that I would like to show a warning if the quiet option is not what I expected it to be. If it's easy to add (even a read only) member to access the quiet parameter, then consider this a feature request. If it's not easy, feel free to close this issue as resolved.

**Comment by rkaminsk** [comment]
I do not see a nice way to add this. There are two aspects of clingo: the application and the library. Both can be extended/used using the same API. So the API comprises a common subset of the functionality offered by both. There simply are no application options for the library.
