### ISSUE TITLE
add_clause and add_nogood behavior depends of literal assignation

### ISSUE THREAD

**Issue by Aluriak** [potassco/clingo#107]
I found an unexplained behavior of add_clause and add_nogood when fed with a literal that already have the given value. For instance, `add_clause([2, -2])` when literal 2 is assigned to True.

Maybe this behavior is normal, but it seems not documented.
Maybe it is linked to #104 ?

See file `l.lp` for MWE:

```python
#script(python)
SHOW_BUG = True

class Propagator:
    def init(self, init):
        "watch all literals, remember ko and p atoms"
        for atom in init.symbolic_atoms:
            lit = init.solver_literal(atom.literal)
            init.add_watch(lit)
            if atom.symbol.name == 'p':  # the atom to use to discard models
                self.discard_atom = lit
            elif atom.symbol.name == 'ko':  # determine if a model must be discarded
                self.ko_atom = lit

    # def propagate(self, ctl, _):  # behavior is different (but still buggy) with propagate
    def check(self, ctl):
        "if the ko atom is true, discard the model"
        if ctl.assignment.value(self.ko_atom):
            adder = ctl.add_nogood  # behavior is the same with ctl.add_clause
            lit = self.discard_atom
            value = ctl.assignment.value(lit)
            if SHOW_BUG:  # naïve implementation : send both lit and -lit whatever its value
                clause = [lit, -lit]
            elif value is None:  # working implementation : given arg depends on assignation
                clause = [lit, -lit]
            elif value is False:
                clause = [lit]
            elif value is True:
                clause = [-lit]
            if adder == ctl.add_nogood:  # note that 'is' does not behave as expected
                clause = [-lit for lit in clause]
            if not adder(clause) or not ctl.propagate():
                return


def main(prg):
    prg.register_propagator(Propagator())
    prg.ground([('base', [])])
    prg.solve()
#end.


ok;ko.
{p}.
```

Running `clingo l.lp 0` will, in both 5.2.1 and 5.2.2 output the following:

```
[…]
Answer: 1
ok
Answer: 2
ok p
Answer: 3
ko
Answer: 4
ko p
SATISFIABLE
[…]
```

It seems that the discarding is non functional. However, when choosing the arguments to add_clause/add_nogood according to the `p` atom value, it works (to enable that, set `SHOW_BUG` to `False`):

```
[…]
Answer: 1
ok
Answer: 2
ok p
SATISFIABLE
[…]
```

Few notes:

- the naïve implementation consist in giving `[lit, -lit]` to add_clause/add_nogood, whatever the assigned value of `lit` is.
- both add_nogood and add_clause are touched.
- using any symbol (not necessarily `p`) to discard a model would lead to the same behavior.
- using `propagate` instead of `check` in Propagator lead to the output of an invalid answer set, even with the working implementation.
- `assert ctl.add_nogood is ctl.add_nogood` raises an assertion error. Not related to the problem here, but that's unexpected.

**Comment by rkaminsk** [comment]
I cannot follow you. Adding a clause (or nogood) of form [lit,-lit] does not have any effect. Such a clause is always satisfied. Clingo's behavior looks alright to me.

**Comment by Aluriak** [comment]
I bet it's because i did not understood what is a clause. This fixes the problem.

**Comment by rkaminsk** [comment]
What about the Wikipedia article: https://en.wikipedia.org/wiki/Clause_(logic)

**Comment by Aluriak** [comment]
Thanks. Is multiple calls to `add_clause` the way to get a conjunctive clause ?

**Comment by rkaminsk** [comment]
Since all added clauses have to be satisfied, you can think of adding a formula in CNF like this.
