### ISSUE TITLE
Compilation problems on Windows for release 5.3.0

### ISSUE THREAD

**Issue by ysard** [potassco/clingo#117]
Hello, I'm facing some compilation problems under Windows, with Mingw and MSVC.

First of all, here is my configuration:

- Windows 7
- MinGW-W64 GCC-8.1.0, from [here](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/)
- Python 2.7.15 version amd64
- Microsoft Visual Studio 15 2017
- clingo 5.3.0

Source preparation with cmake:

    cmake -G "MinGW Makefiles" ../
    cmake -G "NMake Makefiles" ../
    cmake -G "Visual Studio 15 2017 Win64" ../

## First bug with MinGW:

    C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/cmath:1121:11: error: '::hypot' has not been declared

This error is resolved on [this stackoverflow post](https://stackoverflow.com/questions/10660524/error-building-boost-1-49-0-with-gcc-4-7-0/).

In fact `pyconfig.h` on Windows seems to define `hypot` as `_hypot` which subsequently
cripples the declaration of `hypot`  in `math.h` and ultimately breaks the using
declaration in `cmath`.

The resolution of the specific bug of MinGW is done by the definition of the macro
before importing `Python.h`:

    #if defined(__GNUC__) && defined(_WIN32)
    #define _hypot hypot
    #endif

## Second bug in the linking step:

    build\temp.win-amd64-2.7\Release\lippyclingo\pyclingo.o:pyclingo.cc:(.text+0x2a641): undefined reference to `__imp_Py_InitModule4`

The bug is identified on [stackoverflow](https://stackoverflow.com/questions/2842469/python-undefined-reference-to-imp-py-initmodule4).

MinGW does not seem to define some variables that MSVC systematically defines.
Adding the following macro to the compiler fixes the bug:

    -DMS_WIN64

## Bugs with MSVC:

Preparation with cmake:

    c:\clingo\build>cmake -G "NMake Makefiles" ../
    Re-run cmake no build system arguments
    -- The C compiler identification is MSVC 19.14.26431.0
    -- The CXX compiler identification is MSVC 19.14.26431.0
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
    2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
    2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
    o/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
    o/2017/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: C:/Python27/python.exe (found version "2.7.15")
    -- Found PythonLibs: C:/Python27/libs/python27.lib (found version "2.7.15")
    -- Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
    -- Could NOT find BISON: Found unsuitable version "2.4.1", but required is at le
    ast "2.5" (found C:/Program Files (x86)/GnuWin32/bin/bison.exe)
    -- Could NOT find RE2C (missing: RE2C_EXECUTABLE) (Required is at least version
    "0.13")
    -- Looking for pthread.h
    -- Looking for pthread.h - not found
    -- Found Threads: TRUE
    -- Potassco is not installed - using local copy
    -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
    -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/clingo/build

Compilation with nmake:

    ...
    [ 61%] Building CXX object libgringo/CMakeFiles/libgringo.dir/src/input/aggregate.cc.obj
        cd C:\clingo\build\libgringo
        C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x64\cl.exe @C:\Users\ysard\AppData\Local\Temp\nm520.tmp
    aggregate.cc
        cd C:\clingo\build
    [ 62%] Building CXX object libgringo/CMakeFiles/libgringo.dir/src/input/aggregates.cc.obj
        cd C:\clingo\build\libgringo
        C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x64\cl.exe @C:\Users\ysard\AppData\Local\Temp\nmA03.tmp
    aggregates.cc
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\xmemory0(920): error C2280: 'std::pair<const _Kty,_Ty>::pair(const std::pair<const _Kty,_Ty> &)'ÿ: tentative de référencement d'une fonction supprimée
            with
            [
                _Kty=Gringo::UTerm,
                _Ty=Gringo::UTerm
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\utility(136): note: voir la déclaration de 'std::pair<const _Kty,_Ty>::pair'
            with
            [
                _Kty=Gringo::UTerm,
                _Ty=Gringo::UTerm
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\list(769): note: voir la référence à l'instanciation de la fonction modèle 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,const std::pair<const _Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>>&>(_Alloc &,_Objty *const ,const std::pair<const _Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>> &)' en cours de compilation
            with
            [
                _Alloc=std::allocator<std::_List_node<std::pair<const Gringo::UTerm,Gringo::UTerm>,std::_Default_allocator_traits<std::allocator<std::pair<const Gringo::UTerm,Gringo::UTerm>>>::void_pointer>>,
                _Ty=std::pair<const Gringo::UTerm,Gringo::UTerm>,
                _Kty=Gringo::UTerm,
                _Objty=std::pair<const Gringo::UTerm,Gringo::UTerm>
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\list(767): note: voir la référence à l'instanciation de la fonction modèle 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,const std::pair<const _Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>>&>(_Alloc &,_Objty *const ,const std::pair<const _Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>> &)' en cours de compilation
            with
            [
                _Alloc=std::allocator<std::_List_node<std::pair<const Gringo::UTerm,Gringo::UTerm>,std::_Default_allocator_traits<std::allocator<std::pair<const Gringo::UTerm,Gringo::UTerm>>>::void_pointer>>,
                _Ty=std::pair<const Gringo::UTerm,Gringo::UTerm>,
                _Kty=Gringo::UTerm,
                _Objty=std::pair<const Gringo::UTerm,Gringo::UTerm>
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\list(1004): note: voir la référence à l'instanciation de la fonction modèle 'std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer> *std::_List_buy<_Ty,_Alloc>::_Buynode<const std::pair<const _Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>>&>(std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer> *,std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer> *,const std::pair<const _Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>> &)' en cours de compilation
            with
            [
                _Ty=std::pair<const Gringo::UTerm,Gringo::UTerm>,
                _Alloc=std::allocator<std::pair<const Gringo::UTerm,Gringo::UTerm>>,
                _Kty=Gringo::UTerm
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\list(1004): note: voir la référence à l'instanciation de la fonction modèle 'std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer> *std::_List_buy<_Ty,_Alloc>::_Buynode<const std::pair<const _Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>>&>(std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer> *,std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer> *,const std::pair<const _Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>> &)' en cours de compilation
            with
            [
                _Ty=std::pair<const Gringo::UTerm,Gringo::UTerm>,
                _Alloc=std::allocator<std::pair<const Gringo::UTerm,Gringo::UTerm>>,
                _Kty=Gringo::UTerm
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\list(968): note: voir la référence à l'instanciation de la fonction modèle 'void std::list<std::pair<const _Kty,_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>::_Insert<const std::pair<const _Kty,_Ty>&>(std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>,std::_Iterator_base0>,const std::pair<const _Kty,_Ty> &)' en cours de compilation
            with
            [
                _Kty=Gringo::UTerm,
                _Ty=Gringo::UTerm
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\list(968): note: voir la référence à l'instanciation de la fonction modèle 'void std::list<std::pair<const _Kty,_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>::_Insert<const std::pair<const _Kty,_Ty>&>(std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>,std::_Iterator_base0>,const std::pair<const _Kty,_Ty> &)' en cours de compilation
            with
            [
                _Kty=Gringo::UTerm,
                _Ty=Gringo::UTerm
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\xhash(302): note: voir la référence à l'instanciation de la fonction modèle 'void std::list<std::pair<const _Kty,_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>::emplace_front<const std::pair<const _Kty,_Ty>&>(const std::pair<const _Kty,_Ty> &)' en cours de compilation
            with
            [
                _Kty=Gringo::UTerm,
                _Ty=Gringo::UTerm
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\xhash(585): note: voir la référence à l'instanciation de la fonction modèle 'std::pair<std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>,bool> std::_Hash<std::_Umap_traits<_Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::emplace<const std::pair<const _Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>>&>(const std::pair<const _Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>> &)' en cours de compilation
            with
            [
                _Ty=std::pair<const Gringo::UTerm,Gringo::UTerm>,
                _Kty=Gringo::UTerm,
                _Hasher=Gringo::value_hash<Gringo::UTerm>,
                _Keyeq=Gringo::value_equal_to<Gringo::UTerm>,
                _Alloc=std::allocator<std::pair<const Gringo::UTerm,Gringo::UTerm>>
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\xhash(585): note: voir la référence à l'instanciation de la fonction modèle 'std::pair<std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>,bool> std::_Hash<std::_Umap_traits<_Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::emplace<const std::pair<const _Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>>&>(const std::pair<const _Kty,std::unique_ptr<Gringo::Term,std::default_delete<Gringo::Term>>> &)' en cours de compilation
            with
            [
                _Ty=std::pair<const Gringo::UTerm,Gringo::UTerm>,
                _Kty=Gringo::UTerm,
                _Hasher=Gringo::value_hash<Gringo::UTerm>,
                _Keyeq=Gringo::value_equal_to<Gringo::UTerm>,
                _Alloc=std::allocator<std::pair<const Gringo::UTerm,Gringo::UTerm>>
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\xhash(1113): note: voir la référence à l'instanciation de la fonction modèle 'void std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::insert<std::_List_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>>(_Iter,_Iter)' en cours de compilation
            with
            [
                _Kty=Gringo::UTerm,
                _Ty=Gringo::UTerm,
                _Hasher=Gringo::value_hash<Gringo::UTerm>,
                _Keyeq=Gringo::value_equal_to<Gringo::UTerm>,
                _Alloc=std::allocator<std::pair<const Gringo::UTerm,Gringo::UTerm>>,
                _Iter=std::_List_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const Gringo::UTerm,Gringo::UTerm>>>>
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\xhash(1113): note: voir la référence à l'instanciation de la fonction modèle 'void std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::insert<std::_List_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>>>(_Iter,_Iter)' en cours de compilation
            with
            [
                _Kty=Gringo::UTerm,
                _Ty=Gringo::UTerm,
                _Hasher=Gringo::value_hash<Gringo::UTerm>,
                _Keyeq=Gringo::value_equal_to<Gringo::UTerm>,
                _Alloc=std::allocator<std::pair<const Gringo::UTerm,Gringo::UTerm>>,
                _Iter=std::_List_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const Gringo::UTerm,Gringo::UTerm>>>>
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\xhash(1105): note: pendant la compilation de la fonction membre '<Inconnu>' (classe <Inconnu>)
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\xhash(215): note: voir la référence à l'instanciation de la fonction modèle 'void std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::_Copy(const std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>> &)' en cours de compilation
            with
            [
                _Kty=Gringo::UTerm,
                _Ty=Gringo::UTerm,
                _Hasher=Gringo::value_hash<Gringo::UTerm>,
                _Keyeq=Gringo::value_equal_to<Gringo::UTerm>,
                _Alloc=std::allocator<std::pair<const Gringo::UTerm,Gringo::UTerm>>
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\unordered_map(97): note: voir la référence à l'instanciation de classe modèle 'std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>' en cours de compilation
            with
            [
                _Kty=Gringo::UTerm,
                _Ty=Gringo::UTerm,
                _Hasher=Gringo::value_hash<Gringo::UTerm>,
                _Keyeq=Gringo::value_equal_to<Gringo::UTerm>,
                _Alloc=std::allocator<std::pair<const Gringo::UTerm,Gringo::UTerm>>
            ]
    C:\clingo\libgringo\gringo/input/literals.hh(96): note: voir la référence à l'instanciation de classe modèle 'std::unordered_map<Gringo::UTerm,Gringo::UTerm,Gringo::value_hash<Gringo::UTerm>,Gringo::value_equal_to<Gringo::UTerm>,std::allocator<std::pair<const _Kty,_Ty>>>' en cours de compilation
            with
            [
                _Kty=Gringo::UTerm,
                _Ty=Gringo::UTerm
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\utility(136): note: 'std::pair<const _Kty,_Ty>::pair(const std::pair<const _Kty,_Ty> &)'ÿ: la fonction a été supprimée implicitement, car un données membres appelle une fonction supprimée ou inaccessible 'std::unique_ptr<Gringo::Term,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)'
            with
            [
                _Kty=Gringo::UTerm,
                _Ty=Gringo::UTerm
            ]
            and
            [
                _Ty=Gringo::Term
            ]
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\memory(2308): note: 'std::unique_ptr<Gringo::Term,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)'ÿ: la fonction a été supprimée explicitement
            with
            [
                _Ty=Gringo::Term
            ]
    NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x64\cl.exe' : code retour '0x2'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX64\x64\nmake.exe"' : code retour '0x2'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX64\x64\nmake.exe"' : code retour '0x2'
    Stop.

I'm sorry for this big dump, but i don't really know how to solve this.

MinGW is a less used compiler but in my opinion, it is much easier to install than MSVC.
That's why I did some tests with it.

Thanks for reading me :)

**Comment by rkaminsk** [comment]
Hi, thanks for reporting these issues. I will have a look.

- The hypot thing looks like this is ultimatively a compiler bug. Some feature test macro in cmake might be the best option to workaround this.
- Using mingw linking with an msvc compiled python is not recommended because this breaks some things: <https://bugs.python.org/issue4709#msg243605>. It might be better to not even support this. Or is this macro also required with a mingw compiled python?
- I will look into compilation with msvc 15. With msvc 14 things are definitely working because the CI tests are up and running reliably.

PS: Have you considered installing clingo with anaconda? This should be really easy and you get msvc 14 compiled binaries with python 3 support and easy installation of further python packages.

**Comment by ysard** [comment]
Thank you for your reply.

* Yes, this is a compiler bug, 

* Yes indeed I had read this page; the good news seems to be that things should work out (https://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/, https://blogs.msdn.microsoft.com/vcblog/2014/06/10/the-great-c-runtime-crt-refactoring/), I have not yet had time to read all these resources, but anyway python 2.7 is still compiled with Visual Studio 2008 (...).
I agree that officially supporting this compiler may not guarantee a correct compilation, but it is a compiler used in general by people working with Cygwin or from the Linux world. Anyway, with these 2 macros, the extension compiles correctly and can be imported from Python.
For the moment I do not have any idea of the edge effects that this compiler can cause.

* To be honest I'm interested in the "old-style" packaging of the Python extension: via PyPI, from sources or via wheels (pre-compiled binaries). In fact, many projects simply require a lightweight package to install with `pip install <package>` command. That's why I tested several compilers including Visual Studio 2017 that I downloaded naïvely, because this is the latest version available on the Microsoft website. I will indeed try to go back to the previous version.

**Comment by rkaminsk** [comment]
- \-
- Compiling clingo with cygwin should just work and it should work with cygwin's python. I set up CI tests for this. Unfortuantely, there are so many mingw, msys, msys2, etc. compilers that it is hard to keep track. I can add the macros. It is just a bit tricky to add the macros only when required.
- The idea is to support all msvc>=14 compilers. I will try to make the latest version work, too. I find pip as a package manager unsatisfactorily that is why I was suggesting anaconda (or miniconda if you want something a little more lightweight). It will eat a little more disk space though but is in my opinion worth it.

**Comment by rkaminsk** [comment]
With commit e4da5356479901baebbba9ddc656463cb65e0522, clingo should compile with msvc 15 now too.

**Comment by rkaminsk** [comment]
I could add the following macros before including the Python header. I decided to make these mingw specific because they should only be necessary for this specific compiler. Can you check if this works in your environment please?

```c
#ifdef __MINGW32__
#  define _hypot hypot
#endif

#ifdef __MINGW64__
#  define MS_WIN64
#endif
```

**Comment by rkaminsk** [comment]
I added a workaround for the msvc issue. I decided not to address the mingw issues because ideally this should be fixed in the mingw or python projects.
