### ISSUE TITLE
Build fails on Archlinux ARM

### ISSUE THREAD

**Issue by vbmithr** [potassco/clingo#12]
Build log here: http://pastebin.com/7uX5Kgda

**Comment by rkaminsk** [comment]
On my OS Python's hashfunc is defined as
  typedef long (*hashfunc)(PyObject *);
Apparently, for the ARM version the return value is int. I will look into how to fix this. For now, you could simply build without python support. -R

**Comment by rkaminsk** [comment]
The issue is fixed in the cmake branch I am currently working on. The upcoming 5.2 release will contain the fix.
