### ISSUE TITLE
C++ API for Configurations does not work

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#120]
Deriving from Clingo::Application
in main

```
std::cout << "conf description " << std::endl;
std::cout << "isMap: " << ctl.configuration().is_map() << std::endl;
std::cout << "size: " << ctl.configuration().keys().size() << std::endl;
for (auto i : ctl.configuration().keys()) {
    std::cout << "key: " << std::endl;
}
```
Seems to be a problem with incrementing the iterators.
Output:
conf description 
isMap: 1
size: 11
key: 

Command terminated

**Comment by rkaminsk** [comment]
Can you send something I can compile, please? In principle, there is a test for iterating over keys, which is working.

**Comment by MaxOstrowski** [comment]
MWE:
https://github.com/potassco/clingoDL/tree/bug

**Comment by rkaminsk** [comment]
You code is invalid. You must write
```c++
auto conf = ctl.configuration();
for (auto key : conf.keys()) {
    std::cerr << "key: " << key << std::endl;
}

```

**Comment by MaxOstrowski** [comment]
Is there any rule to this ?
Do i have to keep a copy of the configuration object ?
Is it possible to access the "--text" option from this interface (i have found nothing like this in the keys), as I have to intercept this option in the main loop for the correct behavior.

Thanks a lot.

**Comment by rkaminsk** [comment]
> Is there any rule to this?

It is how range based for loops work in C++.

> Is it possible to access the "--text" option from this interface?

The configuration object is only for clasp options. Currently it is not possible to detect (cleanly) if the text ouput is enabled. The API would have to be extended.
