### ISSUE TITLE
Python API: comparison operators and returning NotImplemented

### ISSUE THREAD

**Issue by daveraja** [potassco/clingo#129]
Currently, if you a perform an (in-)equality comparison of a python wrapped clingo object with another object of a different type the behaviour is to return that the objects are not equal.

For example, looking at the Symbol object and comparing with a non-Symbol object, the following works:
```
  func = clingo.Function("somefunc",[])
  assert  func != 3          # assertion passes
```
However, from what I can gather this is not considered good idiomatic python behaviour. Instead I think the correct thing to do is to return ``NotImplemented``.  The reason is that by returning ``NotImplemented`` the python interpreter can try different ways of satisfying the comparison; such as reversing the comparison.

To makes things concrete... I want to provide a wrapper around a Symbol object and then overload the equality operator to allow my wrapper object to compare the underlying Symbol object. The following is not exactly what I'm doing but gives the right idea:
```
class Wrapper(object):
    def __init__(self, symbol):
        self._symbol=symbol
   def  __eq__(self, other):
       if isinstance(other,Wrapper):
            return self._symbol == other._symbol
       elif type(other) == clingo.Symbol:
            return self._symbol == other
       else:
           return NotImplemented

func = clingo.Function("somefunc",[])
wfunc = Wrapper(Function("somefunc",[]))

assert wfunc == func        # this holds
assert func != wfunc        # but so does this!
```
The two asserts above show the resulting unintuitive behaviour (note: I'm assuming the ``__ne__`` operator defined appropriately). The reason is that the first assert calls the Wrapper equality operator while the second calls the inbuilt Symbol equality operator. However, if the Symbol operator was changed to return NotImplemented then, from what I've read, the python interpreter would be smart enough to try the reverse comparison, and would then call the Wrapper equality operator. 

From what I can see making the change would be in ``libpyclingo/pyclingo.cc, line 910`` and would be a matter of returning Py_NotImplemented (or the macro Py_RETURN_NOTIMPLEMENTED). This may also be a better return value for the ordered comparison operators which current generate an "unorderable types" error.

I'm happy to try and make this change and create a pull request, but wasn't sure if you'd agree that this was the correct behaviour.

**Comment by rkaminsk** [comment]
The objects in the clingo API have been designed with the idea in mind that comparisons across different types are not necessary. Because I am not a fan of this. But this does not mean we cannot implement your request. There is no harm in offering this functionality. We might have to replace the whole block from line 910 to 923 with `Py_RETURN_NOTIMPLEMENTED`. I have to consult my Python book before doing this. :wink:

**Comment by daveraja** [comment]
Great, thanks. Have a look at it and see what you think. I tested it out and it seems to work as expected, but I'm also not sure if it would cause some unintended behaviour changes.
