### ISSUE TITLE
Watching all literals results in segfault

### ISSUE THREAD

**Issue by tsahyt** [potassco/clingo#13]
I was trying to reimplement the dot propagator using Haskell bindings that I have been writing and ran into a segfault. Upon writing an equivalent C implementation the segfault still exists, and it occurs independently of the propagate and undo methods, so I have omitted these from the code snippet below.

The code iterates over the symbolic atoms during the init method of the propagator and sets a watch on all of them. However, setting a watch to literal 30 or higher (1 indexed) triggers the problem. It works fine when omitting those higher literals. I have not been able to find any notable difference between literals <30 and >=30.

I am not completely sure whether the problem is on my end or not, but this should constitute a 1:1 translation of the init method from the Python example.

I have attached both the source causing the problem, and the test file below (althoiugh github does not accept the correct filetypes for some reason).

[dot-segfault.txt](https://github.com/potassco/clingo/files/577677/dot-segfault.txt)

[test.txt](https://github.com/potassco/clingo/files/577679/test.txt)

**Comment by rkaminsk** [comment]
Hi, you forgot to call [`clingo_propagate_init_solver_literal`](https://potassco.org/clingo/c-api/current/group__propagator#ga24ffe5c89ab1629271e53be60c7cff9d) to map the program literal you get with `clingo_symbolic_atoms_literal` to a solver literal. After doing that, your propagator should work.

**Comment by tsahyt** [comment]
Thank you! I have tried it in both languages and it works. I have missed that the clingo_literal_t type can refer to two different kinds of literals here. I'll be sure to make this a compile time error in my bindings.
