### ISSUE TITLE
Dot propagator prints the first dot before solving starts (according to logs)

### ISSUE THREAD

**Issue by Aluriak** [potassco/clingo#130]
While running the dot-propagator example, i got the following output:

    $ clingo dot.lp test.lp
    clingo version 5.3.1
    Reading from dot.lp ...
    .Solving...

    UNSATISFIABLE

    Models       : 0
    Calls        : 1
    Time         : 15.389s (Solving: 15.27s 1st Model: 0.00s Unsat: 15.27s)
    CPU Time     : 0.055s

The first dot is printed before the «Solving...» print.

Why is that ?

**Comment by rkaminsk** [comment]
If you check the decision level of the assignment at this point, you will see that it is zero. All consequences on this level are propagated before the actual solving starts. Also, if something is propagated on level 0, then there won't be a matching call to undo. So it might even make sense not to print a dot for such levels.

**Comment by Aluriak** [comment]
Sounds good to me. Thanks !
