### ISSUE TITLE
Clingo Killed Execution

### ISSUE THREAD

**Issue by MhmdSaiid** [potassco/clingo#136]
Hello,
I am using clingo 5.3.1.
I am executing the code and the process is being killed.
I believe this is due to the large search space.
Is there way to resolve this?
The code is being called when a Control object calls its "solve()" method. Specifically, in this line:

`-> self.sampling_control.solve([], lambda model: self.models.append(model.symbols(atoms=True)))
`

Thanks in advance.

**Comment by rkaminsk** [comment]
I do not have enough information to really help you, but some remarks:
- If your program has too many solutions, your code is bound to fail. Maybe limit the number of models?
- If your input program is too large, you should consider optimizing it to be better solvable. This might be difficult. If you just want to experiment with sampling, you could restrict yourself to manageable input programs.

**Comment by rkaminsk** [comment]
Closing. Feel free to reopen but please add more information in this case.

**Comment by MhmdSaiid** [comment]
Thank you! I am trying to limit the number of models as you suggested.
