### ISSUE TITLE
Clingo Portfolio Settings

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#139]
Is it possible to change the portfolio settings (configurations for several threads) using the API.
Currently it is not possible to use options added via the API in the portfolio configuration file accepted by clingo. This would allow us to set user specified options on a per thread level.

**Comment by rkaminsk** [comment]
You can set thread specific options via the configuration.

**Comment by MaxOstrowski** [comment]
Wouldn't it be nice to be able to use the portfolio feature for this, such that --configuration=file can also parse the added options ?

**Comment by rkaminsk** [comment]
We can collect such feature requests. We already started something like this in #121.
