### ISSUE TITLE
Allow tuples as level in heuristic statements

### ISSUE THREAD

**Issue by wanko** [potassco/clingo#140]
This would easily allow for lexicographic orderings of choices for atoms.
For example, with the call 
`echo "1={a(1,b);a(1,c);a(2,a)}. #heuristic a(X,Y).[(X,Y),true]" | clingo - 0 --heur=Domain`
I would expect
```
clingo version...
Reading from -
Solving...
Answer: 1
a(2,a)
Answer: 2
a(1,c)
Answer: 3
a(1,b)
SATISFIABLE
```

**Comment by rkaminsk** [comment]
For this, we would have to support gringo terms in the aspif output. It is very unlikely that this will be implemented. You have to stick to integers.
