### ISSUE TITLE
#show is not effective if only conditional #show's exist

### ISSUE THREAD

**Issue by peschue** [potassco/clingo#141]
The following program shows two answer sets "a foo(a) bar(a)" and "b foo(a) bar(a)" instead of two  answer sets "foo(a)" and "foo(a)".

    a :- not b.
    b :- not a.
    bar(a).
    #show foo(X) : bar(X).

The result is

```
clingo version 5.3.0
Reading from test.lp
Solving...
Answer: 1
bar(a) foo(a) b
Answer: 2
bar(a) foo(a) a
SATISFIABLE
```

If I add a "#show." before the conditional #show line, it works as espected.

    a :- not b.
    b :- not a.
    bar(a).
    #show.
    #show foo(X) : bar(X).

This results in

```
clingo version 5.3.0
Reading from test.lp
Solving...
Answer: 1
foo(a)
Answer: 2
foo(a)
SATISFIABLE
```

**Comment by rkaminsk** [comment]
> If I add a "#show." before the conditional #show line, it works as expected.

It is intended like this.

**Comment by MaxOstrowski** [comment]
The conditional #show statement only shows *extra* information, therefore, still all predicates are shown.
If you use `#show pred/2.` instead, this will hide all predicates except the ones that are shown.

**Comment by peschue** [comment]
Thank you!

In summary, 

* using unconditional `#show X.` causes an implicit `#show.` (which hides everything that is not shown)
* using conditional `#show X : Y.` does not cause an implicit `#show.`.

Therefore, using only conditional `#show` will not hide anything.
