### ISSUE TITLE
Add a function to the assignment to get the root level.

### ISSUE THREAD

**Issue by rkaminsk** [potassco/clingo#142]

**Comment by mahi045** [comment]
Sorry, I cannot understand what this function is doing. 
I have printed its output. The function is returning 0 (if decision level == 0) or 1 (otherwise). I cannot understand what this 0 or 1 means. I am using Clingo C API.

**Comment by rkaminsk** [comment]
What the function returns depends on how the solver is used. It will only return non-zero values if assumptions are used. There is a short description in the paper *An Extensible SAT-solver* by Niklas Eén and Niklas Sörensson.

> **Root-level.** To support incremental SAT, the concept of a *root-level* is introduced. The root-level acts a bit as a new top-level. Above the root-level are the incremental assumptions passed to `solve()` (if any). The search procedure is not allowed to backtrack above the root-level, as this would change the incremental assumptions. If we reach a conflict at root-level, the search will return `False`.

In your case, when the decision level is zero, there are probably no assumptions yet and later there is an active assumption.
