### ISSUE TITLE
Rewrite python docstrings to use markdown

### ISSUE THREAD

**Issue by rkaminsk** [potassco/clingo#146]
The following tasks remain:
- [x] link known types in type annotations
- [x] document if a class implements a protocol (`Sequence`, `Hashable`, etc.)
- [x] type annotations for classes
- [x] type annotation for global variables
- [x] reformat doc for ast

**Comment by 0x326** [comment]
Correct me if I'm wrong but I think reStructuredText is more idiomatic for Python documentation than Markdown

**Comment by rkaminsk** [comment]
My plan is to use [pdoc](https://pdoc3.github.io/pdoc/) to generate the documentation. I was looking for something lightweight I can easily embed into our website. Python's sphinx is a bit overweight in my opinion...

**Comment by 0x326** [comment]
@rkaminsk Fair enough. I hadn't heard of `pdoc` before
