### ISSUE TITLE
It should be possible to return arbitrary sequences and not just lists from external python functions.

### ISSUE THREAD

**Issue by rkaminsk** [potassco/clingo#147]

**Comment by Aluriak** [comment]
Are generators supported ?

    def g():
        yield from (1, 2, 3)

**Comment by rkaminsk** [comment]
Yes, anything that is iterable is supported. But note that `str` and `tuple` is converted to `clingo.String` and `clingo.Tuple`.

**Comment by Aluriak** [comment]
Thank you !

**Comment by marypopa** [comment]
Hi! I have a problem. I run this code with the clyngor in python 
`from clyngor import ASP, solve

answers = ASP("""
rel(a,(c;d)). rel(b,(d;e)).
obj(X):- rel(X,_) ; rel(X,Y): att(Y).
att(Y):- rel(_,Y) ; rel(X,Y): obj(X).
:- not obj(X):obj(X).
:- not att(Y):att(Y).
""")
for answer in answers:
    print(answer)`
and I get this error 
`
FileNotFoundError: [WinError 2] The system cannot find the file specified
`

**Comment by Aluriak** [comment]
@marypopa Sounds like a clyngor related problem. Please file this issue on [clyngor repository](https://github.com/Aluriak/clyngor/issues), i will study it as soon as possible.
