### ISSUE TITLE
How to set time limit in python clingo-API

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#151]
I am using python clingo-API. How I can set a time limit (`--time-limit=<n>`) for Control.solve() call?

**Comment by rkaminsk** [comment]
This option is not available via the API. You can use clingo's asynchronous solving facility to achieve the same though.

**Comment by rkaminsk** [comment]
I just paste an example to give you an idea. If you also want to put a limit on the grounding time, then it might be better to control the process externally because there is no clean way to stop grounding.

```python
import clingo

limit=3

def on_model(m):
    print (m)

prg = clingo.Control()

prg.add("base", [], """
#const n = 20.

1 { p(X); q(X) } 1 :- X = 1..n.
:- not n+1 { p(1..n); q(1..n) }.
""")
prg.ground([("base", [])])

with prg.solve(on_model=on_model, async_=True) as handle:
    handle.wait(limit)
    handle.cancel()
    print (handle.get())
```
