### ISSUE TITLE
Another yet helpful example

### ISSUE THREAD

**Issue by flavioeverardo** [potassco/clingo#152]
I would suggest to include a basic example of how to get the answer sets in a list directly from the solve call. 
Particularly, this small code has been very useful in case you need to process further the output from clingo.
```
import clingo
answer_sets = []
ctl = clingo.Control()
ctl.add("base", [], "{a;b}.")
ctl.ground([("base", [])])
ctl.solve(None, lambda model:answer_sets.append(model.symbols(shown=True)))
for answer in answer_sets:
        print answer
```
output:
```
[]
[b]
[a]
[a, b]
```

If it is not interesting enough, please close this issue ;-)

**Comment by rkaminsk** [comment]
Such an example would fit in the Model class description. I'll have a look.
