### ISSUE TITLE
Giving input file in Clingo C API 

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#153]
I am working with **Clingo C API**. I write a C program (viz, test.c) with including ``clingo.h`` header file. I build the C program using the command ``g++ test.c  -o test -lclingo``.

I run the binary file (``test``) by command ``./test test.lp`` (test.lp contains an ASP program) and get the following error. Parameter ``test.lp`` is given to **clingo_control_new** function as argument.
```
In context '<libclingo>': unknown option: 'Positional Option'
```
How to give input file when using **Clingo C API**.
N.b. I cloned the master branch.

**Comment by rkaminsk** [comment]
You can load files using [clingo_control_load](https://potassco.org/clingo/c-api/5.3/group__control#gacd916338afc7dd07cb33ae3eca50353d) or, alternatively, load a program from a string with [clingo_control_add](https://potassco.org/clingo/c-api/5.3/group__control#gada7b7f54331abfedf60fac33d742c0dc). Also check the examples linked below the documentation of the functions.
