### ISSUE TITLE
Add clause from clingo_propagator::init() function

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#157]
From clingo C API, I want to add some clauses from **clingo_propagator::init()** function. Is there any function/way to add some clauses from `clingo_propagate_init_t` struct (similar to [clingo_propagate_control_add_clause](https://potassco.org/clingo/c-api/5.1/group__propagator#ga45c65882cf55edcf8782f2ce13d66e2b) function of `clingo_propagate_control_t` struct)?

**Comment by rkaminsk** [comment]
There is no interface for this. But you can add rules via the backend before solving starts. Have a look at the backend [example].

[example]: https://potassco.org/clingo/c-api/5.1/backend_8c-example.html

**Comment by mahi045** [comment]
Hi,
I want to add clause from **clingo_propagator:: init()** function and the clause will be deleted later (i.e., I want to add learnt/volatile clause for propagation at decision level 0). Does [clingo_backend_rule](https://potassco.org/clingo/c-api/5.1/group__programbuilder#ga89dd64e084d6432e48b097a049d0bf8f) function fit this need?

Sorry for reopening the issue after a long time.

**Comment by rkaminsk** [comment]
The answer is still the same. :wink: There is no interface for this but it is possible to achieve the behavior you want. You can add clauses either in a check or propagate call. You could set the propagate mode to fixpoint and then add the clauses in the first check call.
