### ISSUE TITLE
Error when I add "-q1" or "--quiet=1" option in Python API

### ISSUE THREAD

**Issue by zhunyoung** [potassco/clingo#158]
When I initialize a clingo control 
`clingo_control = clingo.Control(["--warn=none", "--opt-mode=optN", "--q1"])`
I got the following error 
`RuntimeError: In context '<libclingo>': unknown option: 'q1'`
Similar error shows when I use option "--quiet=1". How can I solve this error? 
What would be the correct way to obtain all optimal models?

**Comment by rkaminsk** [comment]
When you create a control object like this, application options are not supported. The quiet option would have no effect anyway, because it is just about configuring the output and such a control object produces no output. You have to print the models yourself.

**Comment by zhunyoung** [comment]
I used the following codes to print all models, while sometimes a non-optimal model is also printed out. That's the reason I'm trying to add the "-q1" option to limit output to optimal models.
```
clingo_control = clingo.Control(["--warn=none", "--opt-mode=optN"])
models = []
clingo_control.add("base", [], program)
clingo_control.ground([("base", [])])
clingo_control.solve(None, lambda model: models.append(model.symbols(atoms=True)))
models = [[str(atom) for atom in model] for model in models]

print(models)
```
What would be the correct way to limit output to optimal models?

**Comment by rkaminsk** [comment]
You can use the [optimality_poven] flag of a model to filter non optimal models while enumerating.

[optimality_poven]: https://potassco.org/clingo/python-api/5.3/clingo.html#Model

**Comment by zhunyoung** [comment]
Problem is solved. Thank you so much.
