### ISSUE TITLE
Python documentation for on_finish callback is out of date

### ISSUE THREAD

**Issue by daveraja** [potassco/clingo#159]
The generated Python documentation for the on_finish callback for Control.solve() states that the function takes two parameters: a SolveResult object and a bool indicating if the search was cancelled.

https://github.com/potassco/clingo/blob/master/libpyclingo/pyclingo.cc#L6572

https://github.com/potassco/clingo/blob/master/libpyclingo/pyclingo.cc#L6639

But providing a function with two arguments produces an error. Also the examples in https://github.com/potassco/clingo/blob/master/examples/clingo/solve-async/solve-async-py.lp indicate only one argument.

**Comment by rkaminsk** [comment]
This is a relic of the past, when the `SolveResult` did not have an interrupted attribute. The described interrupted flag is gone and part of the solve result now. I'll update the doc for the next release.

**Comment by rkaminsk** [comment]
Btw. the Python documentation got a complete overhaul. You can have a look (at a not yet fixed version)
[here](https://release--potassco.netlify.com/clingo/python-api/current/). Feedback is welcome!

**Comment by daveraja** [comment]
Thanks. I've started checking out the new docs. It looks really good. BTW. I really like the new Context feature for grounding.
