### ISSUE TITLE
Please join Slack!

### ISSUE THREAD

**Issue by d4hines** [potassco/clingo#161]
Hello all,
I've been fascinated with ASP since my introduction to it at Philadelphia Logic Week last month. I've been raving about it to my Clojure friends since then. Clojure has already adopted Datascript as the lingua franca logic language, and I think they'll be delighted with ASP and Clingo. Like any new language, ASP will take time for people (including myself) to learn and adopt; however, finding community and support will greatly accelerate this process. To that end, I have taken the liberty of creating a Slack workspace for all things LPNMR (complete with a #clingo channel). I would greatly appreciate it if you would join; it would help all us web developers quite a bit.

Here's the link: https://join.slack.com/t/lpnmr/shared_invite/enQtNzA3MzAwMDA4ODIyLTk5NWE5OWUwNWNhNDkxMGZhYmMxZjQ1N2QwZDJiZmU1ZjEyNDI5OTI5MzZlNTAzODQwZTY2N2I4NDYyNDAzMDI

Thanks,
Daniel Hines

**Comment by rkaminsk** [comment]
I joined but chances are I am not going to use it much because I find chat's too distracting to keep them open while working.
