### ISSUE TITLE
atom does not occur in any rule head

### ISSUE THREAD

**Issue by d4hines** [potassco/clingo#162]
Hello!
I'm a total newbie at ASP, so forgive a few dumb questions. I'm writing a JavaScript application that uses the Clingo output as its model, and appends facts to the Clingo input when users perform actions. Here's a (distilled) version of the program:

```
tick(0).
tick(1).

tab(0, a).

# === Tab Inertia ==============================
tab(T, Name) :- tick(T), tab(T-1, Name), not not tab(T, Name).

%=== Rules =====================================

% Close Tab
not tab(T, Name) :- closeTab(T, Name).
tick(T) :- closeTab(T, _).

% Add Tab
tab(T, Name) :- addTab(T, Name).
tick(T) :- addTab(T, _).

%=== Actions ====================================
closeTab(2, a).
```

I get the following error though:
```
17:17-32: info: atom does not occur in any rule head:
```
I've gathered it's complaining that `addTab/2` never shows up anywhere, namely, because a user hasn't yet performed that action. How do I tell Clingo it's ok for `addTab` not to be present yet? Or else, how do I correctly structure my program for the situation?
Many thanks!

**Comment by rkaminsk** [comment]
You can selectively suppress this warning:

    #defined addTab/2.

**Comment by d4hines** [comment]
Thank you, this was what I needed!
