### ISSUE TITLE
Question: Choice Rules vs. Multiple Rules

### ISSUE THREAD

**Issue by d4hines** [potassco/clingo#170]
Hello,
I hope you'll indulge another beginner ASP question. I have cases in my program where a rule has multiple implications, like so:
```
b :- a.
c :- a.
```
When the body of the rule is very complicated, it's confusing to repeat the body for each implication, as I must read it carefully to determine it's actually the same rule. One solution that was proposed to me was a choice rule:
```
2 { b; c } :- a.
```
This seems to me to have different semantics: "choose 2 of the 2 following choices", which seems rather round about. It's not really a choice rule if there's no choice.

If the choice rule is the accepted idiom, I can bite the bullet and write my rules that way. But does that impact performance vs. just having two rules? If so, I'd rather have a macro like the following:
```
b, c :- a.
% expands to
b :- a.
c :- a.
```
Is there no way to express what I mean here, or am I missing something more fundamental?

**Comment by rkaminsk** [comment]
In my experience it seldom occurs that there are a lot of rules having the same body. I would try to avoid this. I cannot really tell from the propositional example but maybe it is a modelling issue? 

If there are really some rules with the same bodies then I see no problem writing them twice (maybe introducing an auxiliary atom to avoid writing complex bodies over and over). For example

```prolog
p(X,Z) :- p(X,Y), p(Y,Z).
p(Z,X) :- p(X,Y), p(Y,Z).
```

could be written as

```prolog
q(X,Z) :- p(X,Y), p(Y,Z).
p(X,Z) :- q(X,Z).
p(Z,X) :- q(X,Z).
```

Note that you can actually write `a, b :- c` but it has a different semantics. Comma in the head is a disjunction not a conjunction.

**Comment by d4hines** [comment]
I figured it might be the case that my real problem is in the model, not the syntax. I'll see if I can't resolve my issue at that level.
Thanks!

**Comment by rkaminsk** [comment]
If you get stuck, just describe your problem and send a small example. Maybe someone can help.
