### ISSUE TITLE
addition operation undefined on result of #min

### ISSUE THREAD

**Issue by keraJLi** [potassco/clingo#172]
When grounding this minimal example clingo says 
```
a(1).               
b(X+1) :- a(X), not b(X).
c(X+1) :- X = #min { Y : b(Y) }.
-:3:3-4: info: operation undefined:
  (1*X+1)
```
even though the answer set of `a(1) b(2) c(3)` seems correct.
This happens with `#max` too, however this does not happen if `b(2).` is explicitly given.
How can that be fixed?

My configuration is 
```
clingo version 5.4.1
Address model: 64-bit

libclingo version 5.4.1
Configuration: with Python 3.7.4, with Lua 5.3.4

libclasp version 3.3.5 (libpotassco version 1.1.0)
Configuration: WITH_THREADS=1
```

**Comment by rkaminsk** [comment]
The `#min` function applied to an empty set evaluates to `#sup`. The addition `1+#sup` is undefined. You could write

    c(X+1) :- X = #min { Y : b(Y) }, X != #sup 

to get rid of the warning.
