### ISSUE TITLE
Python Application Interface

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#174]
I found a mismatch in the Configuration interface when using python.
If this is due to my lacking python skills I'm very sorry.

The following example is given in the API documentation to read the description of the configuration interface:
```
import sys
import clingo

prg = clingo.Control()
print(prg.configuration.solve.__desc_models)
```

When using the clingo_main method using an Application

```
import sys
import clingo

class Application:
    def main(self, prg, files):
        print(prg.configuration.solve.__desc_models)

sys.exit(int(clingo.clingo_main(Application(), sys.argv[1:])))
```

I do get the following error:

>     print(prg.configuration.solve.__desc_models)
>   AttributeError: 'clingo.Configuration' object has no attribute '_Application__desc_models'

**Comment by rkaminsk** [comment]
Strange. Somehow the name gets mangled. I'll look into it later...

```python
import sys
import clingo

def test(cfg):
    print (cfg.__desc_models)

class Application:
    def main(self, prg, files):
        #print(prg.configuration.solve.__desc_models)
        print (getattr(prg.configuration.solve, "__desc_models"))
        print (test(prg.configuration.solve))

sys.exit(int(clingo.clingo_main(Application(), sys.argv[1:])))
```

**Comment by peschue** [comment]
Double underscore is always mangled to make the symbol private and unaccessible from the "outside", e.g., in derived classes. As far as I know, calling such methods is only possible from a method in the same class, not from outside (and calling from a derived class counts as outside).

**Comment by rkaminsk** [comment]
Yes, you are right. I was thinking the name mangling is applied based on the type of the target object but this is not the case. So there is no bug. It was just a bad idea to make `__desc_*` attributes private variables.

**Comment by Aluriak** [comment]
For reference, the symbol is [not unaccessible](https://docs.python.org/3.3/tutorial/classes.html#tut-private). You may access it using `._Application__desc_models`. This is not an interdiction to call private members but a way to avoid the need for subclasses to know the implementation details of mother classes.

**Comment by Aluriak** [comment]
For reference, the symbol is [not unaccessible](https://docs.python.org/3.3/tutorial/classes.html#tut-private). You may access it using `._Application__desc_models`. This is not an interdiction to call private members but a way to avoid the need for subclasses to know the implementation details of mother classes.

**Comment by peschue** [comment]
Thank you!

**Comment by rkaminsk** [comment]
There is now a description method. Have a look at the example along with the commit.

**Comment by MaxOstrowski** [comment]
thx
