### ISSUE TITLE
python binding is installed into a wrong place, into the build directory

### ISSUE THREAD

**Issue by yurivict** [potassco/clingo#178]
It installs the file into ```/usr/ports/math/clingo/work/.local/lib/python3.7/site-packages/clingo.so```, when ```/usr/ports/math/clingo/work``` was the build path. So it will be installed into the build location, when the correct location is ```lib/python3.7/site-packages/clingo.so```.

**Comment by rkaminsk** [comment]
There are options to configure where the module is installed. You can set PYCLINGO_USER_INSTALL=Off to not install in the user's site directory. There are also more options. You can have a look at `app/pyclingo/CMakeLists.txt` how they are used.

**Comment by yurivict** [comment]
By default you should install tyhem into a standard directory, like all other python packages.

**Comment by rkaminsk** [comment]
By default cmake installs in `/usr/local`. Also there are a lot of users without root access. In any case it is hard to provide good defaults where to install the python module.

On another note, it looks like the cmake developers are working on improving support for building python modules. Maybe this will also lead to cmake specific options to install python modules + defaults for them, which clingo can then just use.

For now users should read the installation instructions that ship with clingo. :wink:

<https://github.com/potassco/clingo/blob/master/INSTALL.md>
