### ISSUE TITLE
Run time error when printing a model

### ISSUE THREAD

**Issue by iensen** [potassco/clingo#18]
Hello!

For some reason, the following code:

```
#include <clingo.hh>
#include <iostream>

using namespace Clingo;

Clingo::Symbol find_ex_symbol(const Control &ctl) {
    Clingo::SymbolicAtoms ats = ctl.symbolic_atoms();
    for(auto at: ats) {
        if(!strcmp(at.symbol().name(),"ex")) {
            return at.symbol();
        }
    }
    throw std::logic_error("no ex found:(");
}

int main(int argc, char const **argv) {
    try {
        Logger logger = [](WarningCode, char const *message) {
            std::cerr << message << std::endl;
        };
        Control ctl{{argv+1, size_t(argc-1)}, logger, 20};
        ctl.add("base", {}, "#external ex. a :- ex. b. ");
        ctl.ground({{"base", {}}});
        SolveIteratively solveit = ctl.solve_iteratively();
        Model m = solveit.next();
        solveit.close();
        std::cout << m << std::endl;
        Symbol ex_symb = find_ex_symbol(ctl);
        ctl.assign_external(ex_symb,TruthValue::True);
        std::cout << m << std::endl;
    }
    catch (std::exception const &e) {
        std::cerr << "example failed with: " << e.what() << std::endl;
    }
}

```
crashes when m is being printed for the second time with the following error:

`ex: /work/plog/clingo/libclasp/clasp/enumerator.h:46: Clasp::ValueRep Clasp::Model::value(Clasp::Var) const: Assertion `hasVar(v)' failed.
`

Am I am doing something wrong again?
Is there a way to keep the model intact after assigning externals/doing some other operations on the control?
Thanks!

**Comment by rkaminsk** [comment]
On Monday, December 19, 2016 12:14:46 AM CET Evgenii Balai wrote:
> SolveIteratively solveit = ctl.solve_iteratively();
> Model m = solveit.next();
> solveit.close();
> std::cout << m << std::endl;
> crashes when m is being printed
> Am I am doing something wrong again?

Hi, you must not access a model after calling close(). Note that model objects 
are only valid up until another call to next() or close(). Think of them as 
handles to the current state of the solver. After calling close, the 
assignment in the solver is reset and most variables will be unassigned. 
Hence, the error you are getting. -R

**Comment by iensen** [comment]
Roland,

Thank you for the prompt reply!!!

I see. I guess I'll just "process" the models immediately after they are computed. There is no real need for them to be available longer.
