### ISSUE TITLE
Problem while compiling c file

### ISSUE THREAD

**Issue by ChandanAVMYSURU** [potassco/clingo#180]
When I tried to compile the example file provided in potassco website for using c api, I am getting this issue. Please, can someone help?

/usr/bin/ld: /tmp/ccEooaG0.o: in function `solve':
test.c:(.text+0x79): undefined reference to `clingo_control_solve'
/usr/bin/ld: test.c:(.text+0x90): undefined reference to `clingo_solve_handle_resume'
/usr/bin/ld: test.c:(.text+0xaa): undefined reference to `clingo_solve_handle_model'
/usr/bin/ld: test.c:(.text+0xd0): undefined reference to `clingo_solve_handle_get'
/usr/bin/ld: test.c:(.text+0xf3): undefined reference to `clingo_solve_handle_close'
/usr/bin/ld: /tmp/ccEooaG0.o: in function `register_options':
test.c:(.text+0x1e5): undefined reference to `clingo_options_add'
/usr/bin/ld: /tmp/ccEooaG0.o: in function `main_loop':
test.c:(.text+0x272): undefined reference to `clingo_control_load'
/usr/bin/ld: test.c:(.text+0x2b1): undefined reference to `clingo_control_load'
/usr/bin/ld: test.c:(.text+0x2d8): undefined reference to `clingo_control_ground'
/usr/bin/ld: /tmp/ccEooaG0.o: in function `main':
test.c:(.text+0x3b3): undefined reference to `clingo_main'
collect2: error: ld returned 1 exit status

**Comment by rkaminsk** [comment]
It looks like you are not linking to the clingo library. If you have installed clingo with anaconda, adding `-lclingo` to the compiler command should be enough. Otherwise, you might need further options to specify paths (options `-L` and `-rpath`).

**Comment by ChandanAVMYSURU** [comment]
I downloaded the clingo tar file, compiled and installed it on my ubuntu system. Could you please let me know how to link library files?

**Comment by rkaminsk** [comment]
There are numerous articles about shared libraries on the internet.
- https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_C_libraries.html
- https://www.tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

If you installed in, e.g., `/usr/local`, then adding `-lclingo` to the compiler command should be enough.

**Comment by ChandanAVMYSURU** [comment]
Thanks, still I am getting the below error 

error while loading shared libraries: libclingo.so.3: cannot open shared object file: No such file or directory

**Comment by rkaminsk** [comment]
You should really read the articles I linked. Knowing how to deal with these things is basic knowledge for a C/C++ developer. Check the section about the `LD_LIBRARY_PATH` in the second article. If you do not want to set the library path all the time, you can also set the rpath when linking. Check the following article:
- https://amir.rachum.com/blog/2016/09/17/shared-libraries/#rpath-and-runpath

PS: Also, with the information you are giving me, I cannot give you concrete answers. I am just guessing what you might be doing.

**Comment by ChandanAVMYSURU** [comment]
Sorry to bother you, Thanks a lot

**Comment by rkaminsk** [comment]
I hope it helped. When you ask a question, you should provide more information. I could have helped you right away, if you I had the following information:
- the location where you installed clingo (best as a list of all the files installed)
- the *exact* compiler command
- your operating system/distribution

On another note, I would recommend you use anaconda to install clingo and gcc/clang. This makes installation very easy and you do not mess up your system by installing things in system folders. You won't have to set include and library paths. And it will also make it easier to run things on a system where you do not have root access. You don't need to use anaconda but then more background knowledge is required. In general, I would recommend to never install anything with `make install` in system directories - *always* use a package manager to install in system folders.

**Comment by rkaminsk** [comment]
I added a little tutorial how to setup a project using clingo with anaconda and cmake:
https://github.com/potassco/clingo-cmake-example
