### ISSUE TITLE
How to include clingo library in cmakeList.txt file?

### ISSUE THREAD

**Issue by chandanavgermany** [potassco/clingo#182]
I have included the clingo library directory in cmake file like link_directories(/home/vaishu/clingo/build/bin) but still I am getting the below error

vaishu@vaishu-MacBookAir:~/path_planning/build$ make
[ 50%] Linking CXX executable path_planning
/usr/bin/ld: CMakeFiles/path_planning.dir/src/main.cpp.o: in function `Clingo::Detail::handle_error(bool)':
main.cpp:(.text._ZN6Clingo6Detail12handle_errorEb[_ZN6Clingo6Detail12handle_errorEb]+0x24): undefined reference to `clingo_error_message'
/usr/bin/ld: main.cpp:(.text._ZN6Clingo6Detail12handle_errorEb[_ZN6Clingo6Detail12handle_errorEb]+0x3f): undefined reference to `clingo_error_code'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/path_planning.dir/build.make:84: path_planning] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/path_planning.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by rkaminsk** [comment]
There are many reasons why this could go wrong. You could for example attach your project sources or send a link to a git repository. Probably, then I can help you.

**Comment by chandanavgermany** [comment]
So source code is under this directory 
https://github.com/chandanavgermany/Self-driving-car
 and I have installed clingo under the directory /home/vaishu/clingo/build/bin

**Comment by rkaminsk** [comment]
You have to add clingo to the target_link_libraries.
