### ISSUE TITLE
internalized strings

### ISSUE THREAD

**Issue by sthiele** [potassco/clingo#186]
There is an [Issue](https://github.com/potassco/clingo-rs/issues/13) for clingo-rs requesting to return [`'static`](https://doc.rust-lang.org/rust-by-example/scope/lifetime/static_lifetime.html) references string slices in the rust API. 
A comment in the C API states
>  All strings returned from clingo API functions are internalized and must not be freed.

I want to be sure that this hold for all the strings i use.
I compiled the following this list of functions/members that I use to retrieve strings from the clingo C-API.
Can you confirm that these strings are only freed when the program is terminated.
```
clingo_location.begin_file
clingo_location.end_file
clingo_signature_name()
clingo_symbol_name()
clingo_symbol_string()
clingo_symbol_to_string()
clingo_configuration_value_get()
clingo_theory_atoms_term_to_string()
clingo_theory_atoms_element_to_string()
clingo_theory_atoms_atom_guard()
clingo_theory_atoms_atom_to_string()

clingo_ast_definition.name
clingo_ast_script.name
clingo_ast_program.name
clingo_ast_function.name
clingo_ast_id.id
clingo_ast_theory_function.name
clingo_ast_theory_unparsed_term_element.operators
clingo_ast_theory_guard.operator_name
clingo_ast_theory_operator_definition.name
clingo_ast_theory_term_definition.name
clingo_ast_theory_guard_definition.term
clingo_ast_theory_guard_definition.operators
clingo_ast_theory_atom_definition.name
clingo_ast_theory_atom_definition.elements
clingo_ast_theory_definition.name
```

**Comment by rkaminsk** [comment]
Internalized
===
> ```
> clingo_location.begin_file
> clingo_location.end_file
> clingo_signature_name()
> clingo_symbol_name()
> clingo_symbol_string()
> clingo_symbol_to_string()
> ```

Lifetime bound to current solve step.
===
The strings here are maintained by clasp. The theory data is invalidated when solving starts. At the same time the strings are freed.
```
clingo_theory_atoms_term_name()
```

Lifetime bound to that of AST object
===
The strings here are internalized but I would not make the assumption and rather bind the lifetime to that of the AST object.
> ```
> clingo_ast_definition.name
> clingo_ast_script.name
> clingo_ast_program.name
> clingo_ast_function.name
> clingo_ast_id.id
> clingo_ast_theory_function.name
> clingo_ast_theory_unparsed_term_element.operators
> clingo_ast_theory_guard.operator_name
> clingo_ast_theory_operator_definition.name
> clingo_ast_theory_term_definition.name
> clingo_ast_theory_guard_definition.term
> clingo_ast_theory_guard_definition.operators
> clingo_ast_theory_atom_definition.name
> clingo_ast_theory_atom_definition.elements
> clingo_ast_theory_definition.name
> ```

Invalid
===
These functions do not return strings but expect memory to write the string to.
> ```
> clingo_configuration_value_get()
> clingo_theory_atoms_term_to_string()
> clingo_theory_atoms_element_to_string()
> clingo_theory_atoms_atom_guard()
> clingo_theory_atoms_atom_to_string()
> ```

**Comment by sthiele** [comment]
I think I found 2 problems within this classification.
I think `clingo_symbol_to_string()` also writes into a preallocated string as it also gets the size.
But i don't think `clingo_theory_atoms_atom_guard()` follows that logic. I found no function to get the size of the string, and without this you can't preallocate memory.

**Comment by rkaminsk** [comment]
I will update the C-API documentation with this information.
