### ISSUE TITLE
apt package is missing Python files

### ISSUE THREAD

**Issue by felixyz** [potassco/clingo#189]
The problem is described here: https://github.com/potassco/clorm/issues/22

As @daveraja explains there:

> ...Python support has been compiled into the clingo binary itself (for example, when I run "clingo --version" it says "with Python 3.7.1"), but there is no Python module in the list of installed
files.

**Comment by rkaminsk** [comment]
This is the wrong place to report problems with distribution packages. I am not maintaining the apt packages. You could ask @tkren who is the maintainer of the debian/ubuntu packages to also include the python modules. (@tkren I am happy to assist if there are questions/problems.)

If you want to get started with clorm quickly consider installing it with anaconda: https://anaconda.org/potassco/clorm. This will install all dependencies including clingo.

**Comment by felixyz** [comment]
@rkaminsk Sorry about that. Yes I did go with anaconda in the end, but would prefer not to have to!

**Comment by tkren** [comment]
The Python module is not installed, this requires more work on the Debian package: https://salsa.debian.org/science-team/clasp (happy to receive patches!)

For now, we should fix the documentation on how to setup Python bindings, in order to address @felixyz initial report in https://github.com/potassco/clorm/issues/22
> I prefer to not use Anaconda. The installation instructions mention how to install from source, but there is no mention of how to get the Python bindings set up.

**Comment by rkaminsk** [comment]
The python bindings are automatically installed if the install target is used (and also a cmake config file). Note that by default the clasp applications are installed too. This can be disabled by setting `CLASP_BUILD_APP` to false.

It is also possible to use an already installed clingo library to build the python module. This allows for building the module for different python versions. Therefore `CLINGO_USE_LIB` has to be set to true.
