### ISSUE TITLE
Releasing externals corrupts statistics

### ISSUE THREAD

**Issue by vroland** [potassco/clingo#190]
With python, accessing the solver statistics after releasing an external seems to corrupt statistics results:
```python
import clingo
import json
ctl = clingo.Control()
ctl.add("base", [], "#external a.")
ctl.ground([("base", [])])
ctl.solve()

ctl.release_external(clingo.Function("a"))
print(json.dumps(ctl.statistics["summary"], indent=4))
```
Yields the total time as the current unix time stamp and a solve time of 0.0.
Since there is no mention in the documentation of `release_external` invalidating statistics, I guess this is a bug?

**Comment by rkaminsk** [comment]
It is more a feature. Operations like releasing externals and grounding start a new step. It is best to access statistics right after the solve call.

**Comment by vroland** [comment]
Thank you for the quick reply. Yes, when debugging I accessed it before and after releasing the external, which was confusing because of the behaviour you described. 
I think it would help if you could  add this description to the documentation of `statistics`-property, as it clarifies that it refers to the last solve call and should be checked as soon as possible.

**Comment by rkaminsk** [comment]
I'll extend the description. Reopening to keep track of this.
