### ISSUE TITLE
RedefinitionError -- is it expected?

### ISSUE THREAD

**Issue by mbalduccini** [potassco/clingo#197]
Hi,

I found that the multi-shot program below triggers a RedefinitionError during the second ground() call:
```
#program base.

#external r1.
#external r2.

s :- r1.
s :- r2.

#program prg2.
#external r3.

s :- r3.


#script (python)
import clingo
def main(prg):
    prg.ground([("base", [])])
    prg.solve()
    prg.ground([("prg2", [])])
#end.
```
Is this to be expected? If so, what are the conditions that need to be satisfied to avoid the error? I have looked through clingo's guide and the papers on multi-shot solving, but I have been able to find them.

FYI, clingo's output is:
```
clingo version 5.4.0
Reading from test-py.lp
Solving...
Answer: 1

*** ERROR: (clingo): <python>: error: error calling main function:
  Traceback (most recent call last):
    File "<test-py.lp:16:1-22:6>", line 6, in main
  RuntimeError: redefinition of atom <'s',2>

UNKNOWN

Models       : 1+
Calls        : 2
Time         : 0.008s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.008s
```

Thanks!
Marcello

**Comment by rkaminsk** [comment]
Yes, this is expected. Programs have to be compositional. You can check our paper about [multi-shot solving][multishot] for an exact definition (and further references).

[multishot]: https://www.cs.uni-potsdam.de/wv/publications/#DBLP:journals/tplp/GebserKKS19

**Comment by mbalduccini** [comment]
Thanks!
