### ISSUE TITLE
Question: Negation as failure and Grounder Python functions

### ISSUE THREAD

**Issue by peschue** [potassco/clingo#198]
In the following program I use a Python function that returns two values.
I also use that function in a negative rule body.

```
#script (python)
import clingo
F = clingo.Function

def a():
  return [clingo.Function('a'), clingo.Function('b')]
#end.

interesting1(a) :- not a = @a().
interesting1(b) :- not b = @a().
interesting2(a) :- not a = X : X = @a().
interesting2(b) :- not b = X : X = @a().
interesting3(X) :- X = @a().

aux(X) :- X = @a().
interesting4(a) :- not aux(a).
interesting4(b) :- not aux(b).
```

The answer set of the program is `aux(a) aux(b) interesting1(a) interesting1(b) interesting3(a) interesting3(b)`.

With naive usage of negation (`interesting1`) all rules are instantiated and therefore the body is true, although without negation (`interesting3`) the body is also true for both `X = a` and `X = b`.

Only the construction where I create a disjunction explicitly achieves what I would consider intuitive: the body is false, as is the case if I explicitly represent `@a() = X` in  an explicit atom.

Now my question is as follows: are Python functions always considered as "Pools" in the sense of the paper "Abstract Gringo" https://www.cs.utexas.edu/users/vl/papers/AG.pdf and therefore the rule

`interesting1(a) :- not a = @a().`

is expanded into

`interesting1(a) :- (not a = a) ; (not a = b).`

which would give the result in the answer set?

Or how can I understand what happens here that leads to both of the following to be true:

* `not a = @a()` 
* `a = @a()`

**Comment by rkaminsk** [comment]
Yes, sequences returned from external functions are handled like pools. For gringo `not a = ...` is the same as `a != ...`. Translating pools conjunctively instead of disjunctively if they occur in the scope of negation might have been a (good) option, too.

**Comment by peschue** [comment]
Thank you!

So this is not a bug. But maybe having a different default behavior might be more intuitive.
Luckily it can be emulated using the ` X : X =` notation from above.

**Comment by peschue** [comment]
I guess this can be closed, unless you plan to change the behavior.

**Comment by rkaminsk** [comment]
Simply changing this is not straightforward. The whole term handling has to be consistent. Right now we might not have the most intuitive behavior in all situations but at least things are consistent. Changing this would also require opinions/approval from the other AG authors.

**Comment by peschue** [comment]
I was not sure if this is actually described explicitly in the AG paper or if the paper leaves open this possibility. Because in the AG paper, within the scope of a negation, it is described that some disjunctions become conjunctions, so I was not sure.

But yes, if the current implementation is described in the AG paper, then changing it is not a good idea.

**Comment by rkaminsk** [comment]
AG does not describe how negation in front of comparison literals is handled. This is a gringo extension (the negation negates the comparison operation). Still this is consistent with AG. To see this, consider

    a :- not p(1..2).

which is equivalent to

    a :- not p(1).
    a :- not p(2).

Similarly, the program

    a :- not X=1..2.

 is equivalent to

    a :- not X=1.
    a :- not X=2.

If the semantics of the latter program had to be changed, so should be the semantics of the former (at least in my opinion).
