### ISSUE TITLE
Invalid JSON Output for Interrupted Solving Processes

### ISSUE THREAD

**Issue by Webastronaut** [potassco/clingo#202]
If a solving process is interrupted for some reason the corresponding JSON output (via `--outf=2`) is invalidated by the string in the first line of the output:

```json
*** Info : (clingo): INTERRUPTED by signal! // <-- this should not be part of the output
{
  "Solver": "clingo version 5.4.0",
  "Input": [
    "stdin"
  ],
  "Call": [
    {

    }
  ],
  "Result": "UNKNOWN",
  "INTERRUPTED": 1,
  "Models": {
    "Number": 0,
    "More": "yes"
  },
  "Calls": 1,
  "Time": {
    "Total": 299.951,
    "Solve": 298.155,
    "Model": 0.000,
    "Unsat": 0.000,
    "CPU": 299.616
  }
}
```

**Comment by rkaminsk** [comment]
I think there is no bug because the message should be printed to stderr and the json output to stdout. If for some reason this is not the case, then it has to be fixed.
