### ISSUE TITLE
"atom does not occur in any rule head" if negated wildcard loaded from file

### ISSUE THREAD

**Issue by keraJLi** [potassco/clingo#204]
I have the following logic program:
```prolog
a(X) :- X = 1.
b :- not a(_).
```
If i run it with clingo version 5.4.1, it correctly gives me the model `a(1).`.
However, if i use the python API to ground the logic program in the following way:
```python
import clingo
ctl = clingo.Control()
ctl.load("program.lp")
ctl.ground([("program.lp", [])])
```
...it says `info: atom does not occur in any rule head: a(#P0)`.
This does not happen if i add the program as a string via `ctl.add(...)`.
It also does not happen if i have `a(1).` instead of `a(X) :-  X = 1.` in my program.
`clingo.__version__` tells my i run clingo 5.4.1 in the python module too.
How do i fix this?

**Comment by rkaminsk** [comment]
If not specified otherwise, all statements go into the base program part. You have to call
```python
ctl.ground([("base", [])])
```

**Comment by keraJLi** [comment]
Thank you, and in general, thank you for your incredibly fast support!
