### ISSUE TITLE
Is it possible to limit the output?

### ISSUE THREAD

**Issue by OFR92** [potassco/clingo#205]
Is it possible to limit the clingo's output for a predicate so that an answer set only shows a maximum of `n` instances for that predicate?

For example, given the program (edited to add additional rule):
```
p1(a,b).
p1(c,d).
p1(b,e).
p1(c,a).
p1(a,e).

constant(a).
constant(b).
constant(c).
constant(d).
constant(e).

p2(X,Y) :- p1(Y,X),constant(X),constant(Y).
p3(X,Y,Z) :- p1(X,Z),constant(X),constant(Y).

#show p3/3.
#show p2/2.
```

Is it possible to show (any) 2 of the 5 and 25 total instances of p2 and p3, respectively?

Thanks!

**Comment by MaxOstrowski** [comment]
There are simple an complex answers to questions and it depends on what
you want to do.
Currently the question does not make much sense.
You can constrain the output to 2 predefined atoms if you like:

#show.
#show p2(a,b) : p2(a,b).
#show p2(c,q) : p2(c,q).

shows only p2(a,b) and p2(x,q) if they are true.
So which 2 do you want to show :)

You probably do not want to randomly select which predicates you show
(which is not possible and is also again just output modification).
We could guess that you actually only want to chose at most two
instances of a predicate? But this again completely changes the question.
And beware that there is a difference between atoms in a solution and
shown output. Shown output should be the least of your problems.

Best,
Max

PS: Maybe the mailing list https://potassco.org/support/ is more suited
for you question.

**Comment by rkaminsk** [comment]
You could also use the `-q` option to not print answer sets and use python code to roll you own model printing. It is also possible to print just two atoms using the show statements Max suggested. If it really is just two atoms you want to see, you can use `#min` and `#max` aggregates to show the "largest" and "smallest" atoms (or encode it using normal rules).

**Comment by OFR92** [comment]
Thank you both for the comments.

To elaborate further, I am dealing with large problems (>100k facts and >2k rules) where some rules end up with sizeable grounding. This does not scales well with the problem size in terms of memory and time. Luckily, for my use case, a maximum of 'n' number of groundings are sufficient for each rule. This would be a subset of all possible groundings, and for now could be a random set (Note: by set, I don't mean the answer set). 

Ideally, I am looking for something similar to Prolog's [findnsols](https://www.swi-prolog.org/pldoc/doc_for?object=findnsols/4) in Clingo. The idea is that this could perhaps reduce the computational requirements by limiting the grounding.

@MaxOstrowski Usually the rules are more complex than the example above and hence it isn't trivial to figure out the instances that could be used for the show command. 

@rkaminsk The only way I can think of using the `max` constraint is as following:
```
p1(a,b).
p1(c,d).
p1(b,e).
p1(c,a).
p1(a,e).

constant(a).
constant(b).
constant(c).
constant(d).
constant(e).

0{p2(X,Y)}1 :- p1(Y,X),constant(X),constant(Y).
0{p3(X,Y,Z)}1 :- p1(X,Z),constant(X),constant(Y).

% Count instances of p2 and p3:
p2count(N) :- N = #count{X,Y:p2(X,Y)}.
p3count(N) :- N = #count{X,Y,Z:p3(X,Y,Z)}.

% Constraint the maximum number of instances for each predicate:
:- 3 #max { N : p2count(N) }.
:- 3 #max { N : p3count(N) }.

% Calculate the number of total instances of p2 + p3:
pXsum(S) :- S = N1+N2,p2count(N1),p3count(N2).

% Maximise the number of total instances:
#maximize{S : pXsum(S)}.
```

However, this approach does not scales at all with the number of rules (I guess because the number of answer sets increase exponentially for different possible instances of p2 and p3 that satisfy the constraints above). In fact the 'constrained' version performs significantly worse than the original approach; my system gives up even for problems with <100 rules :(

**Comment by MaxOstrowski** [comment]
Hi,

I fear I still do not understand what you want but I guess that there
are some fundamental misunderstandings around as some things do not add up.

Am 09.04.20 um 23:00 schrieb OFR92:
>
> Thank you both for the comments.
>
> To elaborate further, I am dealing with large problems (>100k facts
> and >2k rules) where some rules end up with sizeable grounding.
>
2000+ non-ground rules ? So they are automatically generated ? If this
is the case you should look into meta programming, as this will be a
special case.
>
> This does not scales well with the problem size in terms of memory and
> time. Luckily, for my use case, a maximum of 'n' number of groundings
> are sufficient for each rule. This would be a subset of all possible
> groundings, and for now could be a random set (Note: by set, I don't
> mean the answer set).
>
This does not make sense in any possible way with ASP.
>
> Ideally, I am looking for something similar to Prolog's findnsols
> <https://www.swi-prolog.org/pldoc/doc_for?object=findnsols/4> in
> Clingo. The idea is that this could perhaps reduce the computational
> requirements by limiting the grounding.
>
Enumerating answer sets is a native feature in clingo (just add the
number "n" to your command line to enumerate n answers). I currently
fear that you encoded the enumeration of answer sets into the encoding,
which creates an exponential blowup of rules.
>
> @MaxOstrowski <https://github.com/MaxOstrowski> Usually the rules are
> more complex than the example above and hence it isn't trivial to
> figure out the instances that could be used for the show command.
>
> @rkaminsk <https://github.com/rkaminsk> The only way I can think of
> using the |max| constraint is as following:
>
> |p1(a,b). p1(c,d). p1(b,e). p1(c,a). p1(a,e). constant(a).
> constant(b). constant(c). constant(d). constant(e). 0{p2(X,Y)}1 :-
> p1(Y,X),constant(X),constant(Y). 0{p3(X,Y,Z)}1 :-
> p1(X,Z),constant(X),constant(Y). % Count instances of p2 and p3:
> p2count(N) :- N = #count{X,Y:p2(X,Y)}. p3count(N) :- N =
> #count{X,Y,Z:p3(X,Y,Z)}. % Constraint the maximum number of instances
> for each predicate: :- 3 #max { N : p2count(N) }. :- 3 #max { N :
> p3count(N) }. % Calculate the number of total instances of p2 + p3:
> pXsum(S) :- S = N1+N2,p2count(N1),p3count(N2). % Maximise the number
> of total instances: #maximize{S : pXsum(S)}. |
>
> However, this approach does not scales at all with the number of rules
> (I guess because the number of answer sets increase exponentially for
> different possible instances of p2 and p3 that satisfy the constraints
> above). In fact the 'constrained' version performs significantly worse
> than the original approach; my system gives up even for problems with
> <100 rules :(
>
Your encoding does not make much sense. Every answer set contains a set
of p2/2 and p3/3's.
Every answer set also contains exactly one p2count/1 atom (as the number
of true p2's is only one number, there cant be 5 and 7 p2's).
The maximum

|#max { N : p2count(N) } |

therefore will always be the same as the p2count/1 atom. Here you take
the maximum of one number!


The total number of instances should be maximized using

|#maximize{X,Y:p2(X,Y); |||X,Y,Z:p3(X,Y,Z)|}. |

All other rules are just output formatting and should be avoided as
there are very cost intensive.

If you want to constrain the number of p2's use:

|:- 3 #sum {1,|||X,Y:p2(X,Y)|}.|

> —
>
Hope this helps a bit,
Max

**Comment by OFR92** [comment]
Thank you very much for the pointers! I think writing a wrapper to process the clingo output of the original formulation seems like a workable solution for now.
