### ISSUE TITLE
cann't print result correctly  if lacking memory 

### ISSUE THREAD

**Issue by francisol** [potassco/clingo#208]
when I execute  the program with `--time-limit` , I find if the system cannot allocate enough memory, the program will print this message as it exit because of timeout 
```
clingo version 5.4.0
Reading from stdin
```
not like this
```
clingo version 5.4.0
Reading from stdin
Solving...
*** Info : (clingo): INTERRUPTED by signal!
UNKNOWN

TIME LIMIT   : 1
Models       : 0+
Calls        : 1
Time         : 7200.001s (Solving: 7187.62s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 6808.967s

```

**Comment by rkaminsk** [comment]
I would recommend you use some tool to set a memory limit. clingo has no inbuilt way to do this. You could either use the means provided by the OS you are using or use a tool. We often use the [runsolver] tool, here. You can configure it to send a signal once a certain memory limit is reached. There might be other/better options available.

[runsolver]: https://www.cril.univ-artois.fr/~roussel/runsolver/
