### ISSUE TITLE
How to remove added facts from clingo control in python?

### ISSUE THREAD

**Issue by chandanavgermany** [potassco/clingo#211]
Hi @rkaminsk,

I want to add specific facts to clingo control and for specific condition I need to remove some of them.  Could you please let me know how to do that?

Thanks.

**Comment by peschue** [comment]
Hi @chandanavgermany I think you want to lookinto the "assumption" argument of Control.solve()  see https://release--potassco.netlify.app/clingo/python-api/current/#clingo.Control.solve

**Comment by rkaminsk** [comment]
Or have a look at externals. There is also an [example](https://github.com/potassco/clingo/tree/master/examples/clingo/external). Both assumptions and externals are very similar. Externals keep their truth values until you change them via the API and assumptions only apply for one solve step.

**Comment by chandanavgermany** [comment]
Thanks for the help @peschue  and @rkaminsk
