### ISSUE TITLE
Getting the result of grounding in text format

### ISSUE THREAD

**Issue by ZhangShutao** [potassco/clingo#215]
I have some problem to call grounder of clingo in my cpp programs. The version of libclingo is 5.4.0. Here are some ideas I have tried:

1.  adding gringo options to clingo congtrol 
```cpp
        const char* options[] = {"--mode=gringo", "--text"};
        Control ctl{{options, 2}, logger, 20};
```
It seems the option of gringo is not acceptable for clingo control.

2.  getting grounded program with `GroundProgramObserver`
```cpp
class Observer : public GroundProgramObserver {
public:

    void rule(bool choice, AtomSpan head, LiteralSpan body) override {
        std::ostringstream builder;

        if (choice) {
            builder << join(head, ",", "{", "}");
        } else {
            builder << join(head, "|");
        }

        if (!body.empty()) {
            builder << join(body, ",", ":-");
        }
        builder << ".";

        rules.push_back(builder.str());
    }

private:
    std::vector<std::string> rules;
};
```
However, the output of this method use id of atoms and literals, which is not readable for human.

Is there some way to get the grounded program?

**Comment by rkaminsk** [comment]
You can use the `--output-debug=text` option to print rules to `stderr` but there is no interface to intercept rules in this format.

**Comment by ZhangShutao** [comment]
Is it possible to get the map from ip to symbol?

**Comment by rkaminsk** [comment]
> Is it possible to get the map from id to symbol?

Check the `output_atom` method of the [`ProgramObserver`](https://potassco.org/clingo/python-api/current/#clingo.Control.register_observer).

**Comment by ZhangShutao** [comment]
Problem solved.  Thank you so much.
