### ISSUE TITLE
Negative numbers in theory atoms

### ISSUE THREAD

**Issue by tortinator** [potassco/clingo#222]
What is the best way to deal with negative numbers in theory atoms, given that - is problematic due to being reserved for strong negation ?

**Comment by rkaminsk** [comment]
You just declare a unary minus operator and can then use it in the theory atom. For clingo, the *terms* in the theory atoms are just syntax. If you want to treat them as a number or negated atom is up to you. Systems like telingo or clingcon give meaning to the terms. You can have a look how this is done in clingcon: https://github.com/MaxOstrowski/clingo/blob/master/examples/clingo/csp/csp/parsing.py

**Comment by tortinator** [comment]
Thank you, @rkaminsk !
