### ISSUE TITLE
Adding statistics from a Propagator

### ISSUE THREAD

**Issue by keraJLi** [potassco/clingo#224]
In https://github.com/potassco/clingo/issues/72#issuecomment-387079296, it is mentioned that statistics can be added within a Propagator. However I cannot find the necessary interface for doing that. How is that possible?

**Comment by MaxOstrowski** [comment]
It depends on which level you want to do this and which language you are using.
You can have a look at https://github.com/potassco/clingoDL
In app/main.cc you find the add_stats method.
Otherwise you can look into
libclingo-dl/src/clingo-dl.cc and search for UserStatistics to see a working example.

This should be similar in python.

**Comment by keraJLi** [comment]
I am sorry, I was so focused that I forgot there is more than the python API (which I am using). I don't know any C++.
Within the python API, there is the `on_statistics` keyword to `Control.solve` which can be used to modify statistics, but I would like to know how modification is possible from within a propagator. Setting `on_statistics` to a function of the Propagator seems very hacky to me, especially because I want to "push" statistics whenever they are available, and I cannot wait for the API to offer me to update them.

**Comment by MaxOstrowski** [comment]
Why would you like to push them. Update your statistics internally whenever you like and use on_statistics to send them to the solver.
It should also get called in case of Ctrl+c etc...
Using the interface would require string and map operations which you usually want to avoid when simply updating statistics...

**Comment by rkaminsk** [comment]
Since statistics are printed after solving, the API only allows you to add statistics at the end of solving. As Max wrote, you have to gather the statistics in your own data structure and add them using the `on_statistics` callback.
