### ISSUE TITLE
Python API: RuntimeError when using number of answer sets in control object

### ISSUE THREAD

**Issue by daka05** [potassco/clingo#225]
When using the clingo library within Python and creating a control object, it is not possible to limit the number of answer sets
**bigger** than "9". If a number > "9" (e.g. "10" (two characters)) is used, a RuntimeError occurs. 

e.g.:
ctl = clingo.Control("10") 

**RuntimeError: In context '<libclingo>': multiple occurrences: 'models'**

**Comment by rkaminsk** [comment]
The constructor expects a sequence of strings. In Python a string is also a sequence of strings. You should write `Control(["10"])`.
