### ISSUE TITLE
Produces invalid JSON output

### ISSUE THREAD

**Issue by lorenzleutgeb** [potassco/clingo#232]
Hi!

The output produced by

```console
$ clingo --outf=2 examples/clingo/consequences/brave-lua.lp examples/clingo/consequences/example.lp
```

is not JSON.

I checked this by parsing it with [`jq`](https://stedolan.github.io/jq/):

```console
$ clingo --outf=2 examples/clingo/consequences/brave-lua.lp examples/clingo/consequences/example.lp | tee out.txt | jq
parse error: Invalid numeric literal at line 72, column 11
```

The output is in [`out.txt`](https://github.com/potassco/clingo/files/5050431/out.txt).

**Comment by rkaminsk** [comment]
There is a print statement in the Lua code, which breaks the JSON output. If you make the brave consequences part of the model, then you can also have them in the JSON output. Have a look at the [Model.extend] function.

[Model.extend]: https://potassco.org/clingo/python-api/current/#clingo.Model.extend
