### ISSUE TITLE
How does the test propagator work

### ISSUE THREAD

**Issue by sthiele** [potassco/clingo#233]
I was trying to replicate a test of clingos test suite for the rust API. In particular this:

https://github.com/potassco/clingo-rs/blob/8901d93dcdf9e1d7a5eee7388feb898884fa1982/tests/propagator.rs#L467-L487

tries to do the same as:
https://github.com/potassco/clingo/blob/6ebb9acddcb2b08e4c092b8ccc7c382bacb66d2b/libclingo/tests/propagator.cc#L540-L554

However, if I run my test it sometimes happens that thread 0 is started after thread 1 has already called a `notify_one()` on the CondVar (`cv`) and then thread 0 waits forever.
Maybe you see that I've done something obviously stupid? I'm not super familiar with multi threaded programming.

**Comment by rkaminsk** [comment]
The C++ implementation uses a predicate. Even if thread 1 is already finished and thread 0 has not yet started it will still work because the predicate is satisfied.

**Comment by rkaminsk** [comment]
I hope you are not stuck there. The default way to implement this is with a while loop:
```cpp
std::unique_lock<std::mutex> lock(mutex);
while (!condition) {
  cv.wait(lock);
}
```
It is too long ago that I had a look at rust but the [wait_while](https://doc.rust-lang.org/src/std/sync/condvar.rs.html#249-261) function looks like the right thing. Just with the condition inverted. It's surprising. I could once write a little rust. Now it looks like gibberish. :smile:

**Comment by sthiele** [comment]
Thanks, this helped.
