### ISSUE TITLE
Mapping from ids in reified output to predicates

### ISSUE THREAD

**Issue by susuhahnml** [potassco/clingo#234]
### What I have:

Using this theory

`:- not &tel{ >? (move(robot(1),(1,0)))}.`

I obtain in my reified output from clingo:

```
theory_string(0,"tel").

#Defines (move(robot(1),(1,0)))
theory_number(4,1).
theory_string(3,"robot").
theory_tuple(0).
theory_tuple(0,0,4).
theory_function(5,3,0).
theory_number(6,0).
theory_tuple(1).
theory_tuple(1,0,4).
theory_tuple(1,1,6).
theory_sequence(7,tuple,1).
theory_string(2,"move").
theory_tuple(2).
theory_tuple(2,0,5).
theory_tuple(2,1,7).
theory_function(8,2,2).

theory_string(1,">?").
theory_tuple(3).
theory_tuple(3,0,8).
theory_function(9,1,3).
```

I then use a predicate `in_trace_at(ID,T)` to say that the id `ID` holds in step `T`, where the id is defined by the gringo reification above. For instance `in_trace_at(8,1)` states that the predicate represented by `theory_function(8,_,_)` which is `move(robot(1),(1,0))` holds at time step 1. 

### What I want:

I want to be able to filter plans that have `move(robot(1),(1,0))` in the stable models using my predicate `in_trace_at/2`. For that I need some link between id 8 and `move(robot(1),(1,0))`.
This is defined within the linearized AST showed above. Ideally I would construct a predicate 
`id_map(ID,P)` having `id_map(8,move(robot(1),(1,0)))`. 

### What I was able to construct:

I was able to generate: `id_map(8,("move",("robot",1),(1,0))).` and then expect the user to write a rule like:

`in_trace_at(I,T) :- move(robot(N),(X,Y),T),id_map(I,("move",("robot",N),(X,Y))).`

For the generation of `id_map` I had to define a max size for the number of arguments in an ugly way:

```
id_map(ID,(P)):-
theory_string(ID,P).

id_map(ID,(P)):-
theory_number(ID,P).


% ------- Sequence

% Arity 1
id_map(ID,(MAP_0)):-
theory_sequence(ID,tuple,ID_T),
theory_tuple(ID_T,0,ID_0),
not theory_tuple(ID_T,1,_), 
id_map(ID_0,MAP_0).

% Arity 2
id_map(ID,(MAP_0,MAP_1)):-
theory_sequence(ID,tuple,ID_T),
theory_tuple(ID_T,0,ID_0),
theory_tuple(ID_T,1,ID_1),
not theory_tuple(ID_T,2,_),
id_map(ID_0,MAP_0),
id_map(ID_1,MAP_1).

% Arity 3
...
% Arity 4
...

% ------- Function

% Arity 1
id_map(ID,(P,MAP_0)):-
theory_function(ID,ID_O,ID_T),
theory_string(ID_O,P),
theory_tuple(ID_T,0,ID_0),
not theory_tuple(ID_T,1,_),
id_map(ID_0,MAP_0).

% Arity 2
id_map(ID,(P,MAP_0,MAP_1)):-
theory_function(ID,ID_O,ID_T),
theory_string(ID_O,P), 
theory_tuple(ID_T,0,ID_0),
theory_tuple(ID_T,1,ID_1),
not theory_tuple(ID_T,2,_),
id_map(ID_0,MAP_0),
id_map(ID_1,MAP_1).

% Arity 3
...
% Arity 4
...

```

Which generates:

```
id_map(0,"tel").
id_map(3,"robot").
id_map(2,"move").
id_map(1,">?").
id_map(4,1).
id_map(6,0).
id_map(5,("robot",1)).
id_map(7,(1,0)).
id_map(8,("move",("robot",1),(1,0))).
id_map(9,(">?",("move",("robot",1),(1,0)))).
id_map(10,"last").
```

### Question:

Is there a way to get this mapping using only ASP? Since the reified output is using string representations for the names of predicates I don't think there will be a way to actually get the targeted predicate: `id_map(8,move(robot(1),(1,0)))`. But perhaps there is a nicer way to generate the `id_map` that is not dependent on a explicit arity. I know I could make it look like tuples of binary tuples so that is generalized but this would come with the cost of a more tricky rule than `in_trace_at(I,T) :- move(robot(N),(X,Y),T),id_map(I,("move",("robot",N),(X,Y))).`, which might lead to errors (This one already caused some debugging). 

Any ideas? 

Perhaps having this types of mappings could be a nice feature of the reified output of gringo so that they are already available for the theory enhanced implementations.

**Comment by rkaminsk** [comment]
I think you are hitting the limits of what is possible with pure ASP + reification. I would try to make my life as simple as possible and use a little bit of Python before passing the program to the reifier. It is probably easy to generate the maps you need before passing things to the reifier.

It would of course be possible to also reify the output atoms but I think that this is such a cumbersome format that this is probably better handled by some auxiliary scripts.

**Comment by susuhahnml** [comment]
Alright. I thought it was something like this. Thank you for your help.

**Comment by rkaminsk** [comment]
I hope you can workaround the issue. Just reopen this if you have more questions regarding this issue.
