### ISSUE TITLE
Ground elem can't be applied when using python-clingo

### ISSUE THREAD

**Issue by hitoridejuyon** [potassco/clingo#235]
I need to solve a problem using python, and I tested this code. In my mind, it should get the answer `[[q(1)]]` because I add p(1,a) and p(2,b) into ground, and only q should appear because of `#show q/1`. However, I got `[[p(1,"a"), p(2,"b")]]`. It seems like the rule 'base' was not added into program.

My code is followed:

```python
def test():
    ctl = clingo.Control()
    ctl.add('fact',['index','name'],'p(index,name).')
    ctl.add('base',[],'''
q(X):-p(X,a).
#show q/1.
    ''')
    parts = []
    parts.append(('fact',[1,'a']))
    parts.append(('fact',[2,'b']))
    parts.append(('base',[]))
    ctl.ground(parts)
    models = []
    with ctl.solve(yield_=True) as handle:
        for model in handle:
            models.append(model.symbols(atoms=True))
    print(models)
```

However, when I changed rule `q(X):-p(X,a).` to `q(X):-p(X).`, `q(1)` and `q(2)` appeared. What's the different between python code and pure ASP code like followed:

```ASP
p(1,a;2,b).
q(X):-p(X,a).
#show q/1.
```

**Comment by rkaminsk** [comment]
Strings and numbers are automatically converted to the corresponding Symbol. Passing `1` is equivalent to `Number(1)` and `"a"` to `String("a")`. Since you are using `a` without quotes in the program, you have to use 
`Function("a")` because the term `a` is a zero-ary function in clingo.

```python
import clingo

ctl = clingo.Control()
ctl.add('fact', ['index', 'name'], 'p(index,name).')
ctl.add('base', [], '''
q(X):-p(X,a).
#show q/1.
''')
parts = []
parts.append(('fact', [clingo.Number(1), clingo.Function('a')]))
parts.append(('fact', [clingo.Number(2), clingo.Function('b')]))
parts.append(('base', []))
ctl.ground(parts)
models = []
with ctl.solve(yield_=True) as handle:
    for model in handle:
        models.append(model.symbols(atoms=True))
print(models)
```
