### ISSUE TITLE
Packaging clingo with pip

### ISSUE THREAD

**Issue by rkaminsk** [potassco/clingo#238]
It looks like it should be possible to build clingo using [scikit-build].

[scikit-build]: https://scikit-build.readthedocs.io/en/latest/usage.html

**Comment by joshessman-llnl** [comment]
Thanks for your work on clingo!  Any update on this capability and/or the status of the `pip` branch?

**Comment by rkaminsk** [comment]
You can already install a clingo package with pip:
```bash
python -m pip install --upgrade --extra-index-url https://test.pypi.org/simple/ clingo-cffi
```
For the command to work, you need at least Python 3.6 and a C/C++ compiler with C++14 support (e.g., gcc version 4.9 and greater). It would also be possible to provide binary packages. In the case of Linux, this means setting up something that produces [portable binary packages][3].

I completely rewrote the package using the [cffi package][1]. This has the advantage that the module will also work with other Python implementations (e.g., [pypy][2]) and also makes maintenance a lot easier. In the future, the cffi based package will probably replace the old package. For now, it is possible to choose which one to install.

The new package is not 100% compatible. First, I did not implement auto conversions from ints, tuples and strings to symbols (could be implemented). Second, the ast submodule has changed providing more functionality, and making it safer to use and more consistent. If you are not using the ast module, it is easy to write code that works with the old clingo module and the cffi based clingo package.

[1]: https://pypi.org/project/cffi/
[2]: https://www.pypy.org/
[3]: https://www.python.org/dev/peps/pep-0513/

**Comment by joshessman-llnl** [comment]
Thanks for the info - I've implemented binary packaging of clingo via Github Actions here: https://github.com/joshessman-llnl/package-clingo-manylinux

There's a few hacky patches I've added to avoid linking to `libpython.so` that may only be correct for the [manylinux](https://github.com/pypa/manylinux) images, but it does appear to produce working wheels.  I've also renamed the package in order to test the upload to testpypi.

I'd be happy to contribute this as a PR to the main clingo repository if you're interested.

**Comment by rkaminsk** [comment]
> I'd be happy to contribute this as a PR to the main clingo repository if you're interested.
Thanks for the effort. This saves me from a lot of fiddling. I am definitely interested in having this in clingo. It would be great if you could also open a PR. I checked and non of the libraries in `/usr/lib/python3/dist-packages` are linked against python. So this actually seems to be the right way to do it. It is probably a good idea to see if the same works for MacOS. Recent cmake versions provide a `Python::Module` target, which might do the trick already. Currently, I am using `Python::Python`, which is not the right thing.

**Comment by rkaminsk** [comment]
@joshessman-llnl I already opened #255 based on your work. It seems to work but there are still some things left to do.

**Comment by rkaminsk** [comment]
There are a number of pip packages available now. I'll publish them on pypi with the next release: https://test.pypi.org/user/kaminski/

**Comment by alalazo** [comment]
Any known timeframe for the next release and pip packages moving to the official PyPI repository?

**Comment by rkaminsk** [comment]
> Any known timeframe for the next release and pip packages moving to the official PyPI repository?

No, but feature-wise clingo should be ready. There are no more things I want to add. But I still want to clean up the release scripts and cmake files before a release. You could use the development version for now.
