### ISSUE TITLE
test.sh does not work with release

### ISSUE THREAD

**Issue by flip111** [potassco/clingo#24]
```
» ./test.sh
realpath: ../build/release/clingo: No such file or directory
realpath: ../build/release/python: No such file or directory
clingo/addclause
$  addclause-py.lp 0
./test.sh: line 13: addclause-py.lp: command not found
looks alright (y/n)? [y] 
```

version: https://github.com/potassco/clingo/releases/download/v5.1.0/clingo-5.1.0-linux-x86_64.tar.gz

clingo and python are in path

**Comment by rkaminsk** [comment]
The script simply executes all the examples. This is just one last sanity check before I do a release. The script is not even meant to be part of a release. -R

**Comment by flip111** [comment]
aah ok, i was trying to run the script to make sure that clingo was working correctly. You want to change anything about the script? Or close the issue? I leave it open you can decide what you want to do.

**Comment by rkaminsk** [comment]
I'll come up with a solution for the next release and then close the issue. -R
