### ISSUE TITLE
unconditional jump when using multiple propagators

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#240]
The following program produces an unconditional jump when checking with valgrind:

```cpp
#include <clingo.hh>

class DLPropagator final : public Clingo::Propagator {
public:
void init(Clingo::PropagateInit &init) override {}
void propagate(Clingo::PropagateControl &control, Clingo::LiteralSpan changes) override {}
void check(Clingo::PropagateControl &control) override {}
void undo(Clingo::PropagateControl const &control, Clingo::LiteralSpan changes) noexcept override {}
};

class Propagator final : public Clingo::Propagator {
public:
void init(Clingo::PropagateInit &init) override {
    init.add_literal();
}
void propagate(Clingo::PropagateControl &control, Clingo::LiteralSpan changes) override {}
void check(Clingo::PropagateControl &control) override {}
void undo(Clingo::PropagateControl const &control, Clingo::LiteralSpan changes) noexcept override {}
};

int main(int argc, char *argv[]) {
    DLPropagator dlp;
    Propagator p;

    Clingo::Control ctl{{"0"}};
    ctl.register_propagator(dlp);
    ctl.register_propagator(p);

    if (ctl.solve(Clingo::LiteralSpan{}, nullptr, false, false).get().is_interrupted()) {
        throw std::runtime_error("interrupted");
    }

    return 0;
}
```

The relevant part of the valgrind output is:
```
Conditional jump or move depends on uninitialised value(s)
==19880==    at 0x4A58417: Clasp::ClingoPropagator::propagateFixpoint(Clasp::Solver&, Clasp::PostPropagator*) (clingo.cpp:268)
==19880==    by 0x4AB43B2: Clasp::Solver::postPropagate(Clasp::PostPropagator*) (solver.cpp:888)
```

Compiled using:
```bash
g++ -I<clingowip>/include -L<clingowip>/lib -Wall -Wl,-rpath,<clingowip>/lib64 main.cpp -lclingo
```

**Comment by MaxOstrowski** [comment]
[main.txt](https://github.com/potassco/clingo/files/5231453/main.txt)

Even smaller version without heuristics and theory.

**Comment by MaxOstrowski** [comment]
Maybe @BenKaufmann could help here ? :pleading_face:

**Comment by rkaminsk** [comment]
@BenKaufmann we are having issues combining two propagators. One thing we stumbled upon is the above valgrind issue. This should probably be fixed before debugging the wrong answer sets further.

**Comment by BenKaufmann** [comment]
> @BenKaufmann we are having issues combining two propagators. One thing we stumbled upon is the above valgrind issue. This should probably be fixed before debugging the wrong answer sets further. Can you have a look?

While the valgrind issue could be trivially fixed, it actually points to some underlying problem (assumption violation). We are adding two propagators but only for the first one `Clasp::PostPropagator::init()` is called. Valgrind therefore later stumbles over the uninitialized `front_` member but what's more important is that we never called the `init()` function of the clingo propagator or acquired all problem variables. 

I'll try to look into this on the weekend.

**Comment by BenKaufmann** [comment]
Pushed a fix to clasp's dev branch. Note that I was wrong about the missing call to `Clingo::Propagator::init()`. This function is of course always called (by clingo) but the missing call to `Clasp::PostPropagator::init()` in clasp meant, among other things, that no watches were added for the propagator.

**Comment by rkaminsk** [comment]
Thanks, I updated the clingo wip and started building new dev packages for anaconda.

**Comment by MaxOstrowski** [comment]
You are awesome guys. Will test it next week, thanks a lot.

**Comment by MaxOstrowski** [comment]
Thanks a lot guys, you are awesome.
The error is gone and some tests do work, some others I need to fix by myself...

**Comment by rkaminsk** [comment]
Closing since there is no further feedback.
