### ISSUE TITLE
Feature Request: upper bounds

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#242]
Given a setup with 10 minimize statements on 10 different levels and multithread optimization using a mix of branch and bound and unsat core.

I would like to be able to access the proven lower and upper bounds of the different optimization levels.
Especially if a level has been proven to be optimal, i.e. "This solution is optimal w.r.t. the features x,y,z but not yet for features a,b,c".

@BenKaufmann Is this information somewhere easily available in the clasp API s.t. it can be forwared to clingo (and the clingo API)?

**Comment by rkaminsk** [comment]
There is a `ClaspFacade::Summary::lower()` and a `ClaspFacade::Summary::costs()` function. I would think that these correspond to the lower and upper bounds Max is asking for. @BenKaufmann can you explain what the `lower` function returns exactly, please? I would have to break the clingo API to provide these functions as part of clingo's solve result, which is an enumeration at the moment. As the costs are already part of the statistics, what do you think about adding a lower bound to the statistics, too?

**Comment by BenKaufmann** [comment]
@rkaminsk Whenever minimization is active and `hasLower()` returns true,  `lower(i)` returns the current lower bound of level `i`.
Whether there is a current lower bound depends on the selected minimization strategy (i.e. unsat-core or branch and bound with a step-sizes > 1) . Furthermore, while `costs` are updated on each model, `lower` is only updated on unsat. 

For an example on how `ClaspFacade::Summary::lower()` and `ClaspFacade::Summary::costs()` can be used in a summary, you can take a look at `Clasp::Cli::TextOutput::printSummary()` and `Clasp::Cli::TextOutput::printBounds()`, which is called if we have lower bounds but no optimum was found. 

Finally, adding `lower` to the statistics, while not fully trivial, would probably make sense. Should we then go for a simple array `summary.lower` that would be empty unless there is some lower bound?

**Comment by rkaminsk** [comment]
> Finally, adding `lower` to the statistics, while not fully trivial, would probably make sense. Should we then go for a simple array `summary.lower` that would be empty unless there is some lower bound?

That would be my preferred solution because we already have the optimum there. Regarding the second point, I would have thought that there is always a lower/upper bound. The trivial ones are the sums of the negative/positive weights (assuming that we compare with <=).

**Comment by MaxOstrowski** [comment]
That sounds already promising.
The usecase I was playing around was different though.
I wanted to stop search after at least x seconds and the first 3 optimas are proven.
This would require to have the lower bound accessible during search (and maybe not in the model, as the lower bound can be updated without producing a model).

But I take what I get ;-)

**Comment by rkaminsk** [comment]
> That sounds already promising.
> The usecase I was playing around was different though.
> I wanted to stop search after at least x seconds and the first 3 optimas are proven.
> This would require to have the lower bound accessible during search (and maybe not in the model, as the lower bound can be updated without producing a model).
> 
> But I take what I get ;-)

I am not quite sure what you are saying. You only want to stop if at least three levels have been shown optimal? And then, if there is still time continue refining the solution?

This usecase could be covered with the current API already by only passing the three levels of highest priority, first. And, second, adding further levels and continue search if the time budget permits. The only downside is that this requires two solve calls.

Intercepting bound updates during the search would only be possible by extending clingo's `SolveEventHandler`.

**Comment by MaxOstrowski** [comment]
Thats exactly what I wanted to do. (And afterwards inform the user which optimas have been reached und which are maybe still suboptimal).
Using the two shot approach may help, also I do not know how this will influence heuristics etc... Thanks.

**Comment by BenKaufmann** [comment]
@rkaminsk Is the statistics thing still relevant? If so, I would try to implement something similar to your preferred solution (the trivial bounds maybe INT64_MIN and INT64_MAX, though). Note that `summary.lower` and `summary.costs` would then have a slightly  different meaning than  `ClaspFacade::Summary::lower()` and `ClaspFacade::Summary::costs()`, though.

**Comment by rkaminsk** [comment]
> @rkaminsk Is the statistics thing still relevant? If so, I would try to implement something similar to your preferred solution (the trivial bounds maybe INT64_MIN and INT64_MAX, though). Note that `summary.lower` and `summary.costs` would then have a slightly different meaning than `ClaspFacade::Summary::lower()` and `ClaspFacade::Summary::costs()`, though.

I think that this is *nice to have*. It sounded like Max would not be able to use it for his use case. Only do it if you are in the mood to code. :smile:

Btw. are there already `Event`s for bound updates that could be intercepted during search?

**Comment by BenKaufmann** [comment]
> I think that this is nice to have.

I implemented something in dev (https://github.com/potassco/clasp/commit/b089aa1509511ab403c0b9abd0d13eb9e873af44)

> Btw. are there already Events for bound updates that could be intercepted during search?

Yes. The event handler that one can pass to `ClaspFacade::solve()` has a both an `onModel()` and an `onUnsat()` function. The latter is called whenever a solver's current (sub-)problem is unsat and if optimization is active, the solver also stores a copy of the current lower bound. In contrast to `onModel()`, `onUnsat()` is not a "synchronization point", though and one currently cannot use `onUnsat()` to interfere with the overall search.

**Comment by rkaminsk** [comment]
> I implemented something in dev ([potassco/clasp@b089aa1](https://github.com/potassco/clasp/commit/b089aa1509511ab403c0b9abd0d13eb9e873af44))

I updated clasp in the wip branch. I always like feature where this is all I have to do. :wink: Thanks!

> Yes. The event handler that one can pass to `ClaspFacade::solve()` has a both an `onModel()` and an `onUnsat()` function. The latter is called whenever a solver's current (sub-)problem is unsat and if optimization is active, the solver also stores a copy of the current lower bound. In contrast to `onModel()`, `onUnsat()` is not a "synchronization point", though and one currently cannot use `onUnsat()` to interfere with the overall search.

I will keep this issue open for now because I think that adding an `on_unsat` callback to clingo's SolveEventHandler is a good idea. It should also be quite straight forward. I only have to think what should be its parameter. Maybe `SolveState` or...

**Comment by rkaminsk** [comment]
@BenKaufmann what do you think about reporting the lower bound like this in an `on_unsat` callback in clingo?

```cpp
bool ClingoLib::onUnsat(Clasp::Solver const &s, Clasp::Model const &m) {
    if (m.ctx != nullptr && m.ctx->optimize() && s.lower.active()) {
        std::vector<int64_t> optimization;
        auto const *costs = m.num > 0 ? m.costs : nullptr;
        if (costs != nullptr && costs->size() > s.lower.level) {
            std::copy(costs->begin(), costs->begin() + s.lower.level, std::back_inserter(optimization));
        }
        optimization.emplace_back(s.lower.bound);
        return ClingoControl::onUnsat(Potassco::toSpan(optimization));
    }
    return true;
}
```

**Comment by BenKaufmann** [comment]
@rkaminsk Your snippet looks fine to me. I would probably replace the std::copy with a call to std::vector's range-insert, though:
`optimization.insert(optimization.end(), m.costs->begin(), m.costs.begin() + s.lower.level);`

> I noticed that it is not possible to stop the solver by returning false from onUnsat. Is this intended?

Yes. As mentioned earlier, `onUnsat()` is currently not a "synchronization point" where one can interfere with the overall search and changing this would probably require some serious effort.

**Comment by rkaminsk** [comment]
> @rkaminsk Your snippet looks fine to me. I would probably replace the std::copy with a call to std::vector's range-insert:
> `optimization.insert(optimization.end(), m.costs->begin(), m.costs.begin() + s.lower.level);`
> 
> > I noticed that it is not possible to stop the solver by returning false from onUnsat. Is this intended?
> 
> Yes. As mentioned earlier, `onUnsat()` is currently not a "synchronization point" where one can interfere with the overall search and changing this would probably require some serious effort.

Thanks. Since we have the `Control.interrupt` function, the user can still cancel the search there. (Without guarantees that further bounds/models are reported of course.)

**Comment by MaxOstrowski** [comment]
This looks awesome, thanks a lot.
