### ISSUE TITLE
Compiler error with gcc@10.2.0 and clang@10.0.1

### ISSUE THREAD

**Issue by teonnik** [potassco/clingo#244]
I got compilation errors when compiling `clingo@5.4.0` and `clingo@5.3.0` with `gcc@10.2.0` and `clang@10.0.1`:

`gcc@10.2.0`:
```
<root_dir>/libpyclingo/pyclingo.cc:1174:14: error:
          cannot convert 'std::nullptr_t' to 'Py_ssize_t' {aka 'long int'} in initialization
```

`clang@10.0.1`:
```
<root_dir>/libpyclingo/pyclingo.cc:1180:5: error
             : cannot initialize a member subobject of type 'Py_ssize_t' (aka 'long') with an rvalue of type 'nullptr_t'
```

**Comment by rkaminsk** [comment]
Have a look at #167. You can apply the patch from <https://github.com/conda-forge/clingo-feedstock/blob/master/recipe/python38.patch> to make it compile or use the latest master branch.
