### ISSUE TITLE
ModuleNotFoundError: No module named 'clingo'

### ISSUE THREAD

**Issue by hklarner** [potassco/clingo#249]
I need to install clingo for Python because another package depends on it
 * https://github.com/pauleve/mpbn#extra-requirements

I want to keep the overhead low, so if possible avoid installing a whole new package management (conda) or building the source with cmake. What options do I have to install clingo? I have tried
```
pip3 install clingo
```

**Comment by rkaminsk** [comment]
I tried to provide clingo packages via pip but did not manage to come up with satisfying solution. The easiest way is to install clingo is via conda. If you use miniconda, then the overhead is also relatively small. It is also possible to compile clingo yourself, you would have to install a cmake, a C++ compiler, and python's development packages. I strongly recommend conda to safe yourself some trouble. (Conda also integrates nicely with pip.)

**Comment by hklarner** [comment]
Steps to install that worked for me:

1. download Minicona: https://docs.conda.io/en/latest/miniconda.html#linux-installers
2. install conda: `bash Miniconda3-latest-Linux-x86_64.sh`
3. install clingo: `conda install -c potassco clingo`

**Comment by rkaminsk** [comment]
> Steps to install that worked for me:
> 
>   1. download Minicona: https://docs.conda.io/en/latest/miniconda.html#linux-installers
>   2. install conda: `bash Miniconda3-latest-Linux-x86_64.sh`
>   3. install clingo: `conda install -c potassco clingo`

Glad it worked. I would recommend to create separate environments for different projects:
```
# create an environment called potassco and install clingo from the potassco channel
conda create -n potassco -c potassco clingo
# activate the potassco environment
conda activate potassco
```
This way, you always have a clean `base` environment. Environments other than `base` can simply be deleted or recreated when needed. clingo releases are also available from the `conda-forge` channel. This channel has a huge selection of software to install available.
