### ISSUE TITLE
clingo in python, without anaconda

### ISSUE THREAD

**Issue by lucarag** [potassco/clingo#251]
I've tried installing clingo with homebrew on my macbook (still with catalina). if I try using it in the terminal it works, but when I try importing the module in python it won't. Is there some other specific procedure I should follow to make it work properly? thanks.

**Comment by rkaminsk** [comment]
I had a quick look at the formula: <https://github.com/Homebrew/homebrew-core/blob/master/Formula/clingo.rb>. It looks like it uses python 3.9. Are you using the right python executable?

**Comment by rkaminsk** [comment]
I had a closer look and it seems like the formula has to be updated. Running 

    brew reinstall --build-from-source --verbose --debug clingo

there are two problems. First, there is the message that the variable `PYTHON_EXECUTABLE` is unused. If available clingo uses cmake's `FindPython` module, which uses the variable `Python_EXECUTABLE`. The second bigger problem is the clingo module is installed in the wrong location. Here is the relevant excerpt from the log:

```
-- Install configuration: "Release"
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/lpconvert
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/clasp
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libclingo.3.0.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libclingo.3.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libclingo.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/include/clingo.hh
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/include/clingo.h
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/cmake/Clingo/ClingoTargets.cmake
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/cmake/Clingo/ClingoTargets-release.cmake
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/cmake/Clingo/ClingoConfig.cmake
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/cmake/Clingo/ClingoConfigVersion.cmake
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libpyclingo.1.0.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libpyclingo.1.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libpyclingo.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/reify
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/gringo
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/clingo
-- Installing: /private/tmp/clingo-20201127-59348-gq8suv/clingo-5.4.0/.brew_home/Library/Python/3.9/lib/python/site-packages/clingo.cpython-39-darwin.so
```
I do not know where such a module should be installed, so I cannot tell you how to fix the formula.

**Comment by rkaminsk** [comment]
Just to let you know. The homebrew formula should work now.

**Comment by lucarag** [comment]
Hi Roland,
Thank you very much. I will definitely try it asap. You were very kind.

Best wishes.

Il giorno mar 12 gen 2021 alle 19:06 Roland Kaminski <
notifications@github.com> ha scritto:
