### ISSUE TITLE
Small typos in documentation

### ISSUE THREAD

**Issue by damianoazzolini** [potassco/clingo#258]
In the pdf documentation:
- Section 11.2.3 pag 97: The input language of asprinextends (missing space between asprin and extends)
- Section 11.2.5 pag 101: The preference library of asprinimplements (missing space between asprin and implements)
However, they are not crucial...

**Comment by 0x326** [comment]
@damianoazzolini Can you move this issue to https://github.com/potassco/guide?

**Comment by 0x326** [comment]
(Moved to https://github.com/potassco/guide/issues/26)
