### ISSUE TITLE
clingo.Symbol() in python does not expose match(self, name:str, arity:int) -> bool method

### ISSUE THREAD

**Issue by glaserL** [potassco/clingo#262]
Hello everyone, 
https://potassco.org/clingo/python-api/5.4/#clingo.Symbol says that a Symbol object should have the method `match(name, arity)`, which unfortunately does not work. I have 5.3.0 installed on macOS 11.1. 

MWE:

```python
import clingo

c = clingo.Function("h", [clingo.Number(1)], True)
isinstance(c, clingo.Symbol) #true
c.match("h", 1) 
```
Produces:
```
Traceback (most recent call last):
  File "whatwhy.py", line 5, in <module>
    c.match("h", 1)
AttributeError: 'clingo.Symbol' object has no attribute 'match'
```

This is also the case for the SymbolicAtom class. SymbolicAtoms.by_signature(name, arity) works incidentally. I saw that the backend does expose this function but somehow it doesn't 'reach' python. 
https://github.com/potassco/clingo/blob/2a025667090d71b2c9dce60fe924feb6bde8f667/libpyclingo/clingo/__init__.pyi#L223-L224

I hope this helps in any way :) Best regards, Luis

**Comment by rkaminsk** [comment]
The function is available since version 5.4 but not before.

**Comment by glaserL** [comment]
Ah alright I had dependency conflicts so conda couldn't install the newest one. Thank you very much for your help and excuse the useless issue!

**Comment by rkaminsk** [comment]
No worries.
