### ISSUE TITLE
Problem (with bison) building clingo on Apple (M1) silicon

### ISSUE THREAD

**Issue by robertfeldt** [potassco/clingo#263]
Thanks for Potassco and clingo, the whole project is very impressive (and stable!) and I'm enjoying it on Linux.

However, I have troubles setting up cmake correctly for building clingo on an Apple Air with Apple M1 chip running Big Sur. Main problem seems to be to point it to the right version of bison.

I have installed needed libs/requirements using Homebrew 2.7.7 and in the recommended dir/path for Apple M1. Homebrew has partial support for Apple M1 since version 2.6.0 but all requirements that clingo needs are indicated as already supported/checked/fixed and I have added the bison bin and lib flags as recommended:

````
% brew --version
Homebrew 2.7.7
% which brew
/opt/homebrew/bin/brew
% bison --version
bison (GNU Bison) 3.7.5
...
% which bison
/opt/homebrew/opt/bison/bin/bison
% grep bison ~/.bashrc
export PATH="/opt/homebrew/opt/bison/bin:$PATH";
export LDFLAGS="-L/opt/homebrew/opt/bison/lib";
````

However, cmake for clingo still finds the default Apple bison version (which is too old for clingo) and bails out:

````
cmake -H. -B/Users/feldt/lib/clingo -DCMAKE_BUILD_TYPE=Release
-- Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
-- Could NOT find BISON: Found unsuitable version "2.3", but required is at least "2.5" (found /usr/bin/bison)
-- Potassco is not installed - using local copy
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
CMake Error at cmake/clingo_functions.cmake:21 (message):
  bison parser generator required but not found
Call Stack (most recent call first):
  libgringo/CMakeLists.txt:70 (bison_target_or_gen)
````

Any advice?

**Comment by rkaminsk** [comment]
If I remember correctly, setting the bison path via cmake option `-DCMAKE_EXECUTABLE=/opt/homebrew/opt/bison/bin/bison` should do the trick. If you build a release, then you also don't need bison because the generated parsers are bundled.

https://cmake.org/cmake/help/latest/module/FindBISON.html

**Comment by robertfeldt** [comment]
Thanks, that does seem to handle bison. I still have problems with building on the M1 Mac so if someone has pointers what they had to do please share:

````
% cmake -H. -B/Users/feldt/lib/clingo -DCMAKE_BUILD_TYPE=Release
-- Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
-- Potassco is not installed - using local copy
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/feldt/lib/clingo

% cmake --build /Users/feldt/lib/clingo
[  1%] Building CXX object clasp/libpotassco/src/CMakeFiles/libpotassco.dir/application.cpp.o
In file included from /Users/feldt/tmp/clingo/clingo/clasp/libpotassco/src/application.cpp:26:
In file included from /Users/feldt/tmp/clingo/clingo/clasp/libpotassco/potassco/application.h:26:
In file included from /Users/feldt/tmp/clingo/clingo/clasp/libpotassco/potassco/program_opts/program_options.h:28:
In file included from /Users/feldt/tmp/clingo/clingo/clasp/libpotassco/potassco/program_opts/value.h:32:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:504:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string_view:175:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__string:57:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:641:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:60:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string.h:60:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
make[2]: *** [clasp/libpotassco/src/CMakeFiles/libpotassco.dir/application.cpp.o] Error 1
make[1]: *** [clasp/libpotassco/src/CMakeFiles/libpotassco.dir/all] Error 2
make: *** [all] Error 2
````

**Comment by robertfeldt** [comment]
It seems I just had to clear the cmake caches to get past the problems above. Will report back if everything builds ok.

**Comment by robertfeldt** [comment]
It now builds ok but seems not to link correctly to Python:

````
% bin/clingo --version
dyld: Library not loaded: @rpath/Python3.framework/Versions/3.8/Python3
  Referenced from: /Users/feldt/lib/clingo/bin/clingo
  Reason: image not found
````

I will investigate more and report in this thread in the hope that it can help others. Comments/advice welcome.

**Comment by rkaminsk** [comment]
> It now builds ok but seems not to link correctly to Python:
> 
> ```
> % bin/clingo --version
> dyld: Library not loaded: @rpath/Python3.framework/Versions/3.8/Python3
>   Referenced from: /Users/feldt/lib/clingo/bin/clingo
>   Reason: image not found
> ```
> 
> I will investigate more and report in this thread in the hope that it can help others. Comments/advice welcome.

I think you are almost there. This can probably be resolved by setting the rpath properly. Unfortunately, I cannot help you with this because I do not have access to an ARM Mac. On Intel Macs it seems to build just fine.

**Comment by rkaminsk** [comment]
I might actually be able to help if you send the output of 

    cmake --build build/release --verbose

Just make sure to run

    cmake --build build/release --target clean

before.

**Comment by robertfeldt** [comment]
I did run otool on the clingo binary and can see that the Python path seems ok further down the list, i.e.:

````
% otool -l bin/clingo
bin/clingo:
...
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name @rpath/Python3.framework/Versions/3.8/Python3 (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 3.8.0
compatibility version 3.8.0
...
Load command 18
          cmd LC_RPATH
      cmdsize 112
         path /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib (offset 12)
...
```

The latter part is a valid one so maybe I need to point also the path in the "Load command 14" part to a similar, absolute path?

**Comment by robertfeldt** [comment]
Yes, this did the trick:

````
install_name_tool -change @rpath/Python3.framework/Versions/3.8/Python3 /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/libpython3.8.dylib bin/clingo
% bin/clingo --version
clingo version 5.5.0
Address model: 64-bit

libclingo version 5.5.0
Configuration: with Python 3.8.2, without Lua

libclasp version 3.3.5 (libpotassco version 1.1.0)
Configuration: WITH_THREADS=1
Copyright (C) Benjamin Kaufmann

License: The MIT License <https://opensource.org/licenses/MIT>
````

**Comment by robertfeldt** [comment]
To get a sense of the speed of clingo on Apple M1 MacBook Air with 16GB here are some runs on the solitaire example in clingo/examples/clingo/solitaire with different num threads:

````
% time clingo solitaire.lp instance.lp
Time         : 5.750s (Solving: 5.69s 1st Model: 0.79s Unsat: 4.91s)

% time clingo solitaire.lp instance.lp -t 2
Time         : 3.975s (Solving: 3.91s 1st Model: 0.21s Unsat: 3.70s)

% time clingo solitaire.lp instance.lp -t 4
Time         : 1.912s (Solving: 1.85s 1st Model: 0.13s Unsat: 1.72s)

% time clingo solitaire.lp instance.lp -t 6
Time         : 2.004s (Solving: 1.94s 1st Model: 0.49s Unsat: 1.45s)

% time clingo solitaire.lp instance.lp -t 8
Time         : 2.081s (Solving: 2.02s 1st Model: 0.37s Unsat: 1.65s)
````

**Comment by tortinator** [comment]
Hi @robertfeldt, the numbers are  are only partly comparable since each thread runs - by default - a different configuration of clasp.
Hence the more threads the more "oracles" at your disposal. It could be that the best "oracle" is already among the first four configs.

FWIW, you can configure this, first, the solver setups, and also use search space splitting - enjoy! :smile:

**Comment by robertfeldt** [comment]
Thanks for the tip @tortinator so something like:

````
% time clingo solitaire.lp instance.lp -t 2,split
Time         : 3.091s (Solving: 3.05s 1st Model: 0.37s Unsat: 2.68s)

% time clingo solitaire.lp instance.lp -t 4,split
Time         : 1.823s (Solving: 1.76s 1st Model: 0.28s Unsat: 1.48s)

time clingo solitaire.lp instance.lp -t 8,split
Time         : 1.223s (Solving: 1.15s 1st Model: 0.06s Unsat: 1.10s)
````

is more comparable then?

**Comment by rkaminsk** [comment]
I also head a look at the compiler output you send me. It looks right to me because it is linking against the Python library and sets the proper RPATH. Maybe linking the Python frameworks version requires different options. 

From the otool output, it looks like the RPATH should be set to `/Applications/Xcode.app/Contents/Developer/Library/Frameworks` instead of `/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib`. At some point the magic `@rpath` gets inserted. I do not have enough knowledge about linking on MacOS to know where this is from, though. Since I am using cmake's FindPython module, this issue might fix itself at some point with a newer cmake version.

If you use the Homebrew Python maybe it would work out of the box. If you want to give this a shot, you could try to use this version. Passing `-DPython_EXECUTABLE=<path-to-homebrew-python-executable>` should do the trick; just delete the old build or cache before.
```
CLINGO=<path-to-clingo>
XCODE=/Applications/Xcode.app/Contents/Developer
cd $CLINGO/app/clingo
$XCODE/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O3 -DNDEBUG -arch arm64 \
  -isysroot $XCODE/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk \
  -Wl,-search_paths_first -Wl,-headerpad_max_install_names \
  -L/opt/homebrew/opt/bison/lib \
  CMakeFiles/clingo.dir/main.cc.o \
  -o ../../bin/clingo  \
  -Wl,-rpath,$CLINGO/bin \
  -Wl,-rpath,$XCODE/Library/Frameworks/Python3.framework/Versions/3.8/lib \
  ../../lib/libpyclingo.a \
  ../../bin/libclingo.4.0.dylib \
  $XCODE/Library/Frameworks/Python3.framework/Versions/3.8/lib/libpython3.8.dylib
```

**Comment by tortinator** [comment]
Yes, that's one options. Another could be to fix the configuration of the solver; this could work by entering a singe one through a config portfolio file, but there may be a direct option that I had to look up myself, check out --help=3

**Comment by robertfeldt** [comment]
Thanks to you both.

Yes @rkaminsk that did the trick, I installed python3 via Homebrew and then did a fresh:

```
cmake -H. -B/Users/feldt/lib/clingo -DCMAKE_BUILD_TYPE=Release -DBISON_EXECUTABLE=/opt/homebrew/opt/bison/bin/bison -DPython_EXECUTABLE=/opt/homebrew/bin/python3
cmake --build /Users/feldt/lib/clingo
% /Users/feldt/lib/clingo/bin/clingo --version
clingo version 5.5.0
Address model: 64-bit

libclingo version 5.5.0
Configuration: with Python 3.9.1, without Lua

libclasp version 3.3.5 (libpotassco version 1.1.0)
Configuration: WITH_THREADS=1
Copyright (C) Benjamin Kaufmann

License: The MIT License <https://opensource.org/licenses/MIT>
```

Ok, I'm closing this now. All good. :)

**Comment by rkaminsk** [comment]
> Thanks to you both.
> 
> Yes @rkaminsk that did the trick, I installed python3 via Homebrew and then did a fresh:
> 
> ```
> cmake -H. -B/Users/feldt/lib/clingo -DCMAKE_BUILD_TYPE=Release -DBISON_EXECUTABLE=/opt/homebrew/opt/bison/bin/bison -DPython_EXECUTABLE=/opt/homebrew/bin/python3
> cmake --build /Users/feldt/lib/clingo
> % /Users/feldt/lib/clingo/bin/clingo --version
> clingo version 5.5.0
> Address model: 64-bit
> 
> libclingo version 5.5.0
> Configuration: with Python 3.9.1, without Lua
> 
> libclasp version 3.3.5 (libpotassco version 1.1.0)
> Configuration: WITH_THREADS=1
> Copyright (C) Benjamin Kaufmann
> 
> License: The MIT License <https://opensource.org/licenses/MIT>
> ```
> 
> Ok, I'm closing this now. All good. :)

If you are using Homebrew anyway, then you can as well take this route. There is also a clingo formula on homebrew.

**Comment by robertfeldt** [comment]
Thanks, yes, installing via the clingo formula also works but it is good to be able to build from source and get latest version. But I can confirm the clingo install via Homebrew formula works also on Apple M1. Currently at 5.4.0 with Python 3.9.1 and Lua 5.4.2.

**Comment by rkaminsk** [comment]
> Thanks, yes, installing via the clingo formula also works but it is good to be able to build from source and get latest version. But I can confirm the clingo install via Homebrew formula works also on Apple M1. Currently at 5.4.0 with Python 3.9.1 and Lua 5.4.2.

To install the latest master version with brew, you can use `brew install clingo --HEAD`. (Make sure to `brew unlink clingo` before).

**Comment by robertfeldt** [comment]
Ok, fantastic. Big thanks.
