### ISSUE TITLE
erro when running example code

### ISSUE THREAD

**Issue by marypopa** [potassco/clingo#264]
when I run this example code

`
from clyngor import ASP, solve

answers = ASP("""
rel(a,(c;d)). rel(b,(d;e)).
obj(X):- rel(X,_) ; rel(X,Y): att(Y).
att(Y):- rel(_,Y) ; rel(X,Y): obj(X).
:- not obj(X):obj(X).
:- not att(Y):att(Y).
""")
for answer in answers:
    print(answer)
`

I get this error
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by rkaminsk** [comment]
Please use the [clyngor issue tracker](https://github.com/Aluriak/clyngor/issues) for clyngor related problems.
