### ISSUE TITLE
Reification of grammar

### ISSUE THREAD

**Issue by tortinator** [potassco/clingo#267]
I would find it useful to (optionally) obtain a fact based representation of the theory grammar in mode `output=reify`

**Comment by tortinator** [comment]
After all, I was able to reconstruct most of the info I really need from the input - might be a convenience feature after all

**Comment by rkaminsk** [comment]
The reified output works on the level of the the aspif output. The theory definition itself has no representation in this format. So it does not really fit into the design to also reify it. I am also not sure we really need it. It sounds like going meta-meta.

**Comment by tortinator** [comment]
> The reified output works on the level of the the aspif output. The theory definition itself has no representation in this format. So it does not really fit into the design to also reify it. There is also no way to construct a theory definition from facts. 

I agree. I would need it to distinguish defined operators like `<*'` from domain-specific ones, like `f`.
Currently, I copy this information by hand.

The case as such is similar to the availability of obtaining the SCCs via `--reify-sccs`, it's not in aspif but it's useful.

> If there is really a reason to reify it, then it is possible to use clingo's AST API to turn it into facts. We should certainly try this route first before implementing anything in clingo.

I also agree, in case the AST let's us distinguish the former types of `theory_function`, it would be preferable.
How would you do this?

**Comment by rkaminsk** [comment]
The `--reify-sccs` option is there because computing SCCs in ASP is cumbersome and inefficient. But in my opinion reifying a theory definition would only make sense if we want to write generic ASP code that works for arbitrary theory definitions. We usually write an encoding w.r.t. to a fixed theory. So the encoding has to cover all language specific functions anyway. And thus can also contain some predicates to classify them without much extra effort.

**Comment by tortinator** [comment]
>  We usually write an encoding w.r.t. to a fixed theory. So the encoding has to cover all language specific functions anyway. 

Well spotted. Because that's changing. 

> And thus can also contain some predicates to classify them without much extra effort.

Yes, I now do copy+paste, and after all it's just prototyping and thus not urgent.  But once we have all the tel,del,mel, and combinations, copy+paste might become a source of errors.

Anyway, you mentioned that one could use the AST interface to distinguish grammer and non-grammar function symbols.
Can you elaborate?

**Comment by rkaminsk** [comment]
> > We usually write an encoding w.r.t. to a fixed theory. So the encoding has to cover all language specific functions anyway.
> 
> Well spotted. Because that's changing. Yes, I now do copy+paste, and after all it's just prototyping and thus not urgent. But once we have all the tel,del,mel, and combinations, copy+paste might become a source of errors.

Even in this example it is about fixed theories where all the theory operators are known. I feel like copy and paste errors are better caught be by something akin to unit tests. I believe there was even a project by Adam Smith, which he posted on our mailing list. 

> Anyway, you mentioned that one could use the AST interface to distinguish grammer and non-grammar function symbols.
> Can you elaborate?

Actually, we don't even need the AST for this. There is the [is_operator function](https://github.com/potassco/python-clingox/blob/6289230dd4427ff199fe6ac40f97019f02c69ab3/clingox/theory.py#L30) in the clingox library.

Also remember that I wrote the reification for theory atoms/terms without spending much thought about it. There was just an interface that had to be implemented. I would not have thought that this is actually going to be used. It would also be possible to change the reified format to distinguish theory from non-theory functions (breaking some of your encodings of course).

**Comment by tortinator** [comment]
> Even in this example it is about fixed theories where all the theory operators are known. I feel like copy and paste errors are better caught be by something akin to unit tests. I believe there was even a project by Adam Smith, which he posted on our mailing list.

Good point. Let's discuss this at our next croozee!

> > Anyway, you mentioned that one could use the AST interface to distinguish grammer and non-grammar function symbols.
> > Can you elaborate?
> 
> Actually, we don't even need the AST for this. There is the [is_operator function](https://github.com/potassco/python-clingox/blob/6289230dd4427ff199fe6ac40f97019f02c69ab3/clingox/theory.py#L30) in the clingox library.

Great!

> Also remember that I wrote the reification for theory atoms/terms without spending much thought about it. There was just an interface that had to be implemented. I would not have thought that this is actually going to be used. It would also be possible to change the reified format to distinguish theory from non-theory functions (breaking some of your encodings of course).

I believe you did a good job, Straight ideas are often the best.

**Comment by rkaminsk** [comment]
> > Also remember that I wrote the reification for theory atoms/terms without spending much thought about it. There was just an interface that had to be implemented. I would not have thought that this is actually going to be used. It would also be possible to change the reified format to distinguish theory from non-theory functions (breaking some of your encodings of course).
> 
> I believe you did a good job, Straight ideas are often the best.

Actually, I do not like that part of the reified output. The other parts in the output are designed in a way that the original program (or at least something equivalent) can be reconstructed (without the help of the API). For the theory atoms there is no way to do this (and I also do not see a nice one). This should not affect the encodings you are writing atm though.
