### ISSUE TITLE
Error: module 'clingo' has no attribute 'Control'

### ISSUE THREAD

**Issue by jpsiegel** [potassco/clingo#272]
I tried running the example for the python API and this error was raised, I have found no workaround for the problem. Any ideas would be appreciated, I must run a clingo model on production soon

**Comment by MaxOstrowski** [comment]
Which example are you referring to? Which OS do you use? Which python version? How did you install clingo? What is the command line call?

**Comment by rkaminsk** [comment]
> I tried running the example for the python API and this error was raised, I have found no workaround for the problem. Any ideas would be appreciated, I must run a clingo model on production soon

As Max said you should tell us a bit more about how you installed clingo. The kind of error you are getting can only happen if you have a module called clingo in your python path that is not our clingo module. An easy way to install clingo is to install conda and then install clingo from the potassco channel:
- <https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html>
- <https://anaconda.org/potassco/clingo>

**Comment by jpsiegel** [comment]
Im referring to the first example on this [page](https://potassco.org/clingo/python-api/current/). Im using Ubuntu 18.04, python 3.7.3, the command line call is python3 example.py (the file being a copy of the 1st example in the link). 
Many thanks for the answers! I will try reinstalling clingo with conda. I'll let you know how it goes.

**Comment by rkaminsk** [comment]
> Im referring to the first example on this [page](https://potassco.org/clingo/python-api/current/). Im using Ubuntu 18.04, python 3.7.3, the command line call is python3 example.py (the file being a copy of the 1st example in the link).
> Many thanks for the answers! I will try reinstalling clingo with conda. I'll let you know how it goes.

You still have not told us how you installed clingo. One thing I can think of is that you used pip and did not specify the `--extra-url` option. Since you are on Ubuntu you can also install via the PPA. See here: <https://potassco.org/clingo/>. If you decide to install from the PPA, make sure to run `python3 -m pip uninstall clingo` before.

**Comment by jpsiegel** [comment]
Thanks a lot! Running `python3 -m pip install --user --upgrade --extra-index-url https://test.pypi.org/simple/ clingo-cffi` did the trick.
PS.: my installation of clingo is old enough for me not to remember how it was done, it seems to have autoupdated though.
