### ISSUE TITLE
Optimization values using python API

### ISSUE THREAD

**Issue by jpsiegel** [potassco/clingo#273]
Hi again, im succesfully using the python api to run my clingo model.
I have one maximize statement and two minimize statements and my traditional clingo output looks like this after a new model is found:
`Optimization: -43 5170 4`
I can't seem to find how to retrieve those values in the python API documentation.

**Comment by rkaminsk** [comment]
Have a look here <https://www.cs.uni-potsdam.de/~kaminski/pyclingo-cffi/clingo/solving.html#clingo.solving.Model.cost> or here <https://potassco.org/clingo/python-api/current/#clingo.Model.cost>.
