### ISSUE TITLE
cant install clingo-cffi

### ISSUE THREAD

**Issue by jpsiegel** [potassco/clingo#274]
Hi, i need to install clingo again but running 
`python3 -m pip install --user --upgrade --extra-index-url https://test.pypi.org/simple/ clingo-cffi`
returns
`404 Client Error: Not Found for url: https://pypi.org/simple/clingo-cffi/`
which is weird since it worked yesterday. I checked and the url is indeed returning 404. 
Is something down?

**Comment by rkaminsk** [comment]
Everything looks at is should: <https://test.pypi.org/project/clingo-cffi/>. You must be doing something wrong.

**Comment by jpsiegel** [comment]
apparently it was only down for a few minutes, sorry to bother
