### ISSUE TITLE
*Deregister* propagator object from control object.

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#275]
Is there any way to **deregister** a propagator object from a control object? My code is like the following:
```
function(clingo_control_t* ctl) {
    clingo_propagator_t prop = { ... };
    propagator_t prop_data = { ... };
    clingo_control_register_propagator(ctl, &prop, &prop_data, true);
}
```
So, multiple propagator objects (_prop_) are registered to same control object (_ctl_) when the function is executed.

**Comment by rkaminsk** [comment]
There is no function to unregister a propagator. Also keep in mind that performance degrades with many propagators. It is better to only use a few of them.
