### ISSUE TITLE
Clingo 5.5.0 fails to import python module from the working directory

### ISSUE THREAD

**Issue by daveraja** [potassco/clingo#276]
I'm trying out the clingo 5.5.0 (installed with `conda install -c potassco/label/dev clingo`) and it fails to import a python module from the current working directory. So I guess this means that the current directory is not in the Python `sys.path`. Is this a bug or intended?

A simple example:

File `foo.lp`:

    #script(python)
    import bar
    #end.

File `bar.py`: 
    
    def foobar(): return 1

Then run:

    $ clingo foo.lp

    clingo version 5.5.0
    Reading from foo.lp
    *** ERROR: (clingo): Traceback (most recent call last):
      File "<init code for '_clingo'>", line 15, in pyclingo_execute_
      File "<string>", line 3, in <module>  
    ModuleNotFoundError: No module named 'bar'

    UNKNOWN

For comparison it work with clingo 5.4.0

    $ clingo foo.lp

    clingo version 5.4.0
    Reading from foo.lp
    Solving...
    Answer: 1

    SATISFIABLE

**Comment by daveraja** [comment]
I found a couple of references to people adding the current working directory manually.  However, the suggested approach was instead to use [PySys_SetArgvEx](https://docs.python.org/3/c-api/init.html#c.PySys_SetArgvEx). 

If it is passed `argc=0` or `argv[0]` that doesn't point to a script file then it adds the current working directory to `sys.path`.

**Comment by rkaminsk** [comment]
Since I am using cffi using, the C-API is not an option. We can simply implement something in pure Python.

**Comment by daveraja** [comment]
> Since I am using cffi using, the C-API is not an option. We can simply implement something in pure Python.

Ah ok. I haven't used cffi so didn't quite appreciate that it completely abstracts from the C-API. Although, that should have been obvious since it supports both cpython and pypy. :confused:

**Comment by rkaminsk** [comment]
This should now work now with the latest packages. Can you check, please? Simply close the issue if it is working as expected.

**Comment by daveraja** [comment]
Great. This is working now.
