### ISSUE TITLE
Clingo 5.5.0 Python not flushing stderr/stdout (for linux)

### ISSUE THREAD

**Issue by daveraja** [potassco/clingo#277]
From what I can tell clingo 5.5.0 with python print statements is not properly flushing stdout and stderr. This only becomes evident when piping and redirecting stdout/stderr. 

Here's a simple program `foo.lp`:

    #script(python)
    import sys

    def main(ctrl):
        ctrl.ground([("base",[])])
        with ctrl.solve(yield_=True) as sh:
            m = next(iter(sh))
            print("PYTHON STDOUT: {}".format(m), file=sys.stdout)
            print("PYTHON STDERR: {}".format(m), file=sys.stderr)

    #end.

    f(1..5).

I then run:

    $ clingo foo.lp > stdout.txt 2> stderr.txt

I have a number of conda environments with different combinations of python and clingo.

clingo 5.4.0 (python 3.8) does what I expect and displays the python output to stdout and stderr, as well as the usual clingo output to stdout.

But with clingo 5.5.0 I'm getting different (and wrong) behaviour for python 3.7, 3.8, and 3.9.

With python 3.7 and 3.8 it fails to show any python print output for both stdout and stderr. With python 3.9 it shows the python output for stderr but not for stdout.

If I add some flush statements at the end of the code then it behaves properly:

    sys.stderr.flush()
    sys.stdout.flush()

**Comment by rkaminsk** [comment]
It sounds a bit like the embedded interpreter is not shut down properly. I'll have a look.

**Comment by rkaminsk** [comment]
The only difference I can spot is that the cffi module never calls [`Py_Finalize`](https://docs.python.org/3/c-api/init.html#c.Py_Finalize). I suspect that the embedding feature is not very widely used. Ideally, one would report this to the cffi developers (and maybe some other issues I encountered).

**Comment by daveraja** [comment]
> The only difference I can spot is that the cffi module never calls [`Py_Finalize`](https://docs.python.org/3/c-api/init.html#c.Py_Finalize). I suspect that the embedding feature is not very widely used. Ideally, one would report this to the cffi developers (and maybe some other issues I encountered).

That makes sense since cffi is still relatively new (or at least not as widely used). Could the cffi developers' expectation be that that `Py_Finalize` must be called explicitly by the user?

**Comment by rkaminsk** [comment]
The purpose of cffi is to hide which Python version is used (CPython or PyPy). I am quite sure it is an bug in cffi.

**Comment by rkaminsk** [comment]
I reported the issue. Let's see what they say: <https://foss.heptapod.net/pypy/cffi/-/issues/495>.

**Comment by rkaminsk** [comment]
This should now work now with the latest packages. Can you check, please? Simply close the issue if it is working as expected.

**Comment by daveraja** [comment]
It is now flushing stdin/stderr, but it is flushing after clingo prints its normal output.  This results in the order of the output varying when redirecting vs not redirecting.

So with the above example (removing the printing to stderr), if I run it without any redirects it produces:

    $ clingo foo.lp 
    clingo version 5.5.0
    Reading from foo.lp
    Solving...
    Answer: 1
    f(1) f(2) f(3) f(4) f(5)
    PYTHON STDOUT: f(1) f(2) f(3) f(4) f(5)
    SATISFIABLE

    INTERRUPTED  : 1
    Models       : 1+
    Calls        : 1
    Time         : 0.091s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
    CPU Time     : 0.029s

 But when I redirect stdout:

    $ clingo foo.lp > stdout.txt ; cat stdout.txt 
    clingo version 5.5.0
    Reading from foo.lp
    Solving...
    Answer: 1
    f(1) f(2) f(3) f(4) f(5)
    SATISFIABLE

    INTERRUPTED  : 1
    Models       : 1+
    Calls        : 1
    Time         : 0.027s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
    CPU Time     : 0.027s
    PYTHON STDOUT: f(1) f(2) f(3) f(4) f(5)

**Comment by rkaminsk** [comment]
> It is now flushing stdin/stderr, but it is flushing after clingo prints its normal output. This results in the order of the output varying when redirecting vs not redirecting.

But this okay, I would say. Python's stdout and stdin have their own separate buffer. If you want to have them printed at the right place, you have to call flush yourself. The only thing I do not understand is why it is different now.

**Comment by daveraja** [comment]
That's fine with me. Just thought I should mention it :)

I have to admit that I am surprised by this behaviour I don't understand why Python is maintaining its own stdout/stderr buffers rather than using the buffering provided by libc. I always thought that this issue of buffering changing for redirects/piping was built deep into libc. Which is why it has always been tricky to interact with terminal programs by spawning and redirecting IO; which is also one of the reasons for the well known libraries like the TCL Expect and later Python PExpect.
