### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by jpsiegel** [potassco/clingo#278]
Hi
Im running a big clingo model using the pythonAPI and came across a problem:
During grounding, the following happened:
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/code/python_wrapper.py", line 51, in run_model
    clingo_control.ground([("base", [])])
RuntimeError: Clasp::Asp::PrgNode::PrgNode(Clasp::uint32, bool)@404: Value too large for defined data type: Id out of range

Any ideas what happened and how to fix this?
Using PythonAPI, Ubuntu18.04 running the model with -t 64 threads

**Comment by MaxOstrowski** [comment]
Without python code or encoding its hard to guess. Looks like you are producing too many atoms for clasp to handle.
Does this problem also occur with less threads ? (e.g. 1 or 2)
Do you have an infinite grounding, e.g. `a(X+1) :- a(X).` ?
Do you use too large numbers in your instance ?

Btw: Are you sure you want to run your program with 64 threads ? Usually the overhead is quite significant and I haven't seen a real world example that could benefit from so many threads.

**Comment by rkaminsk** [comment]
It looks like your problem is too large. You hit a hard limit regarding the number of atoms the solver can handle. The only way I see is to carefully inspect your encoding and try to reduce the size of its grounding.

**Comment by jpsiegel** [comment]
```sdasd
```

**Comment by jpsiegel** [comment]
We are trying to solve an industrial size problem with clingo and use it in production. The goal is to have a delivery planning, it's a very particular version of the multiple traveling salesman problem (MTSP). The whole model is pretty large but this is a summary that contains everything regarding the generation of atoms

```
node(0..nodes).
agent(1..agents).
depot(0).
payload(1..9). 
{ round(1..4) }.

time(X,Y,T1 + T2) :- travel_time(X,Y,T1), waiting_time(Y,T2).

%a trip means agent C in round V going from X to Y carrying U
{ trip(C,V,X,Y,U) : agent(C), node(X), payload(U) } 1 :- node(Y), not depot(Y), round(V).
%at most one trip can reach a node in each round
1 { trip(C,V,Y,Z,W) :  node(Z), payload(W) } 1 :- trip(C,V,X,Y,U), not depot(Y).
% if a node is reached, it must be abandoned in same round (except depot)

1 { trip(C,V,Y,X,U) : node(X), payload(U) } 1 :- agent(C), depot(Y), round(V).
1 { trip(C,V,X,Y,U) : node(X), payload(U) } 1 :- agent(C), depot(Y), round(V).
%every agent must leave the depot and return to it each round

1 { delivery(Y,V,W) : payload(W), W>0, W<=U, W<=Z} 1 :- trip(C,V,X,Y,U), volume_requested(Y,Z).
%if an agent reaches a node, it must deliver a valid amount of payload
```
Everything looks normal up to this point and i dont think the problem is here, the rest are optimization statements and constraints. There is only one constraint that requires more atoms to be grounded and I think here may be the problem. Its a recursive way of defining a chain of trips to avoid the generation of loops outside the depot.

```
chain(C,V,X,Y) :- trip(C,V,X,Z,U), trip(C,V,Z,Y,W).
chain(C,V,X,Y) :- trip(C,V,X,Z,U), chain(C,V,Z,Y).
chain(C,V,X,Y) :- chain(C,V,Z,Y), trip(C,V,Y,X,U).

:- node(X), not depot(X), delivery(X,V,W), round(V), 0 { chain(C,V,0,X): agent(C) } 0.
%for every node that had something delivered, the node must be connected (chained) to the depot
%avoid loops outside depot
```
Maybe this gets close to what Max pointed as "infinite grounding".
Perhaps you know of a more efficient way to avoid loops in a graph, I couldn't think of a better one!

> Do you use too large numbers in your instance ?

Currently nodes are being grounded with their ID, which is 6 digits long (e.g. node(568098) ) although no calculation is made with that number, could it be a problem for the solver?

> Are you sure you want to run your program with 64 threads?

I'm not sure. We bought a powerful computer to see if it could process this big problem, so I thought the more threads the better. Any indication of clingo options which could lead to a faster computation are appreciated, I've been struggling to find good documentation for all possible parameters to run clingo.

Sorry for the long post, I really look forward to succesfully implement this solution with clingo, but I'm going through a rough patch.
I really hope you can help me! Many thanks in advance to all the potassco team, this technology is very impressive.

**Comment by rkaminsk** [comment]
The chain rules look like they can be made more compact. Maybe something like this:
```prolog
reach(A,D,D) :- agent(A), depot(D).
reach(A,D,Y) :- reach(A,D,X), trip(A,D,X,Y,_).
```

**Comment by MaxOstrowski** [comment]
It may also make sense to remove the payload from the trip predicate,
and create an extra predicate that only combines Agent, Round, Payload.
In this way you do not create predicates for all possible payloads at 
every position, reducing complexity.
You can still ensure that all deliveries must add up to the payload or 
something.

Furthermore your graph seems to be fully connected ? You can have a trip 
from every node X to every other node Y.
You also have cubic blowup (Nodes X,Y,Z) in your second choice rule. I'm 
sure that this can be avoided.

In general I would recommend you to:
1. Look at the size complexity of your rules (3 different variables of 
nodes means cubic), try to reduce it by reformulating
2. If unsure, use the --text option to see what output is actually produced.
3. Do this for every rule to see how many atoms (roughly) this rules 
produces.

Best,
Max

PPS: If the payload domain increases, think about systems like clingcon, 
that can handle integer variables. But first you need to further 
optimize this encoding.

Am 11.03.21 um 17:39 schrieb jpsiegel:

**Comment by jpsiegel** [comment]
Brilliant suggestions, I will implement them and see how it goes. I really appreciate it, big thanks!!
Greetings from Chile

**Comment by jpsiegel** [comment]
I implemented several performance enhancements based on your suggestion. Before, only 33% of the problem could be run, now its running on 100% with no problems! Thanks a lot!
