### ISSUE TITLE
confusing result of weak constraint

### ISSUE THREAD

**Issue by wangbiu** [potassco/clingo#28]
results of programs with weak constraints confuse me, for example:  
```
a | b .
:~ a. [2@1]
:~ b. [1@1]
```
according to semantics of weak constraints, the optimal answer sets should be `{b}`, but output of clingo is 
![lwoc j 5 9 o zwg_4](https://cloud.githubusercontent.com/assets/7279980/24504204/e35d9d82-1587-11e7-8a15-e3bf344ec0be.png)

the command line I used is `clingo file`

**Comment by Aluriak** [comment]
Solutions are printed in the order they are found by the solver. Consequently, the optimal answer is the last answer, here the number 2.
The lines

    Answer: 2
    b
    Optimization: 1
    OPTIMUM FOUND

describes that the answer set number 2 contains atom `b`, reach an optimization of 1 and is an optimum.

**Comment by rkaminsk** [comment]
You might want to use option `-q1` to only print the optimal solution. Another interesting option is `--opt-mode=optN` to enumerate all optimal solutions. I am going to tag this as invalid and close the issue. -R
