### ISSUE TITLE
Logic OR in constraint

### ISSUE THREAD

**Issue by jpsiegel** [potassco/clingo#286]
Hello!
I want to write a constraint that forces a variable into a range of integers, e.g. 
` X < Y < Z`
To write a constraint, this must be negated so,
`¬( X < Y < Z ) ≡ Y < X ∨ Y > Z`

But I can't seem to find a way to write this, besides using two constraints, e.g.
```prolog
:- Y < X.
:- Y > Z.
```

In my actual case the constraint includes more terms and is cuadratic, so it would be very beneficial to only write one.

**Comment by MaxOstrowski** [comment]
Maybe you could provide a more "asp-ish" example, as of course none of 
your rules is valid ASP syntax.

Otherwise, there is no problem in using two rules.
You could also precompute the domain of Y and then use the precomputed 
domain in your constraint.

Best,
Max

**Comment by jpsiegel** [comment]
I'm sorry, here goes a more asp-ish example

Lets say I have nodes (N) which have to be visited in a certain time (T) window. So the visiting time must be between opening and closing time, e.g. `T1 < T2 < T3, opening_time(N,T1), visiting_time(N,T2), closing_time(N,T3).`
To write that idea in form of a constraint, it must be negated, so the visiting time can't occur before opening and can't occur after closing
```prolog
:- T2 < T1, T2 > T3, opening_time(N,T1), visiting_time(N,T2), closing_time(N,T3).
```
But this does not work since T2 wont ever be below T1 AND above T3 at the same time
Therefore, Im looking for some way of writing
```prolog
:- T2 < T1 OR T2 > T3, opening_time(N,T1), visiting_time(N,T2), closing_time(N,T3).
```
Since the only option I've found so far is to write two contraints, 
```prolog
:- T2 < T1, opening_time(N,T1), visiting_time(N,T2), closing_time(N,T3).
:- T2 > T3, opening_time(N,T1), visiting_time(N,T2), closing_time(N,T3).
```
which would obviously be poorly in terms of encoding performance.
I hope this clarifies the issue, thank you!

**Comment by rkaminsk** [comment]
You could write `T2 != T1..T3`.

Note that the size of the cross-products in such kind of comparisons can often be avoided using a technique called chaining.

The rule 
```
:- T2 < T1, visiting_time(N,T2), opening_time(N,T1).
```
could be written as

```
order(1,2).
order(2,3).
...
chain(N,T) :- opening_time(N,T).
chain(N,T) :- chain(N,T'), order(T,T').
:- visiting_time(N,T), order(T,T'), chain(N,T').
```

If this helps depends of course a bit on your instance, which I do not know. If there is a large number of time steps, then it probably will help.

**Comment by MaxOstrowski** [comment]
@rkaminsk is completely right and chaining is probably the most efficient way to represent your encoding.
But I want to address another misunderstanding.
1. I assume that the opening and closing times are not fixed (if they are fixed you do not need any constraint but should just restrict your choice)
2.  Your OR rule could be expressed (ab)using a sum aggregate:
`:- 1 #sum {1: T2 < T1; 1: T2 > T3}, opening_time(N,T1), visiting_time(N,T2), closing_time(N,T3).`
(meaning at least one of your conditions is true)
3. Nevertheless your 2 rules are much more efficient, as you can actually separate opening and closing time:
```
:- T2 < T1, visiting_time(N,T2), opening_time(N,T1).
:- T2 > T3, visiting_time(N,T2), closing_time(N,T3).
```
as both opening and closing time are independent from each other.
Please check the number of constraint generated using `--stats=2` and the actual constraints that are generated with `--text` of both versions. It is not about the number of non-ground rules that you use but about the number of generated constraints.
You will see that rule 2) is cubic in size while 3) is (only) quadratic*2.
Obviously, @rkaminsk version is only linear. You should check this out afterwards.

**Comment by jpsiegel** [comment]
Thanks a lot for your insights, they were very helpful!

**Comment by yangdinglou** [comment]
@rkaminsk Hi Roland, may I know where I can learn techniques like "chaining" from? I have got some hints from https://teaching.potassco.org/encoding/ but still don't think coming up with such encoding is easy without seeing this issue. (Also, having searched in many ASP books/papers without finding any "chaining") It will be good if there is something which summarizes all common optimizations of practical ASP encoding. Thanks.
