### ISSUE TITLE
C++ API with weak constaints: How to get information about the priority levels

### ISSUE THREAD

**Issue by David-Tuc** [potassco/clingo#287]
Dear all, 

I have been trying to get the weights of answer sets through the C++ API. The problem I am encountering is that the cost vector I obtain is of the size of the priority levels that appear for that specific answer set and not all the priority levels in the program. I will explain better through an example:

Considering the following program:
```
1{m(1,1);m(1,2)}1.
1{m(2,1);m(2,2)}1.

:~ m(1,1). [1@1, 1]
:~ m(2,1). [3@2, 1]
```
When we iterate the models with clingo we obtain:

> Answer: 1
> m(2,2) m(1,1)
> Optimization: 0 1
> Answer: 2
> m(2,2) m(1,2)
> Optimization: 0 0
> Answer: 3
> m(2,1) m(1,1)
> Optimization: 3 1
> Answer: 4
> m(2,1) m(1,2)
> Optimization: 3 0

When I enumerate the models through the clingo C++ API and retrieve the cost vector I have the following (format adapted to clingo's/clasp output)

> Answer: 1
> m(2,2) m(1,1)
> Optimization: 1
> Answer: 2
> m(2,2) m(1,2)
> Optimization: (empty cost vector)
> Answer: 3
> m(2,1) m(1,1)
> Optimization: 3 1
> Answer: 4
> m(2,1) m(1,2)
> Optimization: 3

Is there a way to obtain the missing zeros ? Or the priority level for each cost. 
This might be a question for CLASP, I can transfer the issue there if necessary. 

Best
David

**Comment by MaxOstrowski** [comment]
Hi,

1.
I have problems reproducing your first example output with the call `clingo example.lp`.
I do only get the first two models:
```
Answer: 1
m(2,2) m(1,1)
Optimization: 0 1
Answer: 2
m(2,2) m(1,2)
Optimization: 0 0
```
Your models 3 and 4 are less optimal (as they have a weight of 3 on priority level 2). Are you sure you get this output ? What is your exact command line call ?

2. Could you show your C++ enumeration code ?

**Comment by David-Tuc** [comment]
Hi, 

Thank you for you quick reply !

1. The command line I use is 
`clingo example.pl -n 0 --opt-mode=enum`
I am looking to obtain all the answer sets regardless of their optimality.

2. Here is the C++ code:
I have the program in a std::string variable named "program". I have defined a logger "logger" that doesn't do anything. For now this code doesn't store the cost vector, I am simply outputting it to cout (which I have deleted here for readability).
--------
```
Clingo::Control ctl({ "0", 0 }, logger, 20);
ctl.add("base", {}, program.c_str());
ctl.ground({ {"base", {}} });
// Solving
std::vector<std::vector<std::string>> answer_sets;
int i = 0;
for (auto& m : ctl.solve()) {
	int j = 0;
	std::vector<std::string> newList;
	Clingo::CostVector cost = m.cost(); // **<-- this is how I attempt to retrieve the cost**
	for (Clingo::Symbol& atom : m.symbols()) {
		newList.push_back(atom.to_string());
	}
	answer_sets.push_back(newList);
}
```

---------

If you'd like I can make a self contained c++ test file. 

Best
David

**Comment by MaxOstrowski** [comment]
I do not know if this is intended behaviour, but I suggest that it could be hard to distinguish different priority levels if the size of the vector changes from model to model.
Could you
1. make a self contained c++ test file :heart:
2. Try adding something like:
```
:~ #true. [0@1]
:~ #true. [0@2]
```
to your encoding. This usually helps keeping the priority level if it would be otherwise removed by grounding. I know that this is not the case in your example but could be worth a try.

**Comment by rkaminsk** [comment]
I did a quick test with your example and it works as expected. If in another program a priority level is omitted because it is not grounded, then you can use the zero weights as Max is suggesting above to ensure that the cost vector has the required length.

```
#include <clingo.hh>

int main() {

    std::string prg = R"(
1{m(1,1);m(1,2)}1.
1{m(2,1);m(2,2)}1.

:~ m(1,1). [1@1, 1]
:~ m(2,1). [3@2, 1])";

    Clingo::Control ctl({"0"}, nullptr, 20);
    ctl.add("base", {}, prg.c_str());
    ctl.ground({ {"base", {}} });
    // Solving
    std::vector<std::vector<std::string>> answer_sets;
    {
        auto hnd = ctl.solve();
        for (auto const& m : hnd) {
            std::vector<std::string> newList;
            Clingo::CostVector cost = m.cost(); // **<-- this is how I attempt to retrieve the cost**
            std::cerr << "cost:";
            for (auto &&x : cost) {
                std::cerr << " " << x;
            }
            std::cerr << std::endl;
            for (Clingo::Symbol& atom : m.symbols()) {
                newList.push_back(atom.to_string());
            }
            answer_sets.push_back(newList);
        }
        hnd.get();
    }
}
```
This produces the following output:
```
➜ g++ test.cc -lclingo
➜ ./a.out             
cost: 0 1
cost: 0 0
```

**Comment by David-Tuc** [comment]
Indeed that works fine ! 

My mistake is that I am in practice running programs where the weak constraints get deleted at the grounding step (I make the choice on m(1,1) or m(2,1) before hand). So there isn't any issue at all. 

I'll use Max's suggestion then and preprocess the files to add these constraints. Thank you also for the other corrections !

Thank you both for being so helpful ! 
David
