### ISSUE TITLE
Python support not available when loading from clingo module

### ISSUE THREAD

**Issue by daveraja** [potassco/clingo#291]
If you have an ASP file with an embedded python function and then load that file from a python program (using the clingo module) it raises a `RuntimeError` "error: python support not available".

Here's a simple example. Python file `foo.py`:

     from clingo import Control

     ctrl = Control()
     ctrl.load("bar.lp")

     ctrl.ground([("base",[])])
     with ctrl.solve(yield_=True) as sh:
         for m in sh: print(m)

and ASP file `bar.lp`:

     a(@func(1)).
 
     #script(python)

     def func(a): return a

     #end.

Run it from the command line:

    $ python foo.py
    Traceback (most recent call last):
      File "foo.py", line 4, in <module>
        ctrl.load("bar.lp")
      File "/home/daver/local/miniconda3/envs/tmpclingo/lib/python3.8/site-packages/clingo/control.py", line 362, in load
        _handle_error(_lib.clingo_control_load(self._rep, path.encode()))
      File "/home/daver/local/miniconda3/envs/tmpclingo/lib/python3.8/site-packages/clingo/_internal.py", line 65, in _handle_error
        raise RuntimeError(msg)
    RuntimeError: bar.lp:3:1-7:6: error: python support not available

 Note: I can still call the python function from within ASP if I remove the `script(python)` block and move the function into the python file.

**Comment by daveraja** [comment]
Just to add to the discussion... the above works in clingo 5.4. Also you could be even tricker and conditionally call an embedded `main()` function.

So file `foo.py`:

    from clingo import Control

    ctrl = Control()
    ctrl.load("bar.lp")

    if "main" in dir():
        print("Calling embedded main")
        main(ctrl)
    else:
        print("Calling default ground-solve behaviour")
        ctrl.ground([("base",[])])
        with ctrl.solve(yield_=True) as sh:
            for m in sh: print(m)

**Comment by rkaminsk** [comment]
I am not convinced that it is really important to have this feature. If we already are using Python as a host language, it is probably best to put functions in the context object passed to ground. The only useful case that I can imagine is that an encoding with embedded functions is meant to be used by clingo and in a Python program. 

I still had a look at how this could be implemented. The API already has a (hidden) [function](https://github.com/potassco/clingo/blob/wip/libclingo/clingo/script.h) to register Lua and Python scripts. One could make this a public API and allow to register (arbitrary) scripting languages.

**Comment by daveraja** [comment]
The use case for this feature is if you want to write your own clingo application wrapper; where you want to add some feature but otherwise want it to behave "normally", in terms of being able to call embedded python functions. Is there some way you could do this without this feature?

But, as you said on the discussion board, the security aspect of allowing arbitrary code to be loaded into the main module is certainly a concern. The script is loaded later so can be used to override existing functions.

Having a public API to register arbitrary scripts sounds like a nice idea.

**Comment by rkaminsk** [comment]
@daveraja if you have the time please have a look. I had to change quite some code and hopefully did not introduce bugs.
