### ISSUE TITLE
PowerPC wheels through manylinux

### ISSUE THREAD

**Issue by joshessman-llnl** [potassco/clingo#295]
Hi,

I noticed in [this comment](https://github.com/potassco/clingo/pull/255#issue-552175531) that ppc builds for releases were being considered but they do not appear to have been a part of the 5.5.0 release.  Would it be possible to enable these?  I would be happy to contribute a PR that modifies [the GH actions script](https://github.com/potassco/clingo/blob/master/.github/workflows/manylinux.yml) to only run the ppc manylinux image when the `wip` option is false.

Thanks!

**Comment by rkaminsk** [comment]
I am always a bit struggling with actions because I am not too deep into them. You don't need to open a PR but a suggestion where/how to to put the check would be nice. Meanwhile, I'll build the ppc wheels. I wouldn't have thought that anyone is using clingo on the architecture.

**Comment by rkaminsk** [comment]
Something changed and now installing the prerequisites to build clingo takes about 2 hours. It looks like it compiles cmake from source now. In total the ppc builds will most likely take more than 10 hours to build like this. We might hit limits with github's actions here...

**Comment by joshessman-llnl** [comment]
In my auxiliary repository I just remove CMake from the requirements because I know that it's available on the Manylinux images:

https://github.com/joshessman-llnl/package-clingo-manylinux/blob/c3276bba73322f710b812745db4b91c3179e6833/adjust_name.patch#L7-L8

With that change the builds take about 2.5 hours in total, which is still a long time, but infrequent enough that it's not an issue.

There may also be a way to have the build system pick up the system-installed CMake, which would be preferable.

**Comment by rkaminsk** [comment]
I think I somehow have to patch this into the build script because the deploy just failed because there is a 360 minutes limit. I want to keep the cmake dependency for the source releases though.

**Comment by rkaminsk** [comment]
The PPC wheels are online now. I had a look at how to conditionally include/exclude elements in a matrix but all the solutions I saw where quite complicated. I would take your offer of a PR. :smile:

**Comment by rkaminsk** [comment]
I als
