### ISSUE TITLE
Limit optimal models option

### ISSUE THREAD

**Issue by Markusdreyer** [potassco/clingo#299]
Hello 👋 

Is there a way to limit the number of optimal models generated? Reading through the Clingo user guide, I found this option on page 74: 

![Screen Shot 2021-04-22 at 14 45 31](https://user-images.githubusercontent.com/30928669/115716357-64a77b00-a379-11eb-8e91-b1ee9d6f61d3.png)

Generating all optimal models with `optN` is a bit excessive, is there no way to pass an argument limiting the number of models? As it stands now, it seems that you can either get a single optimal model or all optimal models?

**Comment by MaxOstrowski** [comment]
You are already on the right track. Using the mode `optN` together with -`-models=14` (or simply `14` as command line argument) will enumerate 14 optimal models.

**Comment by Markusdreyer** [comment]
Would you look at that! Thanks for a blazingly fast reply 🚀
