### ISSUE TITLE
Guided Optimization

### ISSUE THREAD

**Issue by jpsiegel** [potassco/clingo#304]
Hello!

I wanted to ask if it is possible to guide the optimizer, meaning some sort of suggestion of which values to try first.
In particular, I'm doing a distribution planification and I have the following line in my encoding:
``` prolog
1 { deliver(C,V,Y,W) : payload_amount(W), W>0, W<=max_chargeable, W<=Z } 1 :- trip(C,V,X,Y), volume_asked(Y,Z).
``` 
C being trucks, X and Y nodes to visit, V the round to visit them and Z and W volume of payload to deliver.
So the model has to choose some amount W to deliver between those values, and I have a maximization for the volume delivered. 
Although there are exceptions, I would like to guide this choice rule to start trying values close to max_chargeable, and then try lower amounts. The problem is that currently the model is often suggesting very low amounts to be delivered, which is eventually corrected, if the optimization is run long enough, but I would like to know if there's a way to indicate that it should try from the highest values first so it can reach better results sooner.

Thanks!
JPS

**Comment by rkaminsk** [comment]
You could try to use heuristic directives. Check section 10 our our guide. Otherwise, with optimization it also often helps to switch to two threads with `-t2`. The second thread uses a very different optimization scheme that sometimes works well where the standard one doesn't.

**Comment by MaxOstrowski** [comment]
Just for clarification: The option that is set in thread 2 (`-t2`) is `--opt-strategy=usc` which starts optimization from the "bottom, not the top".
Also the option `--opt-heuristic=sign` could be interesting, as it tries to start with minimal costs.

**Comment by jpsiegel** [comment]
Thank you very much, I will look into those options.
