### ISSUE TITLE
Segmentation fault with Clingo Python API 5.5.0

### ISSUE THREAD

**Issue by andrewcropper** [potassco/clingo#305]
I have a toy problem that causes a segmentation fault when I run it using the Clingo Python API. I do not see anything obviously wrong with the code. 

To be clear, I understand that the example makes little sense, I am simply playing with the API.

I am using Clingo 5.5.0 on a MacOS 11.2.3.

```
import clingo
import time

solver = clingo.Control()

solver.add('base', [], """\
        {p(1..4)}.
        {q(1..4)}.
        :- not p(_).
        :- not q(_).
        """)
solver.ground([('base', [])])

cnt = 0
while True:
    with solver.solve(yield_ = True) as handle:
        m = handle.model()
    if not m:
        break
    print(m)
    symbols = m.symbols(shown = True)
    with solver.backend() as backend:
        rule = [backend.add_atom(x) for x in symbols]
        backend.add_rule([], rule)
    cnt +=1
print(cnt)
```
On my machine, this script `apitest.py` prints:
```
p(4) q(4)
[2]    92725 segmentation fault  python3 apitest.py
```

**Comment by rkaminsk** [comment]
Module object cannot be stored for later use. They are just handles to access the current state of the solver. You can store symbols for later use though. Just changing the indention of your code will make it work correctly:
```python
    with solver.solve(yield_ = True) as handle:
        m = handle.model()
        if not m:
            break
        print(m)
        symbols = m.symbols(shown = True)
```

**Comment by andrewcropper** [comment]
Ah yes, another silly mistake on my behalf. Thank you for the explanation!
