### ISSUE TITLE
Some questions on Clingo C API 

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#308]
I am using Clingo C API for a project. It will be helpful for me to know the answers to the following questions:
- If I add a clause via [clingo_propagate_control_add_clause](https://potassco.org/clingo/c-api/5.1/group__propagator#ga45c65882cf55edcf8782f2ce13d66e2b), can I check via Clingo API whether the added clause is **conflicting** with the current assignment. Note that there was no conflict/unit propagation before adding the clause. 
Can I check it via [clingo_assignment_has_conflict](https://potassco.org/clingo/c-api/5.0/group__propagator#gab0b6ebcd6cc3bb3006ebd67b91e4d27f)? If the result of [clingo_assignment_has_conflict](https://potassco.org/clingo/c-api/5.0/group__propagator#gab0b6ebcd6cc3bb3006ebd67b91e4d27f) is **false**, then can I be sure that the added clause is a conflicting clause? 
- If I add a clause via [clingo_propagate_control_add_clause](https://potassco.org/clingo/c-api/5.1/group__propagator#ga45c65882cf55edcf8782f2ce13d66e2b), can I check via Clingo API whether the added clause is **propagating** some literal(s) w.r.t the current assignment. Note that there was no conflict/unit propagation before adding the clause.
Can I check it via [clingo_propagate_control_propagate](https://potassco.org/clingo/c-api/5.0/group__propagator#ga4b446e74624a6f2b4850155df2a3d913)? If `result` parameter of [clingo_propagate_control_propagate](https://potassco.org/clingo/c-api/5.0/group__propagator#ga4b446e74624a6f2b4850155df2a3d913) is **true**, then can I be sure that the added clause is a propagation clause?
- How I add multiple propagation clause via clingo API? Is the following `Add_Multiple_Clause()` function sufficient?
```
function Add_Clause(control, clause):
      bool result;
      // add the clause
      if (!clingo_propagate_control_add_clause(control, clause, sizeof(clause)/sizeof(*clause), clingo_clause_type_learnt, &result)) { return "NOT OK" }
      if (!result) { return "NOT OK" }
      // propagate it
      if (!clingo_propagate_control_propagate(control, &result)) { return "NOT OK" }
      if (!result) { return "OK" }
      
function Add_Multiple_Clause(control, clause_list):
      foreach clause in clause_list:
            if Add_Clause(control, clause) == "NOT OK":
                    return;  // Can't add the remaining propagation clauses
      return;  // All propagation clauses addition done
```

**Comment by rkaminsk** [comment]
> I am using Clingo C API for a project. It will be helpful for me to know the answers to the following questions:
> 
> * If I add a clause via [clingo_propagate_control_add_clause](https://potassco.org/clingo/c-api/5.1/group__propagator#ga45c65882cf55edcf8782f2ce13d66e2b), can I check via Clingo API whether the added clause is **conflicting** with the current assignment. Note that there was no conflict/unit propagation before adding the clause.
>       Can I check it via [clingo_assignment_has_conflict](https://potassco.org/clingo/c-api/5.0/group__propagator#gab0b6ebcd6cc3bb3006ebd67b91e4d27f)? If the result of [clingo_assignment_has_conflict](https://potassco.org/clingo/c-api/5.0/group__propagator#gab0b6ebcd6cc3bb3006ebd67b91e4d27f) is **false**, then can I be sure that the added clause is a conflicting clause?

The only way a clause can be conflicting right away is if all it's literals are false. You could check this yourself using the assignment.

> * If I add a clause via [clingo_propagate_control_add_clause](https://potassco.org/clingo/c-api/5.1/group__propagator#ga45c65882cf55edcf8782f2ce13d66e2b), can I check via Clingo API whether the added clause is **propagating** some literal(s) w.r.t the current assignment. Note that there was no conflict/unit propagation before adding the clause.
>       Can I check it via [clingo_propagate_control_propagate](https://potassco.org/clingo/c-api/5.0/group__propagator#ga4b446e74624a6f2b4850155df2a3d913)? If `result` parameter of [clingo_propagate_control_propagate](https://potassco.org/clingo/c-api/5.0/group__propagator#ga4b446e74624a6f2b4850155df2a3d913) is **true**, then can I be sure that the added clause is a propagation clause?

No, if the `result` parameter is `true`, literals might have been propagated or not. You only know that there was no conflict and the solver does not have to backtrack. With clingo 5.5 you can use [`clingo_assignment_trail_size`](https://potassco.org/clingo/c-api/current/group__propagator#ga75f1c5df0d7d35b4031b025c91838e72) to infer the number of currently assigned literals. If you call it before and after propagation, you should be able to infer how many literals have been propagated. The solver might already assign literals in unit resulting clauses. I am not sure. This would be different from propagation.. 

> * How I add multiple propagation clause via clingo API? Is the following `Add_Multiple_Clause()` function sufficient?

Your pseudo code does not handle errors properly. If an API function returns false, then there was an error, the system in most cases cannot recover from. The `result` parameter is another story. It just indicates that no further `add_clause`/`propagate` calls should happen. In the case that there was no error, your code looks right.

**Comment by mahi045** [comment]
> The only way a clause can be conflicting right away is if all it's literals are false. You could check this yourself using the assignment.

In the case of conflict, first I am checking whether the clause is a conflict clause or not. I have checked this as follows:

Let's say the clause = [10, -12, 15, -18]. If the sign of a literal in the clause is negative (resp. positive), then it is assigned true (resp. false) and I am checking the assigned value by [clingo_assignment_truth_value](https://potassco.org/clingo/c-api/current/group__propagator#ga0a3ce77f8fcc8b72a29a0579be5f4baa).

After adding the clause, what [clingo_assignment_has_conflict](https://potassco.org/clingo/c-api/5.0/group__propagator#gab0b6ebcd6cc3bb3006ebd67b91e4d27f) will return? Won't it return `true` (as I added a conflict clause)?

**Comment by rkaminsk** [comment]
> > The only way a clause can be conflicting right away is if all it's literals are false. You could check this yourself using the assignment.
> 
> In the case of conflict, first I am checking whether the clause is a conflict clause or not. I have checked this as follows:
> 
> Let's say the clause = [10, -12, 15, -18]. If the sign of a literal in the clause is negative (resp. positive), then it is assigned true (resp. false) and I am checking the assigned value by [clingo_assignment_truth_value](https://potassco.org/clingo/c-api/current/group__propagator#ga0a3ce77f8fcc8b72a29a0579be5f4baa).
> 
> After adding the clause, what [clingo_assignment_has_conflict](https://potassco.org/clingo/c-api/5.0/group__propagator#gab0b6ebcd6cc3bb3006ebd67b91e4d27f) will return? Won't it return `true` (as I added a conflict clause)?

To be honest I don't know. If `add_clause` returns false, then the solver has to backtrack. I don't know if this entails that `has_conflict` will return true if a conflicting clause has been added. @BenKaufmann might have an answer here. Other than this, I don't think that there is any good use for ever calling the `has_conflict` function. It is unnecessary.

**Comment by BenKaufmann** [comment]
@rkaminsk Sorry, I somehow missed the notification. 

> If add_clause returns false, then the solver has to backtrack. I don't know if this entails that has_conflict will return true if a conflicting clause has been added.

No, it does not. The return value only indicates that the solver has to backtrack before it can continue (hence, the caller must not continue adding clauses/propagation) but at this point, the clause has not yet been added (it's only added once the propagator's propagate function has returned) and so the assignment is not conflicting.
