### ISSUE TITLE
Using clingo with Node.js

### ISSUE THREAD

**Issue by henryotunuya** [potassco/clingo#310]
Greetings!
I'm new to ASP and would like to know if there is a clingo API for `Node.js`. How can I pass an ASP program from a `Node.js` app and then read its output?

**Comment by rkaminsk** [comment]
No one wrote something like the Python API for JavaScript yet. But it is possible to compile clingo to JavaScript using in a similar ways as the executable. Here are some links that might help:
- https://observablehq.com/@fil/4-color-clingo
- https://github.com/domoritz/clingo-wasm

**Comment by henryotunuya** [comment]
Okay I'll check those out
Thanks for your response.
