### ISSUE TITLE
Some questions about the example of clingo

### ISSUE THREAD

**Issue by yigong837** [potassco/clingo#311]
I see an example somewhere.The first half of the procedure is as follows:
step(0..l).
#domain step(I).
amount(0..n).
#domain amount(A).
The Ubuntu terminal will report the following error:
lexer error, unexpected #domain

There is another problem,my procedure is as follows:
set(1..4).
next(x,z) :- set(x),set(z),x<z.
But I didn't get the right answer set,terminal display:
Answer: 1
set(1) set(2) set(3) set(4)
SATISFIABLE

Models       : 1
I do not know why.
Someone please.

**Comment by MaxOstrowski** [comment]
1. #domain is not part of the gringo language, see potassco.org for modern ASP language descriptions

2. Use capitalized X,Y,Z if you mean variables.

**Comment by yigong837** [comment]
> 1. #domain is not part of the gringo language, see potassco.org for modern ASP language descriptions
> 2. Use capitalized X,Y,Z if you mean variables.

Ok,thanks.

**Comment by rkaminsk** [comment]
Your questions are very basic. Maybe you should read some introductory material about ASP. You could check out our [guide](https://github.com/potassco/guide/) or the book [Answer Set Programming (draft)](https://www.cs.utexas.edu/users/vl/teaching/378/ASP.pdf) by Vladimir Lifschitz.
