### ISSUE TITLE
Question on Clingo C API

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#316]
Is symbolic atom to solver literal mapping change over time? For example, let's say symbolic atoms are: a, b, c, and d. And the associated solver literals are: 
- Solver_literal(a) = 10.
- Solver_literal(b) = 11. 
- Solver_literal(c) = 12. 
- Solver_literal(d) = 13. 

Is there any chance that the mapping is changed (e.g. Solver_literal(d) != 13) at any certain stage of clingo solving? 
Note that we are getting the solver literal w.r.t symbolic atom using [clingo_symbolic_atoms_literal](https://potassco.org/clingo/c-api/5.1/group__symbolicatoms#gaa11e6e579cbd4c51f2551373c9700459) and [clingo_propagate_init_solver_literal](https://potassco.org/clingo/c-api/5.1/group__propagator#ga24ffe5c89ab1629271e53be60c7cff9d), as it is done in [propagator.c](https://potassco.org/clingo/c-api/5.1/propagator_8c-example.html).

**Comment by rkaminsk** [comment]
The mapping does never change.

**Comment by mahi045** [comment]
Thanks
