### ISSUE TITLE
Parsing issue in 5.5.0? Worked in 5.4.0

### ISSUE THREAD

**Issue by ssardina** [potassco/clingo#317]
I upgraded to 5.5.0 and previous files stopped working. I think it is when it contains Python code; issues with parsing?

[test_clingo.lp.txt](https://github.com/potassco/clingo/files/6676127/test_clingo.lp.txt)

In 5.4.0:

```
$ clingo test_clingo.lp
clingo version 5.4.0
Reading from test_clingo.lp
Solving...
(1,"Hi") (2,"Hi") (3,"Hi") (4,"Hi") (5,"Hi") (6,"Hi") (7,"Hi") (8,"Hi") (9,"Hi") (10,"Hi") (1,"Bye") (2,"Bye") (3,"Bye") (4,"Bye") (5,"Bye") (6,"Bye") (7,"Bye") (8,"Bye") (9,"Bye") (10,"Bye")
Answer: 1
(1,"Hi") (2,"Hi") (3,"Hi") (4,"Hi") (5,"Hi") (6,"Hi") (7,"Hi") (8,"Hi") (9,"Hi") (10,"Hi") (1,"Bye") (2,"Bye") (3,"Bye") (4,"Bye") (5,"Bye") (6,"Bye") (7,"Bye") (8,"Bye") (9,"Bye") (10,"Bye")
SATISFIABLE

Models       : 1
Calls        : 1
Time         : 0.129s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.124s
```

In 5.5.0 (Ubuntu, all new packages installed)

```shell
$ clingo test_clingo.lp
clingo version 5.5.0 (e1c2013)
Reading from test_clingo.lp
*** ERROR: (clingo): Traceback (most recent call last):
  File "/home/ssardina/.local/lib/python3.8/site-packages/clingo/script.py", line 184, in _pyclingo_execute
    return _pyclingo_script_execute(_ffi.cast('clingo_location_t*', location),
  File "/home/ssardina/.local/lib/python3.8/site-packages/clingo/script.py", line 147, in _pyclingo_script_execute
    script.execute(_py_location(location), _ffi.string(code).decode())
  File "/home/ssardina/.local/lib/python3.8/site-packages/clingo/script.py", line 128, in execute
    exec(code, __main__.__dict__, __main__.__dict__) # pylint: disable=exec-used
  File "<string>", line 1
    .
    ^
SyntaxError: invalid syntax

UNKNOWN

Models       : 0+
Calls        : 1
Time         : 0.131s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.131s
```

Am I missing something here? Thanks!

**Comment by rkaminsk** [comment]
You have to remove the `.` after the `#script(python)`. In clingo 5.4 everything on the same line as the #script directive was ignored. A period was never required.

**Comment by ssardina** [comment]
:clap: Fantastic, thanks! 

Sorry these issue seem to be silly and not bug related, I was unsure to open an issue. Where should I ask these questions? In the forum?

**Comment by ssardina** [comment]
Actually, seems the other problem is related to this one... all good (so far). Thanks again @rkaminsk !

**Comment by rkaminsk** [comment]
> Sorry these issue seem to be silly and not bug related, I was unsure to open an issue. Where should I ask these questions? In the forum?

No worries. You can use the issues or our mailing list. Whichever you like better. More general questions are probably better asked on the mailing list because there are more people who might respond.

> I ask because I have encounter other issues when moving to 5.5.0..

There are some small incompatibilities. For example, there are no auto conversions to symbols anymore. There was also a thread on our [mailing list](https://sourceforge.net/p/potassco/mailman/potassco-users/thread/6a80b013a5b2f29b1f558d26a7edbc519f6237f8.camel%40cs.uni-potsdam.de/).

**Comment by ssardina** [comment]
> There are some small incompatibilities. For example, there are no auto conversions to symbols anymore. There was also a thread on our [mailing list](https://sourceforge.net/p/potassco/mailman/potassco-users/thread/6a80b013a5b2f29b1f558d26a7edbc519f6237f8.camel%40cs.uni-potsdam.de/).

Exactly!! I should have checked the mailing list... I found that by debugging the code and now I am adding all the `clingo.Number` and similar to my code :-) Great you confirmed that, you read my mind... ;-)
