### ISSUE TITLE
Unclear Performance Issue with Multiple Minimization Criteria

### ISSUE THREAD

**Issue by greg-gelfond** [potassco/clingo#318]
Consider the following path finding problem (which may be seen as a variant of the _Traveling Salesman_):

Let G be a graph (possibly complete) whose nodes are divided into clusters. Let us suppose that we specify a point of origin and a subset of the nodes that must be visited. Let us also suppose that we may have a preference relation which defines a partial order on the desired nodes. The goal is to both _**find and enumerate the edges**_  of a cycle which begins and ends at the point of origin such that:

1. The number of nodes visited/reached is minimized; and
2. The following violations of preferences are minimized:
    * we ought to attempt to not exceed one entry into a cluster of nodes;
    * we ought to respect the user's prefered visitation order.

Below is my current encoding (in the dialect of `clingo`):
   
```
% clingo command invocation:
%     clingo --models=0 --opt-mode=optN --quiet=1,1,2 path-enumeration.lp

#show path/3.

% Graph Definition

%% Nodes [a-p]

node(a).
node(b).
node(c).
node(d).

node(e).
node(f).
node(g).
node(h).

node(i).
node(j).
node(k).
node(l).

node(m).
node(n).
node(o).
node(p).

%% Nodes are subdivided into clusters:

cluster(1;2;3;4).

in_cluster(a,1; b,1; c,1; d,1).
in_cluster(e,2; f,2; g,2; h,2).
in_cluster(i,3; j,3; k,3; l,3).
in_cluster(m,4; n,4; o,4; p,4).

%% Define the graph as a complete graph.

edge(N1,N2) :- node(N1), node(N2), N1 != N2.

% Path Specification

%% The path must originate at node 'a' and visit all of the nodes
%% in the set {a,b,d,e}.

origin(a).

required(b).
required(d).
required(e).

required(N) :- origin(N).

prefered_order(b,e).
prefered_order(e,d).

% Path Generation

%% Choose an arbitrary subset of the edges within the graph.

{ selected_edge(N1,N2) : edge(N1,N2) }.

%% Constrain the selection in such a way as to ensure that every required
%% node is reached.

reached(N2) :- selected_edge(N1,N2), origin(N1).

reached(N2) :- selected_edge(N1,N2), reached(N1).

:- required(N), not reached(N).

:- selected_edge(N,N1), selected_edge(N,N2), N1 != N2.
:- selected_edge(N1,N), selected_edge(N2,N), N1 != N2.

%% Extra nodes are those nodes which are reached, but not specified as
%% required.

extra_node(N) :- reached(N), not required(N).

#minimize{ 1@3,N : extra_node(N) }.

% Path Enumeration

%% Determine the valid indices.

%%% Note: doing this dynamically via an aggregate instead of having a declared
%%% constant (given either directly in the program or as an argument to the
%%% solver) causes a performance penalty.

size(N) :- #count{ (N1,N2) : selected_edge(N1,N2) } = N.

index(0..N-1) :- size(N).

max_index(N-1) :- size(N).

%% Establish a one-to-one correspondence between selected edges and index
%% positions.

1 { path(Src,Dst,N) : selected_edge(Src,Dst) } 1 :- index(N).
1 { path(Src,Dst,N) : index(N) } 1 :- selected_edge(Src,Dst).

%% Ensure that the first edge of the path is the one which starts at the
%% origin.

path(Src,Dst,0) :-
    selected_edge(Src,Dst), origin(Src).

%% Ensure that the final edge of the path is the one which ends at the
%% origin.

path(Src,Dst,N) :-
    max_index(N),
    selected_edge(Src,Dst), origin(Dst).

%% Ensure that the edges are ordered in accordance with their connections (with
%% the exception of the origin).

:- selected_edge(Src,Dst1), path(Src,Dst1,N),
   selected_edge(Dst1,Dst2), not path(Dst1,Dst2,N+1),
   index(N), index(N+1).

% Path Criteria

#minimize{ 1@2,V : rule_violation(V) }.

%% Rule 1 - A path may not cross into a cluster multiple times.

rule_violation(r1) :-
    cluster(C), entry_points(C,N), N >= 2.

entry_points(C,N) :-
    cluster(C),
    N = #count{(Src,Dst) : enters_cluster(Src,Dst,C)}.

enters_cluster(Src,Dst,C2) :-
    selected_edge(Src,Dst),
    in_cluster(Src,C1),
    in_cluster(Dst,C2),
    C1 != C2.

%% Rule 2 - A path ought to preserve the prefered ordering.

rule_violation(r2) :-
    path(Src1,Dst1,M), path(Src2,Dst2,N),
    prefered_order(Dst1,Dst2), M > N.
```

Running `clingo` as follows:

```
clingo --models=0 --opt-mode=optN --quiet=1,1,2 path-enumeration.lp
```

gives the following:

```
(base) C:\Users\GregGelfond\Projects\asp-playground>clingo --models=0 --opt-mode=optN --quiet=1,1,2 path-enumeration-tiered.lp
clingo version 5.5.0
Reading from path-enumeration-tiered.lp
Solving...
Answer: 1
path(a,b,0) path(d,a,3) path(b,e,1) path(e,d,2)
Optimization: 0 0
OPTIMUM FOUND

Models         : 9
  Optimum    : yes
Optimization : 0 0
Calls              : 1
Time             : 246.009s (Solving: 212.58s 1st Model: 0.79s Unsat: 0.00s)
CPU Time     : 245.969s
```

I'm not sure what accounts for the long time to find an optimal solution.

1. Modifying the program to (1) force each node to be required; and (2) hard-coding the maximum index position via a constant results in almost instant results.
2. Finding an optimal solution in terms of solely minimizing extra nodes is also fairly quick (takes about 3 seconds to find optimal solutions). This is fast even if an aggregate is used to determine the possible set of indices used for enumeration.
3. The big drop in performance happens on the inclusion of all of the rules in the `% Path Criteria` section.

The only current hypothesis that I have is that the optimization constraints depend on not just each other but also the evaluation of the aggregate. Any suggestions on how to improve the performance of the encoding would be appreciated (for all I know I may be using the `#minimize` directives in an non-optimal way).

**Comment by MaxOstrowski** [comment]
I'm not sure if I did everything correct, but your path computation is very costly. You do not have to guess the indices, you can simply generate them from the selected edges.
What about:
```
path(Src,Dst,0) :-
    selected_edge(Src,Dst), origin(Src).

size(N+1) :- #count{ 1,N1 : node(N1) } = N.
path(Dst1,Dst2,N+1) :- path(_,Dst1,N), selected_edge(Dst1,Dst2), size(S), N<S.
```

This produces too much `path` predicates as it loops round and round, so you may have to adopt your `rule_violation`.

**Comment by MaxOstrowski** [comment]
Furthermore, rule 2 can be drastically simplified:
```
rule_violation(r2) :-
    path(_,Dst1,M), path(_,Dst2,N),
    prefered_order(Dst1,Dst2), M > N.
```
Furthermore, instead of using `M > N`, chaining could be used to avoid the quadratic blowup.

**Comment by rkaminsk** [comment]
In your setting I would generate the path differently. The following example is meant as an idea to start with. It has to be further refined to your needs:

```prolog
nodes(N) :- N = { node(U) }.

% path length

{ index(1) } :- 1 <= N, nodes(N).
{ index(I+1) } :- index(I), I < N, nodes(N).

% path

1 { selected(I,U) : node(U) } 1 :- index(I).

% example chain

after(I-1,U) :- selected(I,U), I > 1.
after(I-1,U) :- after(I,U), I > 1.

rule_violation(r2) :-
    prefered_order(U,V),
    selected(I,V), after(I,U).
```

And then go as Max is suggesting replacing `!=` by aggregates if possible and replace `<`, `>`, `>=`, or `<=` comparisons by chains as indicated in the above example.

When encoding, always try to keep the grounding as small as possible.

**Comment by mbalduccini** [comment]
Very interesting suggestions, @MaxOstrowski and @rkaminsk. Can you elaborate on what "chaining" means in the context of the comment below?

```
rule_violation(r2) :-
    path(_,Dst1,M), path(_,Dst2,N),
    prefered_order(Dst1,Dst2), M > N.
```
> Furthermore, instead of using M > N, chaining could be used to avoid the quadratic blowup.

**Comment by rkaminsk** [comment]
Let `n` be the number of nodes and `m` be the number of predicates over `rule_violation`. My encoding has size `O(n*n+m)`. With the unchained rule below it is `O(n*n*m)`. So especially if `m` is large, the grounding will be smaller. (Also note that the grounding can be tuned further by only considering nodes in `prefered_order` in the rules defining `after`.)

This "chaining" can be used in a lot of encodings. There is also the chance that atoms over `after` can be used in multiple places. Generally, the solver also handles such rules well.

Just add the following to the program and have a look at the output with `--text`.

```prolog
node(1..10).

prefered_order(1,2).

rule_violation_unchained(r2) :-
    prefered_order(U,V),
    selected(I,V), selected(J,U), J > I.
```

**Comment by greg-gelfond** [comment]
Hi Roland,

Can you explain a bit more about the use of anonymous variables impacts the grounder and performance? I don’t have a clear intuition of the “why”. 

-- 
  Gregory Gelfond
  ***@***.***

**Comment by MaxOstrowski** [comment]
```
rule_violation(r2) :-
    path(_,Dst1,M), path(_,Dst2,N),
    prefered_order(Dst1,Dst2), M > N.
```

using `path(_,Dst1,M)` is equivalent to creating a new predicate:
```
path_projected(Dst,M) :- path(Src,Dst,M).
```
and writing
```
rule_violation(r2) :-
    path_projected(Dst1,M), path_projected(Dst2,N),
    prefered_order(Dst1,Dst2), M > N.
```
This obviously reduces the number of ground rules (see `--text` for output) as it reduces complexity.
The rule is valid independent from the `Src` nodes, and in this specific case, independent from the quadratic combination of different sources. For every source that has a destination `Dst1` a copy of this rule was created.

**Comment by greg-gelfond** [comment]
Thank you Max. This makes sense and clarifies my understanding of anonymous variables. One more question if you don't mind: Consider the original rule:

rule_violation(r1) :-
    cluster(C),
    entry_points(C,N),
    N >= 2.

entry_points(C,N) :-
    cluster(C),
    N = #count{ (Src,Dst) : enters_cluster(Src,Dst,C) }.

I have a clear understanding of why inlining the aggregate:

rule_violation(r1) :-
    cluster(C),
    #count{ (Src,Dst) : enters_cluster(Src,Dst,C) } >= 2.

will yield a performance benefit.

I'm curious if the following rewrite of rule_violation(r1) is equivalent, and if so, if the use of anonymous variables has a similar effect as you described:

rule_violation(r1) :-
    cluster(C),
    { enters_cluster(_, _, C) } >= 2.

-- 
  Gregory Gelfond
  ***@***.***



On Wed, Jun 30, 2021, at 2:59 AM, Max Ostrowski wrote:
> 
> 
> `rule_violation(r2) :-
>     path(_,Dst1,M), path(_,Dst2,N),
>     prefered_order(Dst1,Dst2), M > N.
`
> using `path(_,Dst1,M)` is equivalent to creating a new predicate:
> 
> `path_projected(Dst,M) :- path(Src,Dst,M).
`
> and writing
> 
> `rule_violation(r2) :-
>     path_projected(Dst1,M), path_projected(Dst2,N),
>     prefered_order(Dst1,Dst2), M > N.
`

**Comment by rkaminsk** [comment]
>  I'm curious if the following rewrite of rule_violation(r1) is equivalent, and if so, if the use of anonymous variables has a similar effect as you described: `rule_violation(r1) :- cluster(C), { enters_cluster(_, _, C) } >= 2.`

Clingo only adds projection rules if this does not change the answer sets modulo the auxiliary atoms. The idea is that the program behaves as if anonymous variables were used but spare the programmer from writing all the projection rules. In your case, clingo will not add projection rules. If you want to tune your encodings, best use the `--text` option to see what is happening. Clingo only does simple rewritings, it should be relatively easy to understand what is happening.

**Comment by MaxOstrowski** [comment]
The easiest way to see the effect is using `--text` option of clingo and trying it out.
In your rule:
```
rule_violation(r1) :-
    cluster(C),
    { enters_cluster(_, _, C) } >= 2.
```
the projected is done like this
```
enters_cluster_projected(C) :- enters_cluster(Src, Dst, C).
```
So your rule will be grounded to:
```
rule_violation(r1) :-
    cluster(1),
    { enters_cluster_projected(1) } >= 2.
rule_violation(r1) :-
    cluster(2),
    { enters_cluster_projected(2) } >= 2.
...
```
and this is clearly not what you want. Given a fixed cluster `C`, there is only one atom `enters_cluster_projected(C)`.
You need to count the `Src` and/or `Dst`.
Given that you can not use a node twice I think it should be sufficient to only count one of them, projecting the other one.

**Comment by rkaminsk** [comment]
Hope we could shed some light on your issues. Closing this.
