### ISSUE TITLE
RuntimeError when opening nonexistent file with Control.load

### ISSUE THREAD

**Issue by jachymb** [potassco/clingo#320]
With the python API, when I run
`Control().load("nonexistent-file")`
I get a `RuntimeError` exception.

I think it should instead be a `FileNotFoundError` or perhaps some other subclass of `IOError`.

Not a big deal, just a consistency thing.

**Comment by rkaminsk** [comment]
The Python API maps the error codes from clingo's C API to Python errors. To support something like this, there would have to be corresponding error codes. Without a good reason, for example if it were critical for an application, I won't put any effort there. So I am closing this for now.
