### ISSUE TITLE
Invoke a function when a watch literal is assigned to false

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#326]
Is it possible to call [propagate()](https://potassco.org/clingo/c-api/5.0/structclingo__propagator.html#a666b871bab495a9e5904b6109c92feda) (or any other function like propagate()) when a watch literal is assigned to false? As I know, propagate() is called when any watch literal is assigned to true.

I have an idea to do this. For each watch literal a, 
- add a new atom `b`
- add a rule `b <- not a` 
- finally add a watch for atom `b` 

so that when `a = False` then `b = True`, Thus the propagate() is called for `b`.
Is there any other idea easier than this?

**Comment by rkaminsk** [comment]
I am not sure if I understand but you can watch a literal in any phase. If `l` is a solver literal, you can call `add_watch` with `l` and `-l`.

**Comment by mahi045** [comment]
Thanks for your information.
