### ISSUE TITLE
Difference between two consecutive assignments

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#327]
I am calling [clingo_propagate_control_assignment](https://potassco.org/clingo/c-api/5.0/group__propagator#ga3d51a5acec3aaadb615ca0c66c1b26fb) many many runs. Due to performance issues, it would be better for me if I can get the difference between two consecutive clingo_propagate_control_assignment calls. Is there any way to get this in Clingo C API via decision trail functions?

If not, then I would like to do it by myself. Can anyone please point me where I need to code this?

**Comment by rkaminsk** [comment]
The assignment is just a pointer. Receiving it is fast. You also only have to call this function once per propagate and can reuse the pointer.

Clingo 5.5 also introduced functions to access the assignment trail: <https://potassco.org/clingo/c-api/5.5/group__propagator#ga75f1c5df0d7d35b4031b025c91838e72>.

**Comment by mahi045** [comment]
Thanks for your information. 
Can I ask you what is the complexity of [clingo_assignment_truth_value](https://potassco.org/clingo/c-api/current/group__propagator#ga0a3ce77f8fcc8b72a29a0579be5f4baa)? Does the function scan the full assignment trail for each given literal (at worst case)?

**Comment by rkaminsk** [comment]
> Can I ask you what is the complexity of [clingo_assignment_truth_value](https://potassco.org/clingo/c-api/current/group__propagator#ga0a3ce77f8fcc8b72a29a0579be5f4baa)? Does the function scan the full assignment trail for each given literal (at worst case)? or the complexity is `O(1)`?

It's constant.

**Comment by rkaminsk** [comment]
You can do this using directly using the clasp library but note that you can also do this with the high level API. It gives you access to the trail: <https://potassco.org/clingo/python-api/5.6/clingo/propagator.html#clingo.propagator.Assignment.trail>. The API is probably easier to use. I would suggest you stick as much as possible with the API and only ever consider touching the clasp library if there is no other way (say for performance reasons or because some functionality is not available via the API).

**Comment by rkaminsk** [comment]
Here is an idea how this could be implemented using the API. Note that the code is completely untested.
```python
from typing import Sequence, List
from copy import deepcopy

from clingo.propagator import (
    Propagator,
    PropagateInit,
    PropagateControl,
    PropagatorCheckMode,
)


class TrailPropagator(Propagator):
    trail: List[List[int]]
    last_trail: List[List[int]]

    def init(self, init: PropagateInit) -> None:
        init.check_mode = PropagatorCheckMode.Fixpoint
        self.trail = []
        self.last_trail = []

    def _update_trail(self, control):
        assign = control.assignment
        level = assign.decision_level
        trail = assign.trail
        size = level + 1
        if len(self.trail) < size:
            self.trail.append([])
        elif len(self.trail) > size:
            self.trail.pop(len(self.trail) - size)
        cur = self.trail[level]
        add = trail[trail.begin(level) + len(cur) :]
        self.trail[level].extend(add)

    def propagate(self, control: PropagateControl, changes: Sequence[int]) -> None:
        self._store_trail(control)

        # we can compare last_trail and trail here
        # ...

        # Note: this can be implemented more efficiently
        self.last_trail = deepcopy(self.trail)

    def check(self, control: PropagateControl) -> None:
        self._store_trail(control)
```
