### ISSUE TITLE
Add additional explanations in the Documentation about symbolic atoms, program literals and solver literals

### ISSUE THREAD

**Issue by javier-romero** [potassco/clingo#329]
Hi, 

It would be good to say something like this (if it is correct :)
* symbolic atoms correspond to atoms in the gringo language
* program literals correspond to the literals of the aspif format
* solver literals correspond to the variables of the internal representation of clasp

There is an injective function from symbolic atoms to program literals, and
there is an injective function from program literals to solver literals.
But those functions do not have to be surjective.

**Comment by rkaminsk** [comment]
It would be great if you could go ahead and update the docstrings. The file is here: <https://github.com/potassco/clingo/blob/2c348fc39e862576349ef84701d38e1901d52c51/libpyclingo/clingo/__init__.py#L12> A PR against the wip branch would be nice.

**Comment by javier-romero** [comment]
Done!
