### ISSUE TITLE
Out of Identifier Error

### ISSUE THREAD

**Issue by hmqq** [potassco/clingo#333]
I have a rule file consisting of 241 rules that correspond to OWL 2 QL reasoning and I have a facts file that contains 26618 rules and a query file that corresponds to the datalog translation of the SPARQL query.  The Purpose is to translate ontology into a datalog program and use the fixed rules (241) and Facts to answer the query.

The rules in the rules.txt contain no negation and are recursive in nature.

When I execute this file in Clingo it gives me an "Out of Identifier" error. This is unusual for me because when the same 241 rules I used with different fact files they worked but with this particular file "MEF0" it give me this error.

I have attached all the files:
[MEF0.txt](https://github.com/potassco/clingo/files/7202832/MEF0.txt)
[rules.txt](https://github.com/potassco/clingo/files/7202833/rules.txt)
[query0.txt](https://github.com/potassco/clingo/files/7202834/query0.txt)

I wanted to ask:
How much large input file we can use with Clingo?
Is there a way to increase the size?
Is there any way to make above MEF0 work?

Thankyou!

Kind Regards,
Haya

**Comment by hmqq** [comment]
I have tried DLV2, and it worked.
I wanted to made it work with Clingo.

**Comment by rkaminsk** [comment]
It runs through with the `--text` option.

**Comment by hmqq** [comment]
Yes it run continuously, i waited for more then 30 minutes  and then i killed it.  I want particular predicate result in output. But this command output all the predicates.

**Comment by rkaminsk** [comment]
> Yes it run continuously, i waited for more then 30 minutes and then i killed it. I want particular predicate result in output. But this command output all the predicates.

You can use tools like [grep](https://www.gnu.org/software/grep/) or one of the many alternatives. The following pipe produces a line similar to what clingo without option `--text` would output:

```sh
clingo --text MEF0.txt rules.txt query0.txt | grep '^result' | tr -d '.' | paste -s -d ' '
```

In case you are using Windows, a modern shell like the power shell should provide the necessary tools. I just cannot help you there.
