### ISSUE TITLE
Error handling errors

### ISSUE THREAD

**Issue by stomir** [potassco/clingo#334]
Throwing an error while getting a model (in my case it's a timeout exception) results in an error like this:
```
File ".../python3.9/site-packages/clingo/solving.py", line 479, in model
    _handle_error(
File ".../python3.9/site-packages/clingo/_internal.py", line 60, in _handle_error
    if code == _lib.clingo_error_unknown and handler is not None and handler.error is not None:
AttributeError: '_SolveEventHandler' object has no attribute 'error'
```

My guess is that in `Control.solve` you're supposed to pass a `_CBData` object as a handler to `SolveHandle`, but you're passing a `_SolveEventHandler`.

**Comment by rkaminsk** [comment]
I had a quick glance. It looks like the argument to the `SolveHandle` constructor should simply be `data`. Do you have a small example to reproduce the issue?
