### ISSUE TITLE
Assumptions using C++ API

### ISSUE THREAD

**Issue by marklaw** [potassco/clingo#336]
Hi,

I'm getting some unexpected behaviour when using assumptions in the C++ API. This is the first time I've tried using assumptions, so please let me know if I'm doing something stupid. A minimal example showing the behaviour is:

```
#include <string>
#include <clingo.hh>
#include <iostream>

std::string program = R"ESC(
:- not p.
{ p }.
)ESC";

int main(int argc, char *argv[]) {
  using namespace std;

  Clingo::Logger logger = [](Clingo::WarningCode, char const *message) { cout << message << endl;};
  Clingo::Control ctl({{}, logger, 20});

  ctl.add("base", {}, program.c_str());
  ctl.ground({{"base", {}}});

  Clingo::SymbolicLiteralSpan assumptions {
    Clingo::SymbolicLiteral(Clingo::Function("p", {}), false)
  };  

  for(auto& m : ctl.solve(assumptions))
    for(auto& atom : m.symbols())
      cout << atom << " ";
  cout << endl;

  return 0;
}

```

When I run this simple program, I get the answer set containing `p`. I would expect this to be unsatisfiable, as I am passing an assumption saying that `p` should be false. I've tried doing the same using the Python API and I get the result I expect:

```
:- not p.
{ p }.

#script(python)
from clingo.symbol import Function

def main(prg):
    prg.ground([("base", [])])
    prg.solve(assumptions=[(Function("p"), False)], on_model=print)
#end.
```
The behaviour gets stranger if I add a weak constraint to the program (`:~ p.[1@1]` gives me an infinite number of answer sets, with `p` being printed repeatedly).

Mark

**Comment by marklaw** [comment]
Sorry, I've never used spans before, so didn't realise. So are you saying it needs to be written as:
```
  Clingo::SymbolicLiteral lit(Clingo::Function("p", {}), false);
  Clingo::SymbolicLiteralSpan assumptions{lit};
```

I'm still getting the same problem with the above fix.

**Comment by rkaminsk** [comment]
> Sorry, I've never used spans before, so didn't realise. So are you saying it needs to be written as:
> 
> ```
>   Clingo::SymbolicLiteral lit(Clingo::Function("p", {}), false);
>   Clingo::SymbolicLiteralSpan assumptions{lit};
> ```
> 
> I'm still getting the same problem with the above fix.

You are initializing the span with an initializer list. The initializer list is freed right after the statement. You could use a vector of symbolic literals and it would work.

**Comment by marklaw** [comment]
Ah, okay. Sorry, I misunderstood your previous reply. I've tried using a vector as you suggested (below) but still get the same result. Note that the cast to a span is necessary otherwise the compiler complains that the call to solve is ambiguous.

```
#include <string>
#include <clingo.hh>
#include <iostream>
#include <vector>
#include <span>

std::string program = R"ESC(
:- not p.
{ p }.
)ESC";

int main(int argc, char *argv[]) {
  using namespace std;

  Clingo::Logger logger = [](Clingo::WarningCode, char const *message) { cout << message << endl;};
  Clingo::Control ctl({{}, logger, 20});

  ctl.add("base", {}, program.c_str());
  ctl.ground({{"base", {}}});

  Clingo::SymbolicLiteral lit(Clingo::Function("p", {}), false);
  vector<Clingo::SymbolicLiteral> assumptions {lit};

  for(auto& m : ctl.solve((Clingo::SymbolicLiteralSpan) assumptions))
    for(auto& atom : m.symbols())
      cout << atom << " ";
  cout << endl;

  return 0;
}
```

I've also tried creating a span from the vector:

```
  //...
  vector<Clingo::SymbolicLiteral> assumptions {lit};
  Clingo::SymbolicLiteralSpan ass_2(assumptions);

  for(auto& m : ctl.solve(ass_2))
  //...
```

None of the programs I've sent so far have shown any issues when running them with valgrind, but perhaps I am not passing the correct flags to valgrind...?

Apologies if I'm missing something stupid.

Thanks,

Mark

**Comment by rkaminsk** [comment]
> Apologies if I'm missing something stupid.

Now, you are calling it correctly. It looks like the trivially violated assumption is for some reason ignored. I'll have a closer look later.

**Comment by marklaw** [comment]
Okay, thank you!

**Comment by rkaminsk** [comment]
This seems to be a regression in the recent development version. The program
```python
:- not p.
{ p }.

#script(python)
from clingo.symbol import Function

def main(prg):
    prg.ground([("base", [])])
    print("no yield")
    prg.solve(assumptions=[(Function("p"), False)], on_model=print)
    print("async no yield")
    with prg.solve(assumptions=[-prg.symbolic_atoms[Function("p")].literal], async_=True) as hnd:
        hnd.get()
    print("async yield")
    with prg.solve(assumptions=[-prg.symbolic_atoms[Function("p")].literal], yield_=True, async_=True) as hnd:
        for m in hnd:
            pass
        hnd.get()
    print("yield")
    with prg.solve(assumptions=[-prg.symbolic_atoms[Function("p")].literal], yield_=True) as hnd:
        for m in hnd:
            pass
        hnd.get()
#end.
```
produces different output depending on which version is used.  With clingo 5.5.0 it is
```
➜ clingo-5.5.0 test.lp                  
clingo version 5.5.0
Reading from test.lp
no yield
Solving...
async no yield
Solving...
async yield
Solving...
yield
Solving...
UNSATISFIABLE

Models       : 0
Calls        : 4
Time         : 0.030s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.028s
```
and with the latest development version it is
```
➜ clingo-dev test.lp
clingo version 5.5.1 (4b56eed)
Reading from test.lp
no yield
Solving...
async no yield
Solving...
async yield
Solving...
yield
Solving...
Answer: 1
p
SATISFIABLE

Models       : 1+
Calls        : 4
Time         : 0.034s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.028s
```

**Comment by marklaw** [comment]
Okay. Thanks for getting back to me. Is it likely to be a quick fix, or shall I use another approach for now? I can active what I want by adding constraints and using externals, but in the long run I think assumptions may be more efficient.

**Comment by rkaminsk** [comment]
> Okay. Thanks for getting back to me. Is it likely to be a quick fix, or shall I use another approach for now? I can active what I want by adding constraints and using externals, but in the long run I think assumptions may be more efficient.

I am not sure how important that for loop is for you. The other 3 variants to call the solve function seem to work. You could simply set `async` to true, too. You should not notice a difference. It is probably only this corner case that is broken because I have some unit tests involving assumptions.

**Comment by rkaminsk** [comment]
Fixed. Development packages are on the way.

**Comment by marklaw** [comment]
Thanks!
