### ISSUE TITLE
Multi-threaded use of the C++ API

### ISSUE THREAD

**Issue by marklaw** [potassco/clingo#337]
Quick question: is there any reason the C++ API should not work in a multi-threaded program?

To give some context, I have previously tried using it, where I have many separate threads which are each using the API to solve different programs (so completely different Clingo::Control objects etc.), but it has always led to (non-deterministic) segmentation faults within clingo. I haven't tried in a while, so you may have fixed the issue, but before I try again, I just thought I would check that there is no known reason this won't work.

If you think it should work, I'll try to put together a minimal example that seg faults with the latest version of clingo.

Thanks,

Mark

**Comment by rkaminsk** [comment]
> To give some context, I have previously tried using it, where I have many separate threads which are each using the API to solve different programs (so completely different Clingo::Control objects etc.), but it has always led to (non-deterministic) segmentation faults within clingo. I haven't tried in a while, so you may have fixed the issue, but before I try again, I just thought I would check that there is no known reason this won't work.

This should work. You have to be careful accessing the same control object from different threads though.

> If you think it should work, I'll try to put together a minimal example that seg faults with the latest version of clingo.

If this is causing bugs, then please send an example.

**Comment by marklaw** [comment]
I haven't been able to reproduce the issue I had a few years ago with this. I think whatever it was has been fixed in the later versions of clingo. I'll close this now and reopen or open a new issue if I ever encounter it again.

Sorry, I should have checked that it was still an issue before bothering you. I just wanted to know if there was an obvious reason before wasting too much time on it.

I'm now getting some issues with Python's GIL, when solving programs with python scripts in multiple threads but I think I know why this is and will try to find a workaround myself.

**Comment by rkaminsk** [comment]
Good luck.
