### ISSUE TITLE
The --outf option is not mentioned in the --help text

### ISSUE THREAD

**Issue by broesdecat** [potassco/clingo#34]
Hi,

The --help text does not contain information on how to obtain the answer set in a more machine-readable format. In the pdf guide, I found that I can use --outf for this :)
Something to add to --help?

Thx!
Broes

**Comment by Aluriak** [comment]
You can access a more complete help with `--help=2` (which contains the `--outf` option) and `--help=3`, the most verbose help command.

**Comment by broesdecat** [comment]
Ah I see. I was not expecting `--help` to have levels ^^
What added to the confusion was that if you call `clingo --outf=x`, then you get
`*** ERROR: (clingo): SyntaxError: 'outf' requires a value!`
`*** Info : (clingo): Try '--help' for usage information`
Maybe there it can be specified that there are multiple levels?

**Comment by BenKaufmann** [comment]
> I was not expecting --help to have levels

If you "Try '--help' for usage information", you'll get:

> --help[=\<n\>],-h         : Print {1=basic|2=more|3=full} help and exit

So, the information is there ;)

I agree that the error message could be more expressive. However, 
I don't think that doing something like:
> Try '--help[={2..3}]' for (extended) usage information

would make much of a difference. A truly helpful message would contain context sensitive information
but this would require quite some effort to implement.

As a compromise, I'll add a more prominent hint to the end of the '--help' output.
