### ISSUE TITLE
comparing two series in ASP

### ISSUE THREAD

**Issue by Nsharma213** [potassco/clingo#348]
Hello All,
I am working on my thesis and I need a little help from you.
I am developing a model for market prices and extracting the data dynamically into clorm classes. I have a scenario where I have a curve which compares values from two dates - current and reference (for different grid points- dates) and gives a suspect if the difference between those values is more than the threshold. I have achieved this using ASP.
But now I have to check if all the curves move in a similar manner( for eg all the curves have positive suspects or negative suspects or if they move parallelly) . Could you please help me how can i achieve it.

**Comment by rkaminsk** [comment]
Hello, could you also give us your current encoding (simplified as much as possible) so that we can look at the current state of your work. This will make it much easier for us to help. You might also want to ask your question on our mailing list. There it will reach a wider audience: <https://sourceforge.net/projects/potassco/lists/potassco-users>.

**Comment by Nsharma213** [comment]
#const relthreshold=50.
value("2021-09-25","raw.CO_API#1",11700,"2022-01-01").
value("2021-09-25","ref_raw.CO_API#1",11345,"2022-01-01").
value("2021-09-25","raw.CO_API#1",7350,"2022-02-01").
value("2021-09-25","ref_raw.CO_API#1",6990,"2022-02-01").
**/* These are the input factbase, (for one date, there are two curves with different values for different monthly future prices)*/
I/* I calculate the relative difference and if the difference is more than the threshold I have a suspect( issue point) */**
valreldiff(N1,D,S,G):- value(D,N,V,G), value(D,N1,V1,G), S=((V-V1)*1000)/V1,reference(N,N1).
suspectv("validation check",N1):- valreldiff(N1,D,S,G),|S|>=relthreshold.
grids(N1,G,S,D):-valreldiff(N1,D,S,G),|S|>=relthreshold.

Now I have many curve sets like these eg.raw.CO_API#2,ref_raw.CO_API#2. I want to calculate if all the curves move in a similar way, like if all are suspected by +5 or may be -5( this I can calculate), but in a similar fashion/manner/movement/all upward/all downward/all twisting..

**Comment by rkaminsk** [comment]
You should post your question to our mailing list.
