### ISSUE TITLE
The aggregation function sum has some problems.

### ISSUE THREAD

**Issue by LarryWenatGU** [potassco/clingo#35]
Look at the code: 

#sum+{1: one; 1 : another_one; 2 : two}=3.

It should have two models: {one, two}, and {another_one, two}, but it actually get three models. The extra one is {one, another_one, two}. I found that if two keys with the same weight, like one and another_one, then it will cause problem. Also, if we change the code to 

#sum+{1: one; 1 : another_one; 2 : two}=4.

Then it has no model. But it should have one model {one, another_one, two}. 
I tested the program with gringo and clasp, it has the same problem. It would be great if this bug can be fixed.

**Comment by LarryWenatGU** [comment]
In the above examples, I used sum+, actually it is the same as sum.

**Comment by rkaminsk** [comment]
This works as intended. Check out our [FAQ entry about aggregates](https://potassco.org/doc/faq/2017/04/20/how-do-sum-aggregates-work.html). Our [guide](https://potassco.org/doc) also has a more detailed section about aggregates.

**Comment by LarryWenatGU** [comment]
thank you rkaminsk
