### ISSUE TITLE
() signs are removed in the console output.

### ISSUE THREAD

**Issue by Genco2** [potassco/clingo#356]
Hello Everyone,
I have a question about the output in the console.
For example I have such a predicate; _func : x(y())_ in f1.lp, and my query is satisfiable with this func().
When I give the command; _python -m clingo f1_,
In the console I see ; _x(y)_. For some reason () signs are being removed. Is there a way to prevent this ?
Thanks a lot.
Genco Cosgun.

**Comment by MaxOstrowski** [comment]
I think a "zero-arity function" is usually considered a "constant" and 
therefore
"y()" and "y" should be equivalent.
I do not think that there is a way to distinguish between them, and I 
would recommend not to use "y()" in the first place.

Best,
Max

Am 20.01.22 um 12:25 schrieb Genco2:

**Comment by Genco2** [comment]
Thanks a lot both for clear answer and fast response!
Genco Cosgun
