### ISSUE TITLE
Progression update on USC

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#357]
When using `clingo -t2` or `--opt-strat=usc` I do get "progression" updates which includes **lower** and **upper** bounds.
Is there a way to intercept this information during a solve call?

The **upper** bound can easily be determined using the `on_model` callback.
What about the **lower** bound ?

This would be useful to emulate features of solvers like `cplex` that have command line options to stop search if within i.e. 5% range of the optimum.

**Comment by rkaminsk** [comment]
#242 :wink:

**Comment by MaxOstrowski** [comment]
Awesome, thanks, I haven't found this old Issue and wasn't aware that this is already possible. Thanks a lot guys.

**Comment by rkaminsk** [comment]
> Awesome, thanks, I haven't found this old Issue and wasn't aware that this is already possible. Thanks a lot guys.

You opened it yourself. :smile:
