### ISSUE TITLE
Python API SIGSEGV during call to model.symbols (clingo 5.5.0)

### ISSUE THREAD

**Issue by Glinzerow** [potassco/clingo#358]
I sometimes ran into the following error code:
_Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)_
Debugging with python faulthandler yielded the following:

_Fatal Python error: Segmentation fault_

_Current thread 0x00007efd70e14740 (most recent call first):
  File "/some_path/lib/python3.9/site-packages/clingo/solving.py", line 345 in symbols
  File "/some_path/benchmarking/benchmark-GUC/solvers/python_solvers/two_solvers_brave.py", line 147 in check'
...

The call in line 147 was the following:

`model.symbols(shown=True, complement=True)
`
The `model` was received the following way:
In the init method the control object was set(the missing space between -e and brave is not a typo, it might be a little bug?):
`self._ctl = Control(['-ebrave'])`

In the check method the brave model was computed the following way:
`  with self._ctl.solve(assumptions, yield_=True) as hnd:`
`  for i, _ in enumerate(hnd):`
`  model = hnd.model()`
(sorry for missing indents)

I can provide more information if requested.

**Comment by rkaminsk** [comment]
Could you please send a full example that produces the segfault?

PS: Short options with an argument do not need a space after them. You could also write `['-e', 'brave']`.

PPS: You can use triple backticks for code

    ```python
    while True:
        pass
    ```

**Comment by Entze** [comment]
Compare your code with the code in #305 

Models cannot be reused outside of their handling context. You can save the symbols though. I just had a similar problem.

**Comment by Glinzerow** [comment]
Thanks! That solved my problem.
