### ISSUE TITLE
Jupyter Kernel for Clingo

### ISSUE THREAD

**Issue by thesofakillers** [potassco/clingo#360]
Not an issue!

Just wanted to quickly share that I've made a very basic clingo kernel for [jupyter](https://jupyter.org/), so that you can make jupyter notebooks in clingo. 
https://github.com/thesofakillers/iclingo

It's far from perfect, but it's something. Perhaps the visibility from posting here will welcome contributions :)

**Comment by tortinator** [comment]
Thank you, @thesofakillers ! You might want to post this to our mailing list potassco-users@lists.sourceforge.net 
We are also using jupyter notebooks for teaching at teaching.potassco.org

FYI @javier-romero @susuhahnml

**Comment by thesofakillers** [comment]
Thanks @tortinator for the mailing list suggestion! I've sent an email and it is waiting to be moderated. Closing this issue now to keep your repo tidy :)
