### ISSUE TITLE
The 'type' attribute of External AST node does not exist.

### ISSUE THREAD

**Issue by ZhangShutao** [potassco/clingo#384]
According to the grammar and constructor method, an external statement has an attribute 'type.' However, when parsing an external node with VisitTransformer, the type attribute does not exist, and `print(external), print(external.type)` will get the following output:
```
#external fly(X) : bird(X). [false]
AttributeError: no attribute: type
```
When constructing with the following code:
```
external = clingo.ast.External(loc, fly, body, clingo.ast.Function(loc, 'false', [], True))
```
The `false` is an unfound function, and the output is 
```
#external fly(X) : bird(X). [@false]
```
So here are my questions: 

1. What is the 'type' attribute? 
2. How to construct an external statement without parsing?

**Comment by rkaminsk** [comment]
Hello, you can always parse the statement you want to construct and print it's representation. You can then paste the resulting output and adjust it to your needs. Otherwise, the type can be `true`, `false`, or `free` for the initial truth value of the external atom.
