### ISSUE TITLE
Segmentation fault when iterating over Control.symbolic_atoms.by_signature()

### ISSUE THREAD

**Issue by daveraja** [potassco/clingo#389]
Iterating over a signature where there are no matching entries will cause a seg fault for the latest Clingo. So, the following is fine with Clingo 5.5 but seg faults with Clingo 5.6.0:

    from clingo import Control, Number, String, Function, SymbolType
    from clingo.ast import parse_string, ProgramBuilder

    prgstr = """x(1)."""
    ctrl = Control()

    with ProgramBuilder(ctrl) as pb:
        parse_string(prgstr, pb.add)
    ctrl.ground([("base", [])])

    for sa in ctrl.symbolic_atoms.by_signature("x", 1, False):
        print(f"{sa}")

**Comment by rkaminsk** [comment]
Definitely a bug. Maybe something mishap when refactoring code. It should not be difficult to fix. Will take care of it tomorrow.
