### ISSUE TITLE
Question: Polarity Heuristic of clasp

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#397]
It is a question:
As I checked the [code](https://github.com/potassco/clasp/blob/master/clasp/solver_types.h#L581), clasp maintains the following hierarchy to choose the polarity of a variable:
```
user > saved > preferred > current sign score of heuristic > default value
```

I am interested to know about the purposes of different types of values (e.g., user and preferred values).
Thanks in advance.

**Comment by rkaminsk** [comment]
This question might be better asked at the clasp project (@BenKaufmann). I think (but don't know) the values are related to the different heuristics offered by clasp:

- user: The domain heuristic allows for selecting the sign based on rules.
- saved: There is the progress saving heuristics (also phase saving heuristics) that restores signs after restarts.
- preferred: I don't know.
- current: Related to the sign selection heuristic configurable via the command line.
- default: Default signs can be configured via the command line.

**Comment by BenKaufmann** [comment]
@rkaminsk @mahi045 
As an addition: the "preferred" type is currently only used if option "--opt-heuristic" contains "sign".  In that case, variables occurring in a minimize statement have their "preferred" polarity set to the value that minimizes their overall weight.

**Comment by rkaminsk** [comment]
I am not sure what you are trying to ask here. Do you know about he different command-line options we are referring to?

> Thanks to @rkaminsk and @BenKaufmann. Please clarify the following points:
> 
>     * user: makes sense only for domain heuristic
> 
>     * preferred: makes sense only for optimization problems.
> 
>     * current: makes sense if there is no saved value for a variable
> 
>     * default: makes sense if I specify the polarity via the command line

**Comment by BenKaufmann** [comment]
Some minor additions:
- The *user*  value is influenced by the domain heuristic, either via _Heuristic_ statements (of type _sign_) in the (aspif) input or via the "`--dom-mod`" command-line option.
- The *saved* value is typically only used if option "`--save-progress`" is active
- If available, the current sign score of the active heuristic is used for a variable if it has no *user*, *saved*, or *preferred* value
- The *default* value is typically only used when computing brave/cautious consequences.
- The value specified via "`--sign-def`" is only used if **none** of the previous values applies.
