### ISSUE TITLE
Question on efficient model counting

### ISSUE THREAD

**Issue by RenatoGeh** [potassco/clingo#399]
Hi,

Is there an efficient way to count models? The way I am doing now is simply enumerating through all possible models, e.g.

```python
def count(_):
  global x; x += 1

import clingo

C = clingo.Control(["0"])
C.add("base", [], "{a; b; c; d}.")
C.ground()
x = 0
C.solve(on_model = count)
```

but I was wondering if clingo had a smarter and more efficient way to do this, as I only need the number of models for a program, and not the actual models. I looked at the documentation and couldn't find an option to only do model counting.

Thanks

PS: Thanks for developing and maintaining clingo! :)

**Comment by rkaminsk** [comment]
Our solver can only count models by enumerating all of them. You can probably avoid some overhead by not passing an `on_model` callback and simply extract the number of enumerated models from the statistics. There is some work on more clever ways to count models. Maybe @daajoe can give some pointers because he was working on this topic.

**Comment by RenatoGeh** [comment]
I see. Thanks for the quick reply!

> You can probably avoid some overhead by not passing an `on_model` callback and simply extract the number of enumerated models from the statistics.

I'm actually writing everything in C, so no callbacks. Is it wrong of me to assume that passing [`clingo_solve_mode_yield`](https://potassco.org/clingo/c-api/current/group__SolveHandle.html#gga63eb87834deebecdf9c799d64a3c65a2a60a9c133be636e68a7d02680c8b9d47e) and doing the counting within the [`clingo_solve_handle_model`](https://potassco.org/clingo/c-api/current/group__SolveHandle.html#gaf9353c14149a2a16adf0474796871ae1) loop should be as fast as just querying from the statistics map? Or is there a more efficient way?

**Comment by RenatoGeh** [comment]
Great. Thanks for the info. :)

Closing my question now.
