### ISSUE TITLE
How to express parity constraints?

### ISSUE THREAD

**Issue by zzwonder** [potassco/clingo#400]
Hi, thanks for developing clingo. I'd like to use constraints that set the parity of a set or integer. However, I noticed that #odd and #even were removed in Clingo 4. I am wondering if there is any replacements for #odd and #even?  Thanks!

Zhiwei

**Comment by zzwonder** [comment]
Solved. It can be done by integer modulo operation, e.g., "3 \ 2 = 1".

**Comment by rkaminsk** [comment]
You might also be interested in the following: <https://github.com/potassco/xorro>.
