### ISSUE TITLE
Sign lost for Comparison in AST

### ISSUE THREAD

**Issue by alviano** [potassco/clingo#402]
Dear Roland,

Could you have a look at the following test cases?

$ python -c 'import clingo.ast; clingo.ast.parse_string(":- not 1 == 1.", print)'
#program base.
#false :- 1 = 1.

$ python -c 'import clingo.ast; clingo.ast.parse_string(":- not not 1 == 1.", print)'
#program base.
#false :- 1 = 1

Unrelated to the above issue, the empty show directive is printed in a form that cannot be parsed back (not sure if it is wanted):

$ python -c 'import clingo.ast; clingo.ast.parse_string("#show.", print)'
#program base.
#show /0.

Many thanks for your hard work!

All the best,
Mario

**Comment by rkaminsk** [comment]
Thanks Mario! Already created a PR. Now will wait for the tests to finish and then deploy dev packages.
