### ISSUE TITLE
Support custom malloc in build system

### ISSUE THREAD

**Issue by haampie** [potassco/clingo#407]
In [Spack](https://github.com/spack/spack) we're using clingo, and there I noticed there's a consistent 15% speedup when switching from glibc malloc to mimalloc:

```
$ export LD_PRELOAD=/path/to/libmimalloc.so
$ spack solve --timers hdf5+mpi
...
    load           0.015s
    ground         2.032s
    solve          2.448s
...
```
vs
```
$ spack solve --timers hdf5+mpi
    load           0.016s
    ground         2.312s
    solve          3.061s
```

(Also an equal speedup when enabling profile guided optimization and link time optimization)

Would it be OK to support this directly in the build system? On Linux you can rely on LD_PRELOAD, but it's cumbersome in that it affects all applications. I don't have numbers for macOS, but there it's definitely harder to take a libc symbol from a different dylibc, and DYLD_* variables don't propagate to child processes.

**Comment by rkaminsk** [comment]
Shouldn't it be enough to set the linker flags when compiling clingo without any changes to clingo itself?

**Comment by haampie** [comment]
Personally I think it's better to do it in the build system, since cmake knows the relevant flags for specific compilers, and mimalloc has a cmake-config file. On top of that it's a bit finicky to get this right, since (on linux/elf platforms) when libclingo is dlopen'ed, it will resolve the malloc symbol first from its dependents, not from dependencies. So you typically end up with default malloc.

One option is to compile with the object file and use `-Wl,-Bsymbolic` to force the dynamic loader to look for malloc inside the shared library itself. Of course that could *also* be done through -DCMAKE_* flags, but I think it's cleaner to make it part of the build system under a toggle `-DCLINGO_WITH_MIMALLOC:BOOL=ON` and have it do `find_package(mimalloc 2.0 REQUIRED)` conditionally, and ensure that the shared libs are created with `-Wl,-Bsymbolic` on relevant platforms.

I'm happy to open a pull request, let me know what you think.

**Comment by rkaminsk** [comment]
> One option is to compile with the object file and use `-Wl,-Bsymbolic` to force the dynamic loader to look for malloc inside the shared library itself. Of course that could _also_ be done through -DCMAKE_* flags, but I think it's cleaner to make it part of the build system under a toggle `-DCLINGO_WITH_MIMALLOC:BOOL=ON` and have it do `find_package(mimalloc 2.0 REQUIRED)` conditionally, and ensure that the shared libs are created with `-Wl,-Bsymbolic` on relevant platforms.

If it can be done with a few lines of cmake code, I am fine with this. It looks like an option has to be introduced and mimalloc has to be added to the target link libraries. Does it have to be added to all targets or is just the clingo library enough? Furthermore, the webpage suggests to include `mimalloc-new-delete.h` for best performance with C++.

> I'm happy to open a pull request, let me know what you think.

Yes, please go ahead.

**Comment by haampie** [comment]
Scoping mimalloc's malloc just to libclingo seems difficult if not impossible to achieve in the end :( if you link mimalloc statically but keep the symbol visible, it gets overridden by glibc malloc (from python in my case); if you make the symbol hidden/private (through `-Wl,--version-script` with `global: clingo_*; local: *;`) it seems to run into issues where malloc from glibc is used but free from mimalloc, causing segfaults. Maybe LD_PRELOAD is the way...

**Comment by rkaminsk** [comment]
Have you tried just using the header `mimalloc-new-delete.h`? Clingo should mostly use C++'s new/delete.

**Comment by haampie** [comment]
Ah, nice, that can indeed be scoped to `libclingo`. I didn't even try, cause it's an implementation header, so it thought it would be similar to statically linking malloc. But the upside is that now it can work without the `malloc` override. I will test a bit more, see if it's better to statically link mimalloc (and if so, the --version-script file may be nice to have, since we can't control the visibility of the static mimalloc lib)

**Comment by haampie** [comment]
At the end of the day, `mimalloc-new-delete.h` worked "by accident" for our use of the Python module. This is because including the header puts operator new/delete symbols in libclingo.so, and libclingo.so itself happens to be the first library to pull in libstdc++.so. So basically it's globally overriding operator new/delete, but its success depends on load order of shared libs; in our case that translates into the order in which Python modules are imported.

Given that it's so brittle, I think I'll drop this and stick to a small, hacky patch in Spack itself to ensure mimalloc's new/delete are used.

**Comment by rkaminsk** [comment]
> At the end of the day, `mimalloc-new-delete.h` worked "by accident" for our use of the Python module. This is because including the header puts operator new/delete symbols in libclingo.so, and libclingo.so itself happens to be the first library to pull in libstdc++.so. So basically it's globally overriding operator new/delete, but its success depends on load order of shared libs; in our case that translate

Then the LD_PRELOAD options looks better. Changing clingo to explicitly use mimalloc (or any other library) would be  possible but this would be a rather large patch.
