### ISSUE TITLE
*Anytime* Cautious Reasoning

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#422]
Hi,
Is it possible to compute _anytime_ cautious reasoning using clingo?

**Comment by rkaminsk** [comment]
The solver reports a lower and upper bound on the cautious consequences whenever a model is found. You see `Consequences: [l;u]` in the output. Unfortunately, there is no easy way to check which atoms have already been shown to be cautious consequences. This is rather a problem with the API, which does not (conveniently) expose this information. One could still get this information but it would require using a propagator.

**Comment by rkaminsk** [comment]
> I see, thank you

If this is important for your application, it would probably be easy to extend the API to query whether an atom is a consequence.

**Comment by rkaminsk** [comment]
I implemented a first draft in #423.
