### ISSUE TITLE
unexpected warning message "info: operation undefined"

### ISSUE THREAD

**Issue by maliabd-al-majid** [potassco/clingo#428]
I have tried this simple program:
`#const l=2.`
`neg(G,V):- neg(G),val(G,X),V=l-1-X.`
`1{val( a,0..(l-1))}1.`
`1{val( b,0..(l-1))}1.`
`neg(b).`
`val(min1, R):- R = #min { Y : val(a, Y);X:neg(b, X)}.`

I keep getting a warning:

> -:3:34-35: info: operation undefined:
  (-1*X+1) 
  
  this warning appears only whenever I use the 'neg rule', due to the calculation there.
  
  is there a way to hide this warning, or to reformulate the program to avoid getting it?
  
  thanks in advance.

**Comment by rkaminsk** [comment]
You can use option `-Wno-operation-undefined` to suppress the warning.

Since your min aggregate has at least one element, you can safely add `R !=#sup` to the body of the last rule:

    val(min1, R):- R = #min { Y : val(a, Y);X:neg(b, X)}, R !=#sup.

**Comment by maliabd-al-majid** [comment]
thanks alot for your reply.
