### ISSUE TITLE
Example of incremental solving of the paper "How to build your own ASP system"

### ISSUE THREAD

**Issue by javier-romero** [potassco/clingo#431]
Hi, the paper "How to build your own ASP system", in the section 5.3 titled "Incremental Solving", refers to:
* Potassco Team. 2021h. Solving the towers of hanoi problem with clingo. https://github.com/potassco/clingo/tree/master/examples/clingo/opt.

but the actual code used in the paper is here:
* https://github.com/potassco/clingo/tree/master/examples/clingo/multishot

It seems that we should either change the directory names in clingo, or change the entry in the biblio of the paper.

**Comment by rkaminsk** [comment]
I can simply remove the opt example because it is superseded by the multishot one. I would not rename multishot to opt because it is a bad name. Better change in the paper.

**Comment by rkaminsk** [comment]
I removed the old opt example. The intent was to use the multishot example in the paper.
