### ISSUE TITLE
Any way to retrieve the priority levels from an answer set?

### ISSUE THREAD

**Issue by mbalduccini** [potassco/clingo#440]
Pretty much as the title says... both the clingo executable and the API return the costs as a vector of integers, e.g.
```
Optimization: 1 2 1
```
Is it possible to retrieve the priority levels associated with those costs using the API?

This seems particularly important in multi-shot solving, where we have noticed that the size of the vector may actually *decrease* when new `#minimize` statements are added to program via the backend.

Thanks!
Marcello

**Comment by rkaminsk** [comment]
#406 extends the API to get this info. There is no release yet but the development packages on conda, etc. already provide the functionality.

**Comment by mbalduccini** [comment]
That's great, thanks!
Does clingcon on conda also have it?

**Comment by rkaminsk** [comment]
> That's great, thanks! Does clingcon on conda also have it?

clingcon is using clingo as a library. As long as you take the dev version of both, then it should be available.

**Comment by mbalduccini** [comment]
Great!
