### ISSUE TITLE
atom in disjunction visible in answer set although it is not visible in grounding (and should not be true)

### ISSUE THREAD

**Issue by peschue** [potassco/clingo#45]
In the attached minimal.lp there is a fact
`sequence (0,"Volkstheater").`
and a rule with the disjunctive head
`sequence(I,L) | nsequence (I,L)`

There is no other rule defining sequence/2 or nsequence/2.

Therefore `nsequence(0,"Volkstheater")` can never become true.

However if I run `minimal.lp` with clingo 5.2.0 or with clingo `01dffb` (quite recent master branch hash) then some answer sets contain this atom. If I pipe gringo output into clasp directly this also happens.

If I use `gringo --text` on `minimal.lp` then the rule with `nsequence(0,"Volkstheater")` in the head is not even shown, it seems to be optimized away (which is correct, because it is satisfied by the fact).

[minimal.zip](https://github.com/potassco/clingo/files/1108468/minimal.zip)

**Comment by rkaminsk** [comment]
Will be fixed in next release.

**Comment by peschue** [comment]
Thank you, it is solved!
