### ISSUE TITLE
Optional

### ISSUE THREAD

**Issue by jorgefandinno** [potassco/clingo#454]
Several of these arguments default to ```None``` but if you pass ```None``` to them, ```mypy``` will complaing. Should they be changed to ```Optional[...]```?

https://github.com/potassco/clingo/blob/ba5ec6982fe39b8d7c579803a28a2b0cb55b655c/libpyclingo/clingo/ast.py#L1252-L1258

Same here:

https://github.com/potassco/clingo/blob/ba5ec6982fe39b8d7c579803a28a2b0cb55b655c/libpyclingo/clingo/ast.py#L1315-L1321

**Comment by rkaminsk** [comment]
The `Optional` around the control object is an omission. It used to be possible to set a `Callable` to `None`. This is no longer the case so it should also be wrapped.
