### ISSUE TITLE
quick arithmetic between two aggregate expression in place

### ISSUE THREAD

**Issue by evan0greenup** [potassco/clingo#458]
Currently `clingo` only support comparison or arithmetic operation between constant or variable and aggregate expression. 
like `hello(N, P) :- N = #count{A: kick(A)}.`. But it doesn't support for example `:- #count{X: vertex(X)} = #count{X,Y: edge(X, Y)}.`

It would be nice to add support for expression similar to `:- #count{X: vertex(X)} = #count{X,Y: edge(X, Y)}.`.

**Comment by rkaminsk** [comment]
It is unlikely that clingo will ever have such an extension. However, you can express this already:
```prolog
:- #sum{-1,X: vertex(X); 1,X,Y: edge(X, Y)} = 0.
```
