### ISSUE TITLE
Solving iteratively (as in `examples/cc/solve_iteratively.cc` gives different results than solving using the CLI.

### ISSUE THREAD

**Issue by nuernbergk** [potassco/clingo#492]
I am using the following function to solve a program given by a string iteratively:
```
void solve_iteratively(std::string program)
{
	try
	{
		Clingo::Logger logger = [](Clingo::WarningCode, char const *message)
		{
			std::cerr << message << std::endl;
		};

		std::vector<char *> args = {"-n", "8"};
		Clingo::Control ctl = Clingo::Control{{&args[0], args.size()}, logger, 20};
		ctl.add("base", {}, program.c_str());
		ctl.ground({{"base", {}}});
		for (auto &m : ctl.solve())
		{
			std::cout << "Model no." << m.number() << " :";
			for (auto &atom : m.symbols())
			{
				std::cout << " " << atom;
			}
			std::cout << "\n";
		}
	}
	catch (std::exception const &e)
	{
		std::cerr << "example failed with: " << e.what() << std::endl;
	}
}
```
This is essentially exactly what `examples/cc/solve_iteratively.cc` does. This kind of control over models is useful in my use case, and it would be nice not to have to use the CLI (or the kind of interface defined in `clingo_app.hh`).

However, this does not give the same results as the CLI!
For example, adapting the Hamiltonian Path problem
```
% Generate
{ cycle(X,Y) : edge(X,Y) } = 1 :- node(X).
{ cycle(X,Y) : edge(X,Y) } = 1 :- node(Y).
% Define
reached(Y) :- cycle(1,Y).
reached(Y) :- cycle(X,Y), reached(X).
% Test
:- node(Y), not reached(Y).
% Display
#show cycle/2.

% Optimize
#minimize { C,X,Y : cycle(X,Y), cost(X,Y,C) }.

% Nodes
#const n = 10.
node(1..n).
% (Directed) Edges
edge(X, (X..n)) :- node(X).
edge(X, (1..X)) :- node(X).

cost(A, B, A*B) :- node(A), node(B).
```
the CLI gives me `cycle(1,5) cycle(2,1) cycle(3,2)  cycle(4,6) cycle(5,7) cycle(6,8) cycle(7,4) cycle(8,10) cycle(9,3)   cycle(10,9)` for the first model, whereas `solve_iteratively` gives me `cycle(1,5) cycle(2,1) cycle(3,4) cycle(4,6) cycle(5,7) cycle(6,8) cycle(7,3) cycle(8,10) cycle(9,2) cycle(10,9)`.

These also have different optimization levels: The total cost for the former is 345, for the latter, it is 335.
This example explains an issue I had with very large logic programs, where solving successively stops giving out better models much sooner than solving using the CLI, because the CLI seems to take longer to get to the same optimization levels as solving successively (after which things start to slow down); indeed, this effect can be reproduced by setting `n` to be very large.

This behaviour seems strange and undesirable, however, maybe I am misunderstanding something about the clingo C++ API. Note that the same thing happens when using the interface for the CLI defined in `clingo_app.hh`, i.e. it doesn't seem to be an issue with a specific version or build of clingo.

**Comment by rkaminsk** [comment]
Yes, there are some slight differences because the solver is started in multi-shot mode. You can pass option `--single-shot`. This should make both variants equal.

PS: you should call `get()` on the handle returned by `solve()`.

**Comment by nuernbergk** [comment]
Is this difference documented somewhere? I'm not finding anything in the User's Guide.

**Comment by nuernbergk** [comment]
And Re: the PS: where and why? I am following the example. A `SolveResult` only seems to be useful for checking whether there actually are any more models, which doesn't seem to be relevant in the case of enumerating models.

**Comment by rkaminsk** [comment]
> Is this difference documented somewhere? I'm not finding anything in the User's Guide.

This option has been added after the latest revision of the user guide. Improving the user guide is a construction site for the future...

> And Re: the PS: where and why? I am following the example. A `SolveResult` only seems to be useful for checking whether there actually are any more models, which doesn't seem to be relevant in the case of enumerating models.

Indeed it does not change the enumerated models but it cleanly ends the search and finalizes the statistics.

**Comment by nuernbergk** [comment]
It still seems rather unintuitive that the default options when creating a `Clingo::Control` object are different from the default options used in the CLI and I don't quite understand why this design decision was made. But in any case, this solves my problem, thank you for your help.

**Comment by rkaminsk** [comment]
> It still seems rather unintuitive that the default options when creating a `Clingo::Control` object are different from the default options used in the CLI and I don't quite understand why this design decision was made. But in any case, this solves my problem, thank you for your help.

If the option is passed, solve can only be called a single time. Furthermore, the option just affects internal optimizations that can of course influence the order/time in which models are found. The final optimal value reported does not depend on this option. I think it is a reasonable default. It is disabled by default in the system because there it is know that there is just one call to the solver.
