### ISSUE TITLE
graph.lp:2:1-5: error: syntax error, unexpected <IDENTIFIER>

### ISSUE THREAD

**Issue by aymeric75** [potassco/clingo#500]
Hello,

With this command:

`clingo -t 6 --sat-prepro=2 --time-limit=7200 file.lp graph.lp`
[file.txt](https://github.com/user-attachments/files/15775433/file.txt)

and graph.lp attached and starting with

```

node(1,1)
node(1,2)
node(1,3)
node(1,4)
node(1,5)
node(1,6)

```

I get:

```
clingo version 5.7.1
Reading from file.lp ...
graph.lp:2:1-5: error: syntax error, unexpected <IDENTIFIER>

*** ERROR: (clingo): parsing failed
UNKNOWN
```

Any idea why ?

Thanks

[graph.txt](https://github.com/user-attachments/files/15775434/graph.txt)

**Comment by aymeric75** [comment]
[file.txt](https://github.com/user-attachments/files/15775444/file.txt)

**Comment by ejgroene** [comment]
perhaps you forgot the end each fact with a . (dot)?

**Comment by aymeric75** [comment]
exactly thanks a lot !
