### ISSUE TITLE
how to write the "different than" symbol in a .lp file ?

### ISSUE THREAD

**Issue by aymeric75** [potassco/clingo#501]
Hi,

Somewhere in an ASP code I need to write:
`
objtuple(I, (O1,O2),2) :- object(I,O1), object(I,O2), not constant(O1), not constant(O2), O1 **≠** O2.

`
[file.txt](https://github.com/user-attachments/files/15775600/file.txt)

For now I have writtent "!=" instead, because the ≠ creates an error:

`file.lp:46:98-100: error: syntax error, unexpected <VARIABLE>`

But I suspect that != is not appropriate (even if it does not create an error)

Any idea of how to write the "different than" symbol in an .lp file?

Thanks

**Comment by rkaminsk** [comment]
If you want to express that two terms are different, then `!=` is the right choice.

Consider the program

```prolog
p(1).
p(a).
p(3).

q(X,Y) :- p(X), p(Y), X!=Y.
```

which has solution

```prolog
p(1) p(a) p(3) q(a,1) q(3,1) q(1,a) q(3,a) q(1,3) q(a,3)
```

**Comment by ejgroene** [comment]
Section 3.1.8 states that != is used for ‘not equals’. Did your editor fold it into ≠?

**Comment by aymeric75** [comment]
I will use "!=" then, thanks
