### ISSUE TITLE
Beginner question: Python Support

### ISSUE THREAD

**Issue by JanBruemmer** [potassco/clingo#51]
Hi,

I've recently started to work with Clingo and I have a question.
I've never worked with Python before and I wonder how to run a python script with clingo.

I already have Python in my PATH variable but clingo still tells me, that it has been "built without python support". What else do I need to do?

**Comment by 0x326** [comment]
What OS are you using and are you building `clingo` from source code?

**Comment by JanBruemmer** [comment]
I'm using Windows 8.1 and yes I'm building clingo from source code.

**Comment by rkaminsk** [comment]
Python has to be available when you compile clingo. When running cmake, there should be a message wheather python was found or not.

**Comment by JanBruemmer** [comment]
I've looked into this further and I wonder what the clingo-script.exe file does. When I try to run it, it tells me that the Python27.dll is not on my computer, so I guess it has something to do with my problem.

A quick search showed that I do have the python27.dll, but it's inside my xampp folder, yet it is stated that I don't have it. Any ideas?

**Comment by rkaminsk** [comment]
Xampp is probably shipping with its own python version. To use clingo with python, you should install an official python release. I attached the relevant part of the installation instructions (from INSTALL.md) below. Note that it is important that the python27.dll is somewhere in your PATH (or next to the clingo executable). The python installer will ask you to modify the PATH variable for you.

The `clingo-python.exe` and `gringo-python.exe` executables are build with Python 2.7 support.

To run the executables with Python support, you have to install [Python 2.7.13 for Windows x86-64](https://www.python.org/ftp/python/2.7.13/python-2.7.13.amd64.msi).

**Comment by JanBruemmer** [comment]
I've updated clingo to the 5.2 version and now everything works fine.

@rkaminsk Thank you for your help.
