### ISSUE TITLE
Grounder output description

### ISSUE THREAD

**Issue by joshuaguerin** [potassco/clingo#511]
I've gone through the documentation, searched a bit in the email repo, and can't find documentation on the `--gringo` grounding output.

When I run even the simplest program:
```
a(1..3).
```

the grounder produces a lot of seemingly useful information:
```
asp 1 0 0
1 0 1 1 0 0
1 0 1 2 0 0
1 0 1 3 0 0
4 4 a(1) 0
4 4 a(2) 0
4 4 a(3) 0
0
```

I've been searching around, but I haven't been able to find a description of exactly *what* the output means. Where would I find documentation on how to read gringo output?

**Comment by BenKaufmann** [comment]
You can read about the intermediate language _aspif_ e.g. [here](https://arxiv.org/pdf/2008.06692#appendix.B) and [here](https://www.cs.uni-potsdam.de/wv/publications/DBLP_conf/iclp/GebserKKOSW16x.pdf#appendix.A).
