### ISSUE TITLE
Does Clingo support floating-point number?

### ISSUE THREAD

**Issue by navdeepkjohal** [potassco/clingo#515]
Hello,

Can you please tell me if clingo supports floating -point numbers or not?

I have a fact that says "one batch has 1.5 gallons of coffee. ". I want to write it as batch_size_gallons(1.5). but clingo reads the decimal after 1 as a full stop and throws an error that says:

<block>:3:21-22: error: syntax error, unexpected ., expecting ) or ;

The google search says that floating-point numbers are not supported by Answer-set programming. I am just checking if there is any work-around this that I do not know of.

Thanks
Navdeep

**Comment by rkaminsk** [comment]
Clingo does not support floats. It is possible to use them during grounding by using its API:

```python
#script (python)
import math
from clingo.symbol import String
def sqrt(x):
    return String(repr(math.sqrt(float(x.string))))
#end.
p(@sqrt("17.3")).
```

See also our list: >https://sourceforge.net/p/potassco/mailman/potassco-users/thread/0d78fb1b0eef6ddd729a856c013b79d2037a8bd8.camel%40cs.uni-potsdam.de/#msg37606655>
