### ISSUE TITLE
avoid canonicalize_file_name

### ISSUE THREAD

**Issue by haampie** [potassco/clingo#518]
This is a bit of a trivial request so feel free to ignore.

I noticed `canonicalize_file_name` is used here https://github.com/potassco/clingo/blob/65c976c0396405823ec65dd9eadb305511ba51eb/libgringo/src/input/nongroundparser.cc#L91 which causes the usual cascade of system calls on each path component

```
readlink("/this", 0x7ffcdc815600, 1023) = -1 EINVAL (Invalid argument)
readlink("/this/is", 0x7ffcdc815600, 1023) = -1 EINVAL (Invalid argument)
readlink("/this/is/some", 0x7ffcdc815600, 1023) = -1 EINVAL (Invalid argument)
readlink("/this/is/some/nested", 0x7ffcdc815600, 1023) = -1 EINVAL (Invalid argument)
readlink("/this/is/some/nested/path", 0x7ffcdc815600, 1023) = -1 EINVAL (Invalid argument)
readlink("/this/is/some/nested/path/to", 0x7ffcdc815600, 1023) = -1 EINVAL (Invalid argument)
readlink("/this/is/some/nested/path/to/somewhere", 0x7ffcdc815600, 1023) = -1 EINVAL (Invalid argument)
readlink("/this/is/some/nested/path/to/somewhere/file.lp", 0x7ffcdc815600, 1023) = -1 EINVAL (Invalid argument)
```

in my application it results in 50+ syscalls.

Looks like paths can be left relative, or joined with the current working dir, but canonicalizing is redundant?

**Comment by rkaminsk** [comment]
The function is used to improve the check whether a function is included more than once.

50+ syscalls also does not seem to be excessively expensive. Is this really a problem?

**Comment by haampie** [comment]
I said it was trivial ;p the usual unix way is stat and check the (dev, ino) tuple which is only one syscall. Feel free to close.

**Comment by rkaminsk** [comment]
> I said it was trivial ;p the usual unix way is stat and check the (dev, ino) tuple which is only one syscall. Feel free to close.

I'd rather close not having to figure out how to handle this on Windows then.
