### ISSUE TITLE
Script implemented functions within disjunctive heads

### ISSUE THREAD

**Issue by ubbc** [potassco/clingo#52]
I have noticed an issue where scripted functions appear as terms within the heads of disjunctive rules.
The following code illustrates the problem:
```asp
#script(python)
def v( x ):
	return x
#end.
a(i).
c ; u(@v(X)) :- a(X).
```
clingo 5.2.0 reports
```asp
tiny.lp:5:1-13: error: unsafe variables in:
 u(#Script0)::;c::
tiny.lp:5:7-12: note: '#Script0' is unsafe
```
As a workaround, a suitable variable can be assigned in the rule body:
```asp
c ; u(Y) :- a(X), Y=@v(X).
```
The error also occurs when the function is implemented using the Lua language.

**Comment by rkaminsk** [comment]
This is a problem with disjunctions that is already fixed in the master branch and will be included in the next release.

**Comment by ubbc** [comment]
Ok, that is great. Many thanks.
