### ISSUE TITLE
Regarding domain-specific heuristic with disjunctive atoms

### ISSUE THREAD

**Issue by mahi045** [potassco/clingo#524]
Hi 
Does Clingo's domain-specific heuristics work with disjunctive atoms? I have a disjunctive logic program:
```
p(f1) ; n(f1).
p(cf1) ; n(cf1).
:- p(f1), p(cf1).

p(f2) ; n(f2).
p(cf2) ; n(cf2).
:- p(f2), p(cf2).

p(f3) ; n(f3).
p(cf3) ; n(cf3).
:- p(f3), p(cf3).

p(f4) ; n(f4).
p(cf4) ; n(cf4).
:- p(f4), p(cf4).

:- not p(f1), not p(cf2), not p(cf3), not p(f4).
:- not p(cf1), not p(f2), not p(f3), not p(cf4).

sat :- not p(cf1), not p(f2), not p(cf3), not p(f4). 

:- not sat.

#show p/1.
```

I aim to compute minimal answer sets w.r.t. p/1 atoms. I use the following command:
```
clingo --dom-mod=false,show --enum-mode=domRec --heuristic=domain -n 0 <filename>
```

The clingo output is as follows:
```
clingo version 5.5.1
Reading from rule_enum.pl
Solving...
Answer: 1
p(cf4) p(f3) p(cf2) p(f1)
Answer: 2
p(cf4) p(f3) p(cf2)
Answer: 3
p(cf4) p(cf2)
Answer: 4
p(cf4) p(cf2) p(f1)
Answer: 5
p(cf4) p(f1)
Answer: 6
p(cf4) p(f3) p(f1)
Answer: 7
p(f3) p(f1)
Answer: 8
p(f3) p(cf2) p(f1)
Answer: 9
p(f3) p(cf2)
SATISFIABLE
```
Unfortunately, considering the answer set 3, answer sets 1, 2, and 4 (listed above) are not subset minimal answer sets w.r.t. atoms p/1. 

Is there an issue with my encoding, or am I misunderstanding something?

-Mahi

**Comment by BenKaufmann** [comment]
Hm, are you sure that you are correctly passing the options to clingo?
For me, `clingo  --dom-mod=false,show --enum-mode=domRec --heuristic=domain --stats -n0 /tmp/heu.lp`, where   `/tmp/heu.lp` is your program, produces the following four answer sets:
```
Solving...
Answer: 1
p(f3) p(f1)
Answer: 2
p(f3) p(cf2)
Answer: 3
p(cf4) p(f1)
Answer: 4
p(cf4) p(cf2)
SATISFIABLE
```
Furthermore, I would suggest updating clingo to a more recent version (e.g. [clingo-5.7.1](https://github.com/potassco/clingo/releases))
