### ISSUE TITLE
Projective Solution Enumeration via Python API

### ISSUE THREAD

**Issue by thojat** [potassco/clingo#525]
Hi,

Is there a way to activate projective solution enumeration and to add/retract project statements after grounding over the clingo/python API?

For example, I would like to generate all solutions (or brave consequences) for different sets of projected atoms and would like to avoid re-grounding or generating duplicate solutions w.r.t. the projected atoms.

I think one way to do this is to add a new lp file with project statements to the control object. But unfortunately there is no way to remove the project statements without grounding everything from scratch.

I think it would be a nice feature being able to pass a list of symbols to project to to clingo over the API after grounding, similar to assumptions or externals.

**Comment by rkaminsk** [comment]
@thojat, the required functionality is available in the latest wip branch and development packages.
