### ISSUE TITLE
Intermediate Question: Grounding different ASP #program blocks by commandline

### ISSUE THREAD

**Issue by 0x326** [potassco/clingo#53]
I was wondering if there was a way to ground multiple `#program` blocks from the `clingo` commandline.

For the given file:

    #program foo(constant_1, constant_2).
    a(constant_1, constant_2).
    
    #program bar.
    b.

How can I ground both program `foo` and `bar` (in addition to the implicit program `base)?

In Python, this can be accomplished in the following snippet:

```Python
from collections import namedtuple
import clingo

ASPProgram = namedtuple('ASPProgram', 'name, arguments')

if __name__ == '__main__':
    clingo_control = clingo.Control()
    clingo_control.load('./path/to/asp_file.lp')
    asp_programs = (
        ASPProgram(name='foo', arguments=(4, 5)),
        ASPProgram(name='foo', arguments=(66, 1)),
        ASPProgram(name='bar', arguments=tuple())
    )
    clingo_control.ground(asp_programs)
    clingo_control.solve()
```

Upon solving, I could investigate that my answer set is `a(4, 5)`, `a(66, 1)`, and `b`.

**Comment by rkaminsk** [comment]
If clingo has been compiled with python support, you can simply embed your python code in a source file passed to clingo. The examples folder contains a lot of examples that use this feature.

```
#script (python)
from collections import namedtuple
import clingo

ASPProgram = namedtuple('ASPProgram', 'name, arguments')

def main(clingo_control):
    # can be passed from commandline as well
    # clingo_control.load('./path/to/asp_file.lp')
    asp_programs = (
        ASPProgram(name='foo', arguments=(4, 5)),
        ASPProgram(name='foo', arguments=(66, 1)),
        ASPProgram(name='bar', arguments=tuple())
    )
    clingo_control.ground(asp_programs)
    clingo_control.solve()
```
#end.

**Comment by 0x326** [comment]
@rkaminsk This works. Thank you very much!
