### ISSUE TITLE
Linking on Intel 32-bit fails

### ISSUE THREAD

**Issue by andreasbaumann** [potassco/clingo#57]
```
: && /usr/bin/clang++  -march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -O3 -DNDEBUG  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now   -rdynamic clasp/app/CMakeFiles/clasp.dir/clasp_app.cpp.o clasp/app/CMakeFiles/clasp.dir/main.cpp.o  -o bin/clasp  -Wl,-rpath,:::::::: lib/libclasp.a -lpthread lib/libpotassco.a && :
lib/libclasp.a(minimize_constraint.cpp.o): In function `Clasp::SharedMinimizeData::resetBounds()':
/build/clingo/src/clingo-5.2.0/clasp/src/minimize_constraint.cpp:(.text+0x1cc): undefined reference to `__atomic_store_8'
```

Using g++ instead of clang++ works, most likely C++-11 atomics are missing for certain data
types in clangs C++ library.

**Comment by rkaminsk** [comment]
Hi, on linux clang typically uses the same libstdc++ as gcc (on macos this might be different). To use clang's libc++ you explicitely have to pass -stdlib=libc++. Also the libc++ often has to be installed separately. So I guess the problem lies elsewhere. You can try to add option -v to the commandline above and try to spot a difference between the linker calls of clang++ and g++. I can give 32bit compilation a try later.

**Comment by rkaminsk** [comment]
Hi, I could reproduce the problem with clang. Manually adding `-latomic` to the linker options solves the problem. If gcc is Arch's default compiler, I see no reason not to switch to gcc. I'll discuss with the clasp developer how to add a cmake check automatically adding the library.

**Comment by andreasbaumann** [comment]
Thanks for confirming the -latomic is working. I also think, this is the best way to go. See also
the discussions we had on https://github.com/archlinux32/packages/pull/3. I'm only providing a
patch for 32-bit for the upstream 64-bit ArchLinux, so being as close as possible to the original
PKGBUILD and to the author's wishes is the right way to go. :-)

**Comment by andreasbaumann** [comment]
I'll redo and retest the pull request using -latomic..

**Comment by andreasbaumann** [comment]
Works and fine from me point of view.
