### ISSUE TITLE
Bug in parse_program function with #inf and #sup

### ISSUE THREAD

**Issue by javier-romero** [potassco/clingo#59]
Hola!

At 
  `clingo/examples/gringo/ast`
If I add the line to example.lp:
  `a(#inf,#sup).`
Then with 
 `gringo --text visitor.lp` 
I get at the output:
  `a(#sup,#inf,0).
  a(#sup,#inf,1).
  a(#sup,#inf,2).`
The terms #sup and #inf are switched.

Cheers,
Javier

**Comment by rkaminsk** [comment]
Hi, the issue is fixed in the wip and master branches.
