### ISSUE TITLE
Signal Handling is Inconsistent in clingo

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#6]
When having a (python) main function inside your encoding,
Ctrl+C can be handled differently depending on the exact moment when it was triggered.
It can either end the process, in clasp_app.cpp ll 229 with exit(getExitCode());
or it can report INTERRUPT as a result of the solve call in the python script,
which has to be handled manually (if not the solving continues normally, and further signals will be queued ? ).

**Comment by rkaminsk** [comment]
@BenKaufmann can you please check if this commit fixes the issue: 4ab34e0c7eb346ed98b902ec8f12c9b3b312f6c2

**Comment by rkaminsk** [comment]
Merged the commit.
