### ISSUE TITLE
Request: update tutorial/manual and example comments

### ISSUE THREAD

**Issue by jachymb** [potassco/clingo#61]
Hello,
I am trying to get familiar with clingo, but I am struggling to find good resources.
The manual available at http://wp.doc.ic.ac.uk/arusso/wp-content/uploads/sites/47/2015/01/clingo_guide.pdf is for version 3.x, using version 5.2 I am unable to even run some of the examples there.
Alternatively, more verbose commentary for the examples such as https://github.com/potassco/clingo/tree/master/examples/clingo/opt  would be greatly appreciated.

**Comment by rkaminsk** [comment]
Hi, you should use a more [recent version of our guide](https://sourceforge.net/projects/potassco/files/guide/2.0/). This version was written for clingo series 4, which is much closer to clingo 5 than clingo 3. You find (a fixed horizon version of) the towers of hanoi problem in the introduction. Later in the guide you find an incremental blocksworld problem. Feel free to ask if you have more specific questions.

**Comment by rkaminsk** [comment]
FYI: we just released a new version of the guide: https://github.com/potassco/guide/releases
