### ISSUE TITLE
Infinite looping with incremental solving

### ISSUE THREAD

**Issue by lezan** [potassco/clingo#62]
Hello,
I am a newbie with ASP and Clingo and I am trying to develop a clingo program for airport-cargo problem (from Russell Norvig cap 10.1).
I tried to follow the Blocks World Planning from the guide-2.0, but I failed.
[This](https://gist.github.com/lezan/974e97451ff66cd5fff968e0014d79d8) is what I wrote until now.
If I try to run that, Clingo will loop forever, and output is "Solving...".
There are also a PDDL definition of the problem, maybe can be useful.
You can ignore comment.
Can someone point me in the right direction? It is from two days that I am trying to solve this problem.
Thanks for you answer.

**Comment by rkaminsk** [comment]
Hi, there is certainly more than one way to encode this. Your encoding was a bit lengthy and I did not try to fully comprehend it. I think the most crucial thing that was missing were inertia rules specifying that a fluent does not change if it has not been explicitly removed. In the encoding below I tried to encode your PDDL specification as faithfully as possible:

````prolog
%*
Init(At(C1, SFO) ∧ At(C2, JFK ) ∧ At(P1, SFO) ∧ At(P2, JFK )
    ∧ Cargo(C1) ∧ Cargo(C2) ∧ Plane(P1) ∧ Plane(P2)
    ∧ Airport(JFK ) ∧ Airport(SFO))

Goal(At(C1, JFK ) ∧ At(C2, SFO))

Action(Load(c, p, a),
    PRECOND: At(c, a) ∧ At(p, a) ∧ Cargo(c) ∧ Plane(p) ∧ Airport(a)
    EFFECT: ¬ At(c, a) ∧ In(c, p))

Action(Unload(c, p, a),
    PRECOND: In(c, p) ∧ At(p, a) ∧ Cargo(c) ∧ Plane(p) ∧ Airport(a)
    EFFECT: At(c, a) ∧ ¬ In(c, p))

Action(Fly(p, from, to),
    PRECOND: At(p, from) ∧ Plane(p) ∧ Airport(from) ∧ Airport(to)
    EFFECT: ¬ At(p, from) ∧ At(p, to))
*%

#include <incmode>.

#program base.

at(c1,sfo,0).
at(c2,jfk,0).
at(p1,sfo,0).
at(p2,jfk,0).
cargo(c1).
cargo(c2).
plane(p1).
plane(p2).
airport(jfk).
airport(sfo).

#program step(t).

% choose exactly one action

1 {   load(C,P,A,t) : cargo(C), plane(P), airport(A)
  ; unload(C,P,A,t) : cargo(C), plane(P), airport(A)
  ;    fly(P,F,T,t) : plane(P), airport(F), airport(T)
  } 1.

% preconditions

:-   load(C,P,A,t), not at(C,A,t-1).
:-   load(C,P,A,t), not at(P,A,t-1).

:- unload(C,P,A,t), not in(C,P,t-1).
:- unload(C,P,A,t), not at(P,A,t-1).

:-    fly(P,F,T,t), not at(P,F,t-1).

% effects

-at(C,P,t) :- load(C,P,A,t).
 in(C,P,t) :- load(C,P,A,t).

 at(C,A,t) :- unload(C,P,A,t).
-in(C,A,t) :- unload(C,P,A,t).

-at(P,F,t) :- fly(P,F,T,t).
 at(P,T,t) :- fly(P,F,T,t).

% inertia

at(X,Y,t) :- at(X,Y,t-1), not -at(X,Y,t).
in(X,Y,t) :- in(X,Y,t-1), not -in(X,Y,t).

#program check(t).

:- not at(c1, jfk, t), query(t).
:- not at(c2, sfo, t), query(t).
````

**Comment by lezan** [comment]
Hello,
first of all, thanks for your quickly answer.
I tried your code and yes, it work like a charm.
I followed your suggestion and I inspected my code and maybe I found the problem:
`init(**in**(c1,sfo)).
init(**in**(c2,jfk)). 
init(at(p1,sfo))..
init(at(p2,jfk)).`
-->
`init(**at**(c1,sfo)). 
init(**at**(c2,jfk)). 
init(at(p1,sfo)). 
init(at(p2,jfk)).`

By the way, I am using Clingo on my course at University, so I want ask you a question, 'cause I need to undestand, you know, it is for an exam: when you said  

> I think the most crucial thing that was missing were inertia rules

I followed cap 5.3.2 of the Guide-2.0 where it used **holds**.
If I write something like that
`holds(F, 0) :- init(F).
holds(F, t) :- holds(F, t - 1), not -holds(F, t).
-holds(F, t) :- -holds(F, t - 1), not holds(F, t).`
Is it not a inertia rules?

However, [this](https://gist.github.com/lezan/18e06a4806d2cca17a314963a6eeddb8) is what I actually have and seems to work, but I know, it is not clean like your!

**Comment by rkaminsk** [comment]
> Is it not a inertia rules?

Yes, I missed these between all the other rules. Looks like it was really the initial situation that was inconsistent in your first encoding.

I did not wrap fluents in the holds predicate because of the way I encoded. It is also possible to specify your pddl instane completely as facts and write an encoding that can solve any pddl problem described like this. In this setting I would probably have used init, goal, action, precondition, and effect predicates to capture the instance. And finally used holds predicates in the encoding to solve the instance. As you can see with your inertia rules this allows for writing more general rules that are independend of the fluent names.

PS: Hope you get what I mean with fluent. I guess in pddl there was another name for the concept.

**Comment by javier-romero** [comment]
Hi, 

Just do add on that, in case it may be helpful. 
This is one very good reference on planning in ASP:
 Vladimir Lifschitz: Answer Set Planning. ICLP 1999: 23-37
and this is some of our recent work on pddl planning, which could be of interest to you:
 Yannis Dimopoulos, Martin Gebser, Patrick Lühne, Javier Romero, Torsten Schaub:
 plasp 3: Towards Effective ASP Planning. LPNMR 2017: 286-300

Best wishes,
Javier

**Comment by lezan** [comment]
> Looks like it was really the initial situation that was inconsistent in your first encoding.
True. It was that.

I used holds predicate 'cause I need to develop a soluton for another domain, so I need to be more general as possible with my ASP solution.
Anyway now is going great thanks to your help.

For me, thats is solve.
Thanks for your help!

**Comment by CesareIurlaro** [comment]
Hi everyone, I'm actually studying on the same language and problem.
@rkaminsk your solution is wonderful, but i don't understand how exactly `#program step` works.
Could you please lead me to some sort of documentation?

**Comment by rkaminsk** [comment]
The most detailed description you find in the paper [Multi-shot ASP solving with clingo](https://arxiv.org/abs/1705.09811) but also our [guide](https://github.com/potassco/guide/) uses the incremental mode.

**Comment by CesareIurlaro** [comment]
Thank you very much! :)
