### ISSUE TITLE
Unsafe facts?

### ISSUE THREAD

**Issue by JanBruemmer** [potassco/clingo#63]
Hi,

I was experimenting a bit more with clingo and have a question about facts. In my logic program new.lp is the following line of code:

fluent(POI).

Once I compile my program, I get the following error message:

error: unsafe variables in:
(fluent(POI)) :- [#inc_base].
note: 'POI' is unsafe.

In clingo 5.1 I never had any issues with facts. Since 5.2 I've gotten this message.
My questions are: 

- Why is POI unsafe, despite it being inside a fact?
- What does the [#inc_base] mean?

Note: I do know what unsafe variables are.

**Comment by rkaminsk** [comment]
Clingo never accepted variables in facts. A program is grounded before it is passed to the solving component. Grounding means substituting all relevant ground terms for variables. In your program above any term could be substituted for `POI`. Hence, such programs rejected as unsafe.

The `[#inc_base]` appears in rule bodies of rules appearing in a `#program base` part, which is the default program part if not explicitely given. If you do not intend to write multi-shot programs, you can simply ignore this.
