### ISSUE TITLE
Support for binary/hex/oct numerical literals in gringo

### ISSUE THREAD

**Issue by jachymb** [potassco/clingo#65]
It would be nice, if gringo understood binary and hex and oct numerical literals. For example: `0xD = 0o15 = 0b1101 = 13`. These can sometimes make the source code more readable.

**Comment by rkaminsk** [comment]
This should not be too hard to implement. I'll think about it.

**Comment by rkaminsk** [comment]
64

**Comment by jachymb** [comment]
Seems to work just right in the new release! So just wanted to let you know I appreciate that, thanks!
