### ISSUE TITLE
Changing Heuristics Between Solutions

### ISSUE THREAD

**Issue by sidschingis** [potassco/clingo#70]
I'm currently modeling an optimization problem using the domain heuristics.
If I understood correctly this will only influence the search while looking for a solution. Is there a way to influence the search between solutions? E.g. changing heuristics after the solver has encountered N solutions to try to get out of a local Optimum.

**Comment by rkaminsk** [comment]
You cannot change the heuristics during solving. But you can do so after solving. Why not simply stop the current search, change the heuristics, and then solve again.

**Comment by sidschingis** [comment]
I was looking for a way to not lose the insights gained during the search such as conflicts and solutions known to be non optimal, since the grounding and searching takes quite some time . Grounding takes about 15s depending on instance size and the search would usually stay on the local optimum even after several minutes.
 
Is it maybe possible to separately ground the instance and the heuristic, so that the instance and the encoding does not have to be regrounded when changing the heuristic? When trying to ground just the heuristic rule gringo would return an empty file.

**Comment by rkaminsk** [comment]
You don't have to do the grounding again, clingo supports incremental solving keeping learned constraints and heuristic information.

```
1 { a; b; c }.
1 { b; c; d }.
1 { c; d; e }.

#minimize { 1,a : a; 1,b : b; 1,c : c; 1,d : d; 1,e : e }.

#script (lua)

function main(prg)
    prg:ground({{"base", {}}})
    prg:solve()
    # change the heuristic here ...
    prg:solve()
end

#end.
```

Note that you can also use `#script (python)`. Have a look at the [clingo examples](https://github.com/potassco/clingo/tree/master/examples) and the [python api reference](https://potassco.org/clingo/python-api/current/clingo.html).

**Comment by sidschingis** [comment]
I will have a look and try that out, thank you very much for your help.

**Comment by sidschingis** [comment]
The python api works great. I am adding the heuristics via programs defined in the encoding file.
However I did not find a way to "unground" programs, to remove a heuristic again. I could order the sub programs and introduce an atom in each subsequent program that invalidates the previous, but that would not allow me to freely combine them. Is it possible to reset the Control object to the "base" grounding?

    #const solveTimeout=1.

    #script (python)

    class Solver:
        def __init__(self):
            #init members
            self.optValue   = -1
            self.optSymbols = []

        def run(self, prg):
            # init solver configuration
            prg.configuration.solver.heuristic       = "domain"
            prg.use_enumeration_assumption      = False
            self.timeout = prg.get_const("solveTimeout").number
            
            # ground base programm
            base = [("base", [])]
            prg.ground(base)
            
            # get heuristic groups
            heuristicGroups = self.getHeuristicGroups()
            
            # iterate over heuristic groups
            for group in heuristicGroups:
                parts = []
                # append heuristic rules
                for heuristic in group:
                    print(heuristic)
                    parts.append((heuristic, []))
                prg.ground(parts)
                # solve this heuristic group
                with prg.solve(on_model=self.onModel, async=True) as handle:
                    res = handle.wait(self.timeout)
                    # do something asynchronously
                    print("Solving")
                #break if we have an optimum
                if (res):
                    break
            
            #show results
            print("Final (Local) Optimum:")
            print(self.optValue)
            #print(self.optSymbols)
                    
        def getHeuristicGroups(self):
            groups = []
            
            groups.append(["hPreferKnownSeller"])
            groups.append(["hPreferCheaper"])

            return groups;
            
        def onModel(self,model):
            cost = model.cost[0]
            if (cost < self.optValue or self.optValue < 0):
                print ("Found new optimum")
                print (cost)
                self.optValue   = cost
                self.optSymbols = model.symbols(shown=True)
            
    def main(prg):
        Solver().run(prg)

    #end.

**Comment by rkaminsk** [comment]
You can make heuristic atoms subject to externals to turn them on or off as you like.
```
#script (python)

from clingo import Function

def get_sign(k):
    if k.number == 0:
        return Function("false")
    return Function("true")

def main(prg):
    prg.ground([("base", []), ("step", [0])])
    prg.assign_external(Function("step", [0]), True)
    prg.solve()
    prg.release_external(Function("step", [0]))
    prg.ground([("step", [1])])
    prg.assign_external(Function("step", [1]), True)
    prg.solve()


#end.

#program step(k).

#heuristic p(X) : step(k), S=@get_sign(k). [1,S]
#external step(k).

#program base.

3 { p(1..10) }.
2 { p(1..5) }.
4 { p(3..8) }.
2 { p(7..9) }.
3 { p(2..9) }.
```

**Comment by sidschingis** [comment]
Sorry for bothering you again but I'm running into another problem.
It seems like the heuristic rule is ignored for the init modifier if the body contains an external term.

Given the following base program:

    1{p(X):X=1..2}1.

    #external useHeuristic(1..2).
 
    #script(python)
    import clingo
    def main(prg):
        prg.ground([("base", [])])
        prg.assign_external(clingo.Function("useHeuristic", [1]), True)
        prg.solve()
        prg.assign_external(clingo.Function("useHeuristic", [1]), False)
        prg.assign_external(clingo.Function("useHeuristic", [2]), True)
        prg.solve()
        
    #end.

Running it produces the following output:

    $ clingo-python external.lp --heuristic=Domain
    clingo version 5.2.2
    Reading from external.lp
    Solving...
    Answer: 1
    p(2)
    Solving...
    Answer: 1
    useHeuristic(1) p(2)
    SATISFIABLE

However adding 

    #heuristic p(X): X=1..2, useHeuristic(1). [X, init]

to the base program, gives the same result:
    
    $clingo-python external.lp --heuristic=Domain
    clingo version 5.2.2
    Reading from external.lp
    Solving...
    Answer: 1
    p(2)
    Solving...
    Answer: 1
    useHeuristic(1) p(2)
    SATISFIABLE

Shouldn't it return p(1) for the second run?
Like in:

    #heuristic p(X): X=1..2. [X, init]
    
    $ clingo-python external.lp --heuristic=Domain
    clingo version 5.2.2
    Reading from external.lp
    Solving...
    Answer: 1
    p(1)
    Solving...
    Answer: 1
    useHeuristic(1) p(1)
    SATISFIABLE

Using the false modifier works as expected

    #heuristic p(X): X=1..2,useHeuristic(1). [X, false]
    
    $ clingo-python external.lp --heuristic=Domain
    clingo version 5.2.2
    Reading from external.lp
    Solving...
    Answer: 1
    p(2)
    Solving...
    Answer: 1
    useHeuristic(1) p(1)
    SATISFIABLE

What am I missing here? 

[external.txt](https://github.com/potassco/clingo/files/1479006/external.txt)

**Comment by rkaminsk** [comment]
Hi, I do not know exactly how the init modifier works. I suspect that it is applied before solving starts and, hence, only works if the condition is a fact. @BenKaufmann might be able to tell you more.

**Comment by BenKaufmann** [comment]
@rkaminsk 
You are right. The `init` modifier is only applied once before solving starts. So, if it has some condition that is not true in the beginning, the modification is ignored.

**Comment by sidschingis** [comment]
I see, what about the factor modifier then, since that should be  continuously applied?

**Comment by rkaminsk** [comment]
Hi, I think the same applies to factor modifier. The init modifier can be adjusted in a successive step without using externals though:

```
#program step1.

#heuristic p(1). [1, init]
#heuristic p(2). [0, init]

#program step2.

#heuristic p(1). [-1, init]
#heuristic p(2). [1, init]

#program base.

1 {p(1); p(2)} 1.

#script (python)

def main(ctl):
    ctl.ground([("base", [])])
    ctl.ground([("step1", [])])
    ctl.solve()
    ctl.ground([("step2", [])])
    ctl.solve()

#end.
```

Note the `-1000` for `p(1)` in the second step. It looks like the init modifier is additive. This results in:

```
clingo test.lp --heuristic=domain
clingo version 5.2.2
Reading from test.lp
Solving...
Answer: 1
p(2)
Solving...
Answer: 1
p(1)
SATISFIABLE
```
