### ISSUE TITLE
JSON output is broken with Python print

### ISSUE THREAD

**Issue by domoritz** [potassco/clingo#72]
When I run this program

```
#script (python)

def main(prg):
    print "foo"

#end.
```

with JSON output, the generated output is not valid JSON.

`clingo print.lp --outf=2`

```json
{
  "Solver": "clingo version 5.2.2",
  "Input": [
    "print.lp"
  ],
  "Call": [
    {
foo

    }
  ],
  "Result": "UNKNOWN",
  "Models": {
    "Number": 0,
    "More": "yes"
  },
  "Calls": 1,
  "Time": {
    "Total": 0.087,
    "Solve": 0.000,
    "Model": 0.000,
    "Unsat": 0.000,
    "CPU": 0.058
  }
}
```

It would be good to capture stdout and add a property to the JSON output.

**Comment by rkaminsk** [comment]
Using print statements will mess up the output. There is no (reasonable) way around this. Still it would be nice to be able to extend the JSON-output. I mark this as a feature request. Don't expect anything to be implemented soon because I do not have time for such things at the moment.

**Comment by domoritz** [comment]
Thank you for clarifying this. As a workaround, I print the JSON output to stderr or write directly to a file.

**Comment by rkaminsk** [comment]
The upcoming clingo release will provide an API to add elements to the statistics and symbols to answer sets (from a propagator). Both will appear in the JSON output then. This does not give full control to manipulate the JSON output but should provide enough control for common use cases.

**Comment by rkaminsk** [comment]
In the wip branch you can already extend models and statistics. While this does not allow for arbitrary modifications of the JSON output. It should give enough points to add information in practice.
