### ISSUE TITLE
Released clingo does not come with Python support for linux

### ISSUE THREAD

**Issue by domoritz** [potassco/clingo#75]
I'm using clingo from the packages released on Github. On travis (which runs ubuntu), I get the following error: `error: python support not available`. Details at https://travis-ci.org/domoritz/draco/builds/310011820 and here is how I am installing clingo: https://github.com/domoritz/draco/blob/master/.travis.yml#L6.

**Comment by rkaminsk** [comment]
It is not easily possible to ship clingo with python support so that it runs on all the available linux distributions.
