### ISSUE TITLE
Change Global Restart Policy from Python API

### ISSUE THREAD

**Issue by diane-wagner** [potassco/clingo#76]
Hello,

we are two students doing our bachelor project and for our work we would like to change the global_restart policy to L from the Python API but are a bit unsure about how to do it, because everything we seem to try going from the documentation gives us an error. For example these two strings from the guide and help file respectively (we do not want to set a global limit):

prg.configuration.solve.global_restarts = "0,[L,100,1.5]"

prg.configuration.solve.global_restarts = "L,5"

Can you help us out a bit? Thanks already in advance!

**Comment by rkaminsk** [comment]
On Wednesday, December 13, 2017 8:40:27 AM CET diane-wagner wrote:
> Hello,
> 
> we are two students doing our bachelor project and for our work we would
> like to change the global_restart policy to L from the Python API but are a
> bit unsure about how to do it, because everything we seem to try going from
> the documentation gives us an error. For example these two strings from the
> guide and help file respectively (we do not want to set a global limit):
> 
> prg.configuration.solve.global_restarts = "0,[L,100,1.5]"
> 
> prg.configuration.solve.global_restarts = "L,5"
> 
> Can you help us out a bit? Thanks already in advance!

You are specifying an invalid value for the option. Calling for example
  prg.configuration.solve.global_restarts = "100,L,5"
or
  prg.configuration.solve.global_restarts = "-1,L,5"
works as expected. -R

**Comment by diane-wagner** [comment]
Thank you very much :+1:
