### ISSUE TITLE
API clingo_configuration_type

### ISSUE THREAD

**Issue by andrejpetras** [potassco/clingo#77]
I understand that the method should return the type of the configuration parameter.

The configuration parameter type is defined in the clingo_configuration_type:
```c
enum clingo_configuration_type {
    clingo_configuration_type_value = 1, //!< the entry is a (string) value
    clingo_configuration_type_array = 2, //!< the entry is an array
    clingo_configuration_type_map   = 4  //!< the entry is a map
};
```

But the method returns int values: 1,2,3,4,5
For example:
tester – returns int value 4 and it is clingo_configuration_type_map = 4
solver – returns int value 6 but it is  clingo_configuration_type_map = 4
sign_fix, del_max – returns int value 5 but it is clingo_configuration_type_value = 1
configuration – returns int value 5 but it is clingo_configuration_type_map = 4

Source code of the method:
```c
extern "C" bool clingo_configuration_type(clingo_configuration_t *conf, clingo_id_t key, clingo_configuration_type_bitset_t *ret) {
    GRINGO_CLINGO_TRY {
        int map_size, array_size, value_size;
        conf->getKeyInfo(key, &map_size, &array_size, nullptr, &value_size);
        *ret = 0;
        if (map_size >= 0)   { *ret |= clingo_configuration_type_map; }
        if (array_size >= 0) { *ret |= clingo_configuration_type_array; }
        if (value_size >= 0) { *ret |= clingo_configuration_type_value; }
    }
    GRINGO_CLINGO_CATCH;
}
```

It looks like the method returns union of the types.

Could you please check the “clingo_configuration_type” method in the API.
I think the method should return unique configuration parameter type for each configuration parameter.

**Comment by rkaminsk** [comment]
The type is a bit set. So 6 means it can be used as both map and array (using it as a map accesses the first element of the array here). And with 5 it can be assigned a value and be used as a map. The correct check is: `if (type & clingo_configuration_type_map) { ... }`
