### ISSUE TITLE
"Fatal Python error: take_gil: NULL tstate" in  python 3.6.4 on macOS 10.13.2

### ISSUE THREAD

**Issue by symbol-zy** [potassco/clingo#79]
The Python library built from the current master branch with Python 3.6 on macOS high Sierra(10.13.2) gives the following error:

       In [1]: import clingo
       Fatal Python error: take_gil: NULL tstate
       Abort trap: 6

I also tried installation from Anaconda cloud using "conda install -c potassco clingo", it ended up the same. Any help would be great!

Strange! This error does not come out when using Python 3.6 on Ubuntu 16.04.

**Comment by rkaminsk** [comment]
I can say is that clingo works fine with other python versions on Linux, Windows, and MacOS as well. For example, this includes python2 from anaconda but also python3 from homebrow on MacOS. Maybe something goes wrong when building the module or maybe there is something wrong with the python3 version in anaconda. I think that the clingo source as such code is okay. I have to look deeper into this...

```
$ /usr/local/bin/python3 
Python 3.6.4 (default, Jan  6 2018, 11:51:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import clingo
>>> quit()

$ ~/conda3/bin/python3
Python 3.6.3 |Anaconda, Inc.| (default, Dec  5 2017, 17:30:25) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import clingo
Fatal Python error: take_gil: NULL tstate
```

**Comment by rkaminsk** [comment]
With anaconda's python3, loading the module fails if the extension module is linked against python3. Instead using `-undefined dynamic_lookup` fixes the problem. This change is a bit difficult to add to the build system. I will see how to add this and then provide an updated clingo package.

**Comment by symbol-zy** [comment]
You are awesome! If possible, please update the clingo package on Anaconda cloud, it is much easier to install from there. Thanks very much.

**Comment by rkaminsk** [comment]
The conda package should work now.
