### ISSUE TITLE
Segfault in MinimizeBuilder

### ISSUE THREAD

**Issue by ingdas** [potassco/clingo#87]
The attached file segfaults in Clingo with the error:
```
*** ERROR: (clingo): Clasp::MinimizeBuilder::SharedData* Clasp::MinimizeBuilder::build(Clasp::SharedContext&)@715: contract violated: ctx.ok() && !ctx.frozen()
```
This theory is not supposed to make any sense or have any models, but is a part of an automatically generated ASP model. 

[segClingo.txt](https://github.com/potassco/clingo/files/1769026/segClingo.txt)

**Comment by rkaminsk** [comment]
This seems to be a bug with clingo 5 and 5.1. With version 5.2 I cannot reproduce the problem. It's probably best if you update to the latest version.
