### ISSUE TITLE
Projected model enumeration

### ISSUE THREAD

**Issue by mariusmoldovan** [potassco/clingo#88]
Hello,

We are using libclasp and libgringo libraries in D-FLAT. As I understand , clingo5 allows the use of #project directly in the ASP encoding but it is still necessary to pass --project as a command line argument. However, we call gringo and clasp not from the command line but directly in the code. Is there a way of setting this option for projected model enumeration in the code?

Thank you,
Marius

**Comment by rkaminsk** [comment]
It can be set from Python:
```python
import clingo
ctl = clingo.Control()
ctl.configuration.solve.project = "project,3"
```

**Comment by mariusmoldovan** [comment]
Thank you! As we don't use Python in D-FLAT: can it be set also with c++?

**Comment by rkaminsk** [comment]
The same functionality is available in the C++ interface. If you are using libgringo and libclasp directly (which you should avoid and better use the public API we provide) it is also possible. Just have a look at how functions to set the configuration are implemented. This should be possible by using clasp's facade if I remember correctly.
