### ISSUE TITLE
Build for the web

### ISSUE THREAD

**Issue by domoritz** [potassco/clingo#90]
I'm trying to build clingo for the web. 

I tried to follow the installation steps but added `-DCLINGO_BUILD_WEB=ON`. 

`cmake . -DCLINGO_BUILD_WEB=ON -DCLINGO_BUILD_WITH_LUA=OFF -DCLINGO_BUILD_WITH_PYTHON=OFF`

When I run `make web`, it almost works:

```
...
[ 96%] Building CXX object libclingo/CMakeFiles/libclingo.dir/__/clasp/app/clasp_app.cpp.o
[ 97%] Linking CXX shared library ../bin/libclingo.dylib
[ 97%] Built target libclingo
Scanning dependencies of target web
[ 98%] Building CXX object app/web/CMakeFiles/web.dir/main.cc.o
[100%] Linking CXX executable ../../bin/clingo
clang: error: no such file or directory: 'EXPORTED_FUNCTIONS=["_run"]'
make[3]: *** [bin/clingo] Error 1
make[2]: *** [app/web/CMakeFiles/web.dir/all] Error 2
make[1]: *** [app/web/CMakeFiles/web.dir/rule] Error 2
make: *** [web] Error 2
```

I appreciate any help with this.

**Comment by rkaminsk** [comment]
There is a user who created an [example](<https://github.com/Aluriak/webclingo-example>) how to do this. I also put some notes in the [Installation instructions](https://github.com/potassco/clingo/blob/wip/INSTALL.md#compilation-to-javascript). Note that I do not test this regularly and typically only touch it before I am releasing a new clingo version.

**Comment by domoritz** [comment]
Thank you @rkaminsk.  Do you use cmake to create the web target when you make a release?

**Comment by rkaminsk** [comment]
Check the installation instructions. I am using cmake with the emcmake wrapper provided by emscripten.
