### ISSUE TITLE
Is it possible to obtain the proof tree?

### ISSUE THREAD

**Issue by OFR92** [potassco/clingo#94]
For example for the following logic program:
```
p(a,b).
q(c,d).
q(e,f).

r(X,Y) :- q(X,Y).
```

I would like to know that for the output `r(c,d)` the fact `q(c,d)` was used.

**Comment by rkaminsk** [comment]
clingo (and clasp for that matter) can in general not return proof trees for solutions. In your specific case, you might want to check option `--keep-facts` to keep facts in rule bodies.

**Comment by OFR92** [comment]
Yup, this works for me. Thanks.
