### ISSUE TITLE
Test if a clingo_statistic object (map) contains a key

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#95]
Is there a possibility to test whether a statistics map contains a certain k without iterating over the map ?
`clingo_statistics_map_at(stats,key,"name", &result)`
 seems to return false in case that "name" is not contained in the map, but it also sets the error code.
Would it make sense to set
result = 0 in the case that "name" does not exist ?

**Comment by rkaminsk** [comment]
There is no function to test this. I could add a _has_subkey function, similar to what is provided for configuration objects.

**Comment by rkaminsk** [comment]
Since this is going to be addressed in #108, I am closing this issue.
