### ISSUE TITLE
Loading CNF files with the python API

### ISSUE THREAD

**Issue by khaettig** [potassco/clingo#98]
Hi,

we want to use clasp as a SAT-solver and also want to make use of the clingo python API. Clasp itself is able to load files in cnf/dimacs format but we can't find a way to achieve this inside the API. Is there a way to do this without converting the problem to a .lp-file?

**Comment by rkaminsk** [comment]
The clingo APIs can only be used with logic programs and there is no dedicated python API for clasp.
